USES += contrib/brl contrib/brl/bbas core

LIBRARY := brct
VERSION := 1.0

MANPAGE_SOURCES += brct_algos.h
MANPAGE_SOURCES += kalman_filter.h

################################
include ${IUEROOT}/config/top.mk
################################
