USES += vxl
USES += mul
include ${IUEROOT}/vxl/vnl/algo/config.mk
include ${IUEROOT}/vxl/vil/config.mk

IULIBS := -lmil -lvpdfl -lmbl -lvnl-io -lvnl-algo -lvgl -lvnl -lvil -lvsl -lvpl


TESTS += test_mil.cxx
TESTS += test_gauss_reduce_2d.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
