VXL := 1

USES = vxl
IULIBS := -lvnl-algo -lnetlib -lvnl -lvcl

CODE_SNIPPET      += vnl_svd.cxx
MINI_PROG_SOURCES += vnl_amoeba.cxx
MINI_PROG_SOURCES += vnl_complex_svd.cxx
MINI_PROG_SOURCES += vnl_planefit.cxx
MINI_PROG_SOURCES += vnl_polyroots.cxx
MINI_PROG_SOURCES += vnl_rosenbrock.cxx

################################
include ${IUEROOT}/config/top.mk
################################
