# main package for processing operations

ifdef HAS_EXPAT

# Basic process classes
SUBDIRS += bprb

# Python wrappers
SUBDIRS += bppy

# Brown core processing
SUBDIRS += core

# Brown bvgl processes
SUBDIRS += bvgl_pro

# Brown batch processing (Python)
SUBDIRS += bpro_batch

endif
