USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_opt_pro

SOURCES += boxm_opt_register.cxx
MANPAGE_SOURCES += boxm_opt_processes.h
SOURCES += processes/boxm_opt_bayesian_update_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
