USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_opt_pro

SOURCES += boxm_opt_register.cxx
MANPAGE_SOURCES += boxm_opt_processes.h

SOURCES += processes/boxm_opt_bayesian_update_process.cxx
SOURCES += processes/boxm_render_expected_depth_rt_process.cxx
SOURCES += processes/boxm_update_rt_process.cxx
SOURCES += processes/boxm_render_expected_rt_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
