USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2-view

SOURCES += boxm2_render_tableau.cxx
SOURCES += boxm2_cam_tableau.cxx
MANPAGE_SOURCES += boxm2_include_glew.h
SOURCES += boxm2_change_detection_tableau.cxx
SOURCES += boxm2_trajectory.cxx

################################
include ${VXLROOT}/config/top.mk
################################
