USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2-view

SOURCES += boxm2_render_tableau.cxx
SOURCES += boxm2_cam_tableau.cxx
MANPAGE_SOURCES += boxm2_include_glew.h
SOURCES += boxm2_change_detection_tableau.cxx
SOURCES += boxm2_trajectory.cxx
SOURCES += boxm2_batch_update_tableau.cxx
SOURCES += boxm2_render_rgb_tableau.cxx
SOURCES += boxm2_view_utils.cxx
SOURCES += boxm2_ocl_render_tableau.cxx

SUBDIRS += pro

################################
include ${VXLROOT}/config/top.mk
################################
