USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_class_write_samples.cxx

################################
include ${VXLROOT}/config/top.mk
################################
