USES += core
include ../../config.mk
VGUI_USE_WX := 1

PROGRAM := wx_childview
SOURCES += wx_childview_app.cxx
SOURCES += wx_childview_frame.cxx

PROGRAM := wx_docview
SOURCES += wx_docview_app.cxx
SOURCES += wx_docview_frame.cxx
SOURCES += wx_docview_doc.cxx
SOURCES += wx_docview_view.cxx

PROGRAM := wx_xrc
SOURCES += wx_xrc_app.cxx
SOURCES += wx_xrc_frame.cxx

################################
include ${VXLROOT}/config/top.mk
################################
