USES += contrib/brl contrib/brl/bbas core

LIBRARY := vidl2_gui
VERSION := 1.0

SOURCES += vidl2_gui_param_dialog.cxx
SOURCES += vidl2_capture_tableau.cxx
MANPAGE_SOURCES += vidl2_capture_tableau_sptr.h

################################
include ${VXLROOT}/config/top.mk
################################
