USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_tracking_face_2d.cxx
PARAMS_test_tracking_face_2d := image0005_left.bmp image0005_right.bmp

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
