USES += vxl
include ${IUEROOT}/vxl/vul/config.mk
IULIBS := -lvul -lvul-io -lvsl

TESTS += vul_io_test_all.cxx

TESTS += test_user_info_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
#########################################
