USES += vxl oxl
include ${IUEROOT}/oxl/mvl/config.mk

TESTS += oxltest.cpp
ifdef WIN32
SOURCES += StdAfx.cpp
endif

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
