USES += vxl oxl
include ${IUEROOT}/vxl/vnl/algo/config.mk

TESTS += oxltest.cpp

IULIBS += -lmvl -lvgl -lvnl-algo -lvnl -lvbl -lvul

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
