USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += example_basic.cxx
MINI_PROG_SOURCES += example_basic_animate.cxx
MINI_PROG_SOURCES += example_basic_trackball.cxx
MINI_PROG_SOURCES += example_examiner_27balls.cxx
MINI_PROG_SOURCES += example_examiner_animate.cxx
MINI_PROG_SOURCES += example_examiner_cylinders.cxx
MINI_PROG_SOURCES += example_examiner_file.cxx
MINI_PROG_SOURCES += example_examiner_helix.cxx
MINI_PROG_SOURCES += example_grid_examiner.cxx
MINI_PROG_SOURCES += example_grid_multiscene.cxx
MINI_PROG_SOURCES += example_interact.cxx
MINI_PROG_SOURCES += example_point_set.cxx
MINI_PROG_SOURCES += example_project2d.cxx

################################
include ${VXLROOT}/config/top.mk
################################
