#
# VRML IO library
#
# Modifications:
# 
# 031197 AWF Initial version

VXL := 1

LIBRARY := vrml
VERSION := 1.0

SOURCES += vrml_out.cxx

##########################################
include ${IUEROOT}/config/top.mk
##########################################
