USES += contrib/gel contrib/oxl core
include ${IUEROOT}/contrib/oxl/mvl/config.mk
include ${IUEROOT}/core/vil/config.mk

PROGRAM = octree

SOURCES += main.cxx
SOURCES += VoxmapPoints.cxx
SOURCES += VoxmapImagePoints.cxx
SOURCES += Voxel.cxx
SOURCES += OctreeLevel.cxx
SOURCES += Cube.cxx
SOURCES += ConvexHull.cxx
SOURCES += BaseCube.cxx

################################
include ${IUEROOT}/config/top.mk
################################
