USES += contrib/gel contrib/oxl core
include ${VXLROOT}/contrib/oxl/mvl/config.mk
include ${VXLROOT}/core/vil1/config.mk

PROGRAM = octree

SOURCES += main.cxx
SOURCES += VoxmapPoints.cxx
SOURCES += VoxmapImagePoints.cxx
SOURCES += Voxel.cxx
SOURCES += OctreeLevel.cxx
SOURCES += ConvexHull.cxx
MANPAGE_SOURCES += BaseCube.h
MANPAGE_SOURCES += Cube.h

################################
include ${VXLROOT}/config/top.mk
################################
