USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += basic01_pick_tableau.cxx

################################
include ${VXLROOT}/config/top.mk
################################

