include ${VXLROOT}/contrib/brl/bseg/bvxm/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/algo/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/io/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/pro/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/core/vil_pro/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/config.mk
include ${VXLROOT}/contrib/brl/bpro/bprb/config.mk
include ${VXLROOT}/contrib/brl/bbas/brdb/config.mk
include ${VXLROOT}/core/vil_io/config.mk
include ${VXLROOT}/core/vil/config.mk
include ${VXLROOT}/core/vbl/config.mk
