USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvxm_grid_pro

SOURCES += bvxm_grid_register.cxx
MANPAGE_SOURCES += bvxm_grid_processes.h
SOURCES += processes/bvxm_save_grid_raw_process.cxx
SOURCES += processes/bvxm_crop_grid_process.cxx
SOURCES += processes/bvxm_multiply_grids_process.cxx
SOURCES += processes/bvxm_threshold_grid_process.cxx
SOURCES += processes/bvxm_load_grid_process.cxx
SOURCES += processes/bvxm_grid_to_image_stack_process.cxx
SOURCES += processes/bvxm_combine_grids_process.cxx
SOURCES += processes/bvxm_fill_mesh_grid_process.cxx
SOURCES += processes/bvxm_expectation_opinion_grid_process.cxx
SOURCES += processes/bvxm_grid_distance_trasform_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
