USES += vxl
USES += mul
IULIBS := -lvbl -lvsl -lvbl-io

TESTS += test_vbl_io.cxx
# TESTS += golden_test_vbl_io.cxx
# TESTS += test_smart_ptr_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
