USES += vxl
include ${IUEROOT}/vxl/vbl/io/config.mk
include ${IUEROOT}/vxl/testlib/config.mk

TESTS += vbl_io_test_all.cxx

TESTS += test_vbl_io.cxx # includes test_smart_ptr_io.cxx test_bounding_box_io.cxx test_array_1d_io.cxx test_array_2d_io.cxx test_array_3d_io.cxx test_sparse_array_io.cxx golden_test_vbl_io.cxx
#TESTS += vbl_io_test_classes.cxx
MANPAGE_SOURCES += vbl_io_test_classes.h

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
