USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += volm_dummy_matcher.cxx

################################
include ${VXLROOT}/config/top.mk
################################
