USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += volm_dummy_matcher.cxx
MINI_PROG_SOURCES += volm_generate_hypos.cxx
MINI_PROG_SOURCES += volm_evaluate_output_tiles.cxx
MINI_PROG_SOURCES += volm_query_creation.cxx
MINI_PROG_SOURCES += volm_construct_camera_space.cxx

################################
include ${VXLROOT}/config/top.mk
################################
