USES += core
USE_OPENGL:=1
USE_WX:=1
IMMEDIATE_LIBS += -lvgui

LIBRARY := vgui_wx
VERSION := 1.0

SOURCES += vgui_wx.cxx

# wxWidgets
SOURCES += wxSliderPanel.cxx
SOURCES += wxVideoControl.cxx

# XML Resource Handlers
SOURCES += vgui_wx_adaptorXmlHandler.cxx
SOURCES += wxSliderPanelXmlHandler.cxx
SOURCES += wxVideoControlXmlHandler.cxx

################################
include ${VXLROOT}/config/top.mk
################################
