USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_render_expected_exe.cxx
MINI_PROG_SOURCES += boxm2_convert_bit_scene.cxx
MINI_PROG_SOURCES += boxm2_render_view.cxx
MINI_PROG_SOURCES += boxm2_rep_scene.cxx
MINI_PROG_SOURCES += boxm2_update_exe.cxx

################################
include ${VXLROOT}/config/top.mk
################################
