USES += contrib/brl contrib/brl/bbas core

TESTMAIN := test_driver.cxx
TESTS += test_kml_parser.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
