# segmentation feature detection library
SUBDIRS += sdet

# segmentation view library
SUBDIRS += segv

# segmentation test executables
SUBDIRS += sbin

################################
include ${IUEROOT}/config/top.mk
################################
