USES += contrib/prip core
include ../config.mk

TESTS += vmap_test.cxx
MANPAGE_SOURCES += my_map.h
MANPAGE_SOURCES += my_map_functions.txx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
