USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_face_algs.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
