USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm

SOURCES += dummy.cxx

MANPAGE_SOURCES += boxm_vis_implicit_sample.h

MANPAGE_SOURCES += boxm_plane_obs.txx
MANPAGE_SOURCES += boxm_rt_sample.txx
MANPAGE_SOURCES += boxm_sample_multi_bin.txx
MANPAGE_SOURCES += boxm_opt3_sample.txx
MANPAGE_SOURCES += boxm_opt2_sample.txx
MANPAGE_SOURCES += boxm_sample.txx
MANPAGE_SOURCES += boxm_edge_tangent_sample.txx
MANPAGE_SOURCES += boxm_edge_sample.txx
MANPAGE_SOURCES += boxm_scalar_sample.txx
MANPAGE_SOURCES += boxm_inf_line_sample.txx
MANPAGE_SOURCES += boxm_update_sample.h

SUBDIRS += algo

################################
include ${VXLROOT}/config/top.mk
################################
