USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bvxm-algo-pro

SOURCES += bvxm_algo_register.cxx
MANPAGE_SOURCES += bvxm_algo_processes.h

SOURCES += processes/bvxm_mog_to_mpm_process.cxx
SOURCES += processes/boxm_scene_to_bvxm_grid_process.cxx
SOURCES += processes/bvxm_mog_l2_process.cxx
SOURCES += processes/bvxm_merge_mog_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
