#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

SUBDIRS += mul tbl rpl oxl gel oul brl cul
ifndef NOTEST
 SUBDIRS += gel/vifa/tests
endif
SUBDIRS += gel/vsrl prip conversions


######################################
include ${VXLROOT}/config/top-rules.mk
######################################
