#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

SUBDIRS += mul tbl rpl oxl gel oul brl
ifndef NOTEST
 SUBDIRS += gel/vifa/tests
endif
SUBDIRS += gel/vsrl prip conversions

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
