VXL := 1
USES = vxl

TESTS += vbl_test_arg.cxx
TESTS += vbl_test_sparse_array_2d.cxx
TESTS += vbl_test_sprintf.cxx
TESTS += vbl_test_smart_ptr.cxx
#TESTS += vbl_test_basic_relation.cxx   FIXME

IULIBS := -lvbl -lvcl

##########################################
include ${IUEROOT}/config/static-tests.mk
##########################################
