USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_ocl_reg_mutual_info_exe.cxx
MINI_PROG_SOURCES += boxm2_ocl_depth_map_to_vol_exe.cxx

################################
include ${VXLROOT}/config/top.mk
################################
