USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_pro
VERSION := 1.0

SOURCES += boxm_register.cxx

MANPAGE_SOURCES += boxm_processes.h

################################
include ${VXLROOT}/config/top.mk
################################
