USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_pro
VERSION := 1.0

SOURCES += boxm_register.cxx

MANPAGE_SOURCES += boxm_processes.h
SOURCES += processes/boxm_render_expected_process.cxx
SOURCES += processes/boxm_load_scene_process.cxx
SOURCES += processes/boxm_save_occupancy_raw_process.cxx
SOURCES += processes/boxm_create_scene_process.cxx
SOURCES += processes/boxm_update_process.cxx
SOURCES += processes/boxm_refine_scene_process.cxx
SOURCES += processes/boxm_volume_visibility_process.cxx
SOURCES += processes/boxm_roi_init_process.cxx
SOURCES += processes/boxm_proj_local_cam_process.cxx
SOURCES += processes/boxm_upload_mesh_process.cxx
SOURCES += processes/boxm_replace_const_app_process.cxx
SOURCES += processes/boxm_construct_scene_from_image_process.cxx
SOURCES += processes/boxm_describe_scene_process.cxx
SOURCES += processes/boxm_camera_viewing_scene_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
