USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_pro
VERSION := 1.0

SOURCES += boxm_register.cxx

MANPAGE_SOURCES += boxm_processes.h
SOURCES += processes/boxm_load_scene_process.cxx
SOURCES += processes/boxm_create_scene_process.cxx
SOURCES += processes/boxm_proj_local_cam_process.cxx
SOURCES += processes/boxm_upload_mesh_process.cxx
SOURCES += processes/boxm_construct_scene_from_image_process.cxx
SOURCES += processes/boxm_camera_viewing_scene_process.cxx
SOURCES += processes/boxm_clean_scene_process.cxx
SOURCES += processes/boxm_force_write_blocks_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
