USES += core
include ../config.mk

MINI_PROG_SOURCES += vul_sequence_filename_example.cxx
MINI_PROG_SOURCES += vul_psfile_example.cxx
MINI_PROG_SOURCES += expand_path.cxx

################################
include ${VXLROOT}/config/top.mk
################################
