USES := vxl

IMMEDIATE_LIBS := -lvul
IULIBS := -lvul

MINI_PROG_SOURCES += vul_sequence_filename_example.cxx
MINI_PROG_SOURCES += expand_path.cxx

################################
include ${IUEROOT}/config/top.mk
################################
