USES += contrib/mul core
include ${VXLROOT}/contrib/mul/vimt3d/config.mk
include ${VXLROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += concat_3d_images.cxx
MINI_PROG_SOURCES += print_mbl_log_properties.cxx
MINI_PROG_SOURCES += crop_image_3d.cxx
MINI_PROG_SOURCES += print_image.cxx

################################
include ${VXLROOT}/config/top.mk
################################
