USES += contrib/mul core
include ${VXLROOT}/contrib/mul/vimt3d/config.mk
include ${VXLROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += concat_3d_images.cxx

################################
include ${VXLROOT}/config/top.mk
################################
