USES += contrib/mul core
include ${VXLROOT}/contrib/mul/vimt3d/config.mk
include ${VXLROOT}/contrib/mul/vil3d/config.mk
include ${VXLROOT}/contrib/mul/mbl/config.mk
include ${VXLROOT}/core/vul/config.mk
include ${VXLROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += concat_3d_images.cxx
MINI_PROG_SOURCES += print_mbl_log_properties.cxx
MINI_PROG_SOURCES += crop_image_3d.cxx
MINI_PROG_SOURCES += print_image.cxx
MINI_PROG_SOURCES += image3d_math.cxx
MINI_PROG_SOURCES += index_sort.cxx
MINI_PROG_SOURCES += multiplane_image.cxx
MINI_PROG_SOURCES += tile_images_2d.cxx
MINI_PROG_SOURCES += image3d_split.cxx

################################
include ${VXLROOT}/config/top.mk
################################
