USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vidl2_pro
VERSION := 1.0

SOURCES += vidl2_io_istream.cxx
SOURCES += vidl2_io_ostream.cxx
SOURCES += vidl2_open_istream_process.cxx
SOURCES += vidl2_open_ostream_process.cxx
SOURCES += vidl2_pro_utils.cxx

################################
include ${VXLROOT}/config/top.mk
################################
