USES += core
include ../algo/config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS += test_cartesian.cxx
TESTS += test_distance.cxx
TESTS += test_polygon.cxx
TESTS += test_polygon_scan_iterator.cxx
TESTS += test_triangle_scan_iterator.cxx
TESTS += test_ellipse_scan_iterator.cxx
TESTS += test_window_scan_iterator.cxx
TESTS += test_area.cxx
TESTS += test_clip.cxx
TESTS += test_closest_point.cxx
TESTS += test_convex.cxx
TESTS += test_line_3d_2_points.cxx
TESTS += test_sphere.cxx
TESTS += test_line_segment_3d.cxx
TESTS += test_triangle_3d.cxx
TESTS += test_triangle_3d_line_intersection.cxx
TESTS += test_infinite_line_3d.cxx
TESTS += test_ray_3d.cxx

MINI_PROG_SOURCES += test_include.cxx
MINI_PROG_SOURCES += test_template_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
