USES += core
include ../algo/config.mk
include ${IUEROOT}/core/vnl/algo/config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS += test_homg.cxx
TESTS += test_cartesian.cxx
TESTS += test_conic.cxx
TESTS += test_fit_conics_2d.cxx
TESTS += test_distance.cxx
TESTS += test_polygon.cxx
TESTS += test_polygon_scan_iterator.cxx
TESTS += test_triangle_scan_iterator.cxx
TESTS += test_ellipse_scan_iterator.cxx
TESTS += test_window_scan_iterator.cxx
TESTS += test_area.cxx
TESTS += test_clip.cxx
TESTS += test_h_matrix_1d.cxx
TESTS += test_h_matrix_2d.cxx
TESTS += test_h_matrix_3d.cxx
TESTS += test_fit_lines_2d.cxx
TESTS += test_closest_point.cxx
TESTS += test_p_matrix.cxx
TESTS += test_convex.cxx
TESTS += test_convex_hull_2d.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
