#include <vgl/vgl_fwd.h>
#include <vgl/algo/vgl_algo_fwd.h>

#include <vgl/vgl_1d_basis.h>
#include <vgl/vgl_area.h>
#include <vgl/vgl_box_2d.h>
#include <vgl/vgl_box_3d.h>
#include <vgl/vgl_clip.h>
#include <vgl/vgl_closest_point.h>
#include <vgl/vgl_conic.h>
#include <vgl/vgl_convex.h>
#include <vgl/vgl_distance.h>
#include <vgl/vgl_ellipse_scan_iterator.h>
#include <vgl/vgl_homg.h>
#include <vgl/vgl_homg_line_2d.h>
#include <vgl/vgl_homg_line_3d_2_points.h>
#include <vgl/vgl_homg_plane_3d.h>
#include <vgl/vgl_homg_point_1d.h>
#include <vgl/vgl_homg_point_2d.h>
#include <vgl/vgl_homg_point_3d.h>
#include <vgl/vgl_line_2d.h>
#include <vgl/vgl_line_3d_2_points.h>
#include <vgl/vgl_line_segment_2d.h>
#include <vgl/vgl_line_segment_3d.h>
#include <vgl/vgl_lineseg_test.h>
#include <vgl/vgl_plane_3d.h>
#include <vgl/vgl_point_2d.h>
#include <vgl/vgl_point_3d.h>
#include <vgl/vgl_polygon.h>
#include <vgl/vgl_polygon_scan_iterator.h>
#include <vgl/vgl_polygon_test.h>
#include <vgl/vgl_region_scan_iterator.h>
#include <vgl/vgl_triangle_scan_iterator.h>
#include <vgl/vgl_triangle_test.h>
#include <vgl/vgl_vector_2d.h>
#include <vgl/vgl_vector_3d.h>
#include <vgl/vgl_window_scan_iterator.h>
#include <vgl/algo/vgl_convex_hull_2d.h>
#include <vgl/algo/vgl_fit_lines_2d.h>
#include <vgl/algo/vgl_homg_operators_1d.h>
#include <vgl/algo/vgl_homg_operators_2d.h>
#include <vgl/algo/vgl_homg_operators_3d.h>
#include <vgl/algo/vgl_h_matrix_1d.h>
#include <vgl/algo/vgl_h_matrix_1d_compute.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_3point.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_linear.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_optimize.h>
#include <vgl/algo/vgl_h_matrix_2d.h>
#include <vgl/algo/vgl_h_matrix_2d_compute.h>
#include <vgl/algo/vgl_h_matrix_2d_compute_4point.h>
#include <vgl/algo/vgl_h_matrix_2d_compute_linear.h>
#include <vgl/algo/vgl_h_matrix_2d_optimize.h>
#include <vgl/algo/vgl_h_matrix_2d_optimize_lmq.h>
#include <vgl/algo/vgl_h_matrix_3d.h>
#include <vgl/algo/vgl_line_2d_regression.h>
#include <vgl/algo/vgl_norm_trans_2d.h>
#include <vgl/algo/vgl_norm_trans_3d.h>
#include <vgl/algo/vgl_p_matrix.h>
#include <vgl/algo/vgl_rtree.h>

int main() { return 0; }
