#include <vgl/vgl_1d_basis.hxx>
#include <vgl/vgl_area.hxx>
#include <vgl/vgl_box_2d.hxx>
#include <vgl/vgl_box_3d.hxx>
#include <vgl/vgl_clip.hxx>
#include <vgl/vgl_closest_point.hxx>
#include <vgl/vgl_conic_segment_2d.hxx>
#include <vgl/vgl_conic.hxx>
#include <vgl/vgl_convex.hxx>
#include <vgl/vgl_cylinder.hxx>
#include <vgl/vgl_distance.hxx>
#include <vgl/vgl_ellipse_scan_iterator.hxx>
#include <vgl/vgl_homg_line_2d.hxx>
#include <vgl/vgl_homg_line_3d_2_points.hxx>
#include <vgl/vgl_homg_plane_3d.hxx>
#include <vgl/vgl_homg_point_1d.hxx>
#include <vgl/vgl_homg_point_2d.hxx>
#include <vgl/vgl_homg_point_3d.hxx>
#include <vgl/vgl_infinite_line_3d.hxx>
#include <vgl/vgl_intersection.hxx>
#include <vgl/vgl_line_2d.hxx>
#include <vgl/vgl_line_3d_2_points.hxx>
#include <vgl/vgl_line_segment_2d.hxx>
#include <vgl/vgl_line_segment_3d.hxx>
#include <vgl/vgl_lineseg_test.hxx>
#include <vgl/vgl_plane_3d.hxx>
#include <vgl/vgl_point_2d.hxx>
#include <vgl/vgl_point_3d.hxx>
#include <vgl/vgl_polygon_scan_iterator.hxx>
#include <vgl/vgl_polygon_test.hxx>
#include <vgl/vgl_polygon.hxx>
#include <vgl/vgl_ray_3d.hxx>
#include <vgl/vgl_sphere_3d.hxx>
#include <vgl/vgl_tolerance.hxx>
#include <vgl/vgl_triangle_scan_iterator.hxx>
#include <vgl/vgl_triangle_test.hxx>
#include <vgl/vgl_vector_2d.hxx>
#include <vgl/vgl_vector_3d.hxx>
#include <vgl/vgl_window_scan_iterator.hxx>

int main() { return 0; }
