#include <vgl/vgl_1d_basis.txx>
#include <vgl/vgl_area.txx>
#include <vgl/vgl_box_2d.txx>
#include <vgl/vgl_box_3d.txx>
#include <vgl/vgl_clip.txx>
#include <vgl/vgl_closest_point.txx>
#include <vgl/vgl_conic_segment_2d.txx>
#include <vgl/vgl_conic.txx>
#include <vgl/vgl_convex.txx>
#include <vgl/vgl_cylinder.txx>
#include <vgl/vgl_distance.txx>
#include <vgl/vgl_ellipse_scan_iterator.txx>
#include <vgl/vgl_homg_line_2d.txx>
#include <vgl/vgl_homg_line_3d_2_points.txx>
#include <vgl/vgl_homg_plane_3d.txx>
#include <vgl/vgl_homg_point_1d.txx>
#include <vgl/vgl_homg_point_2d.txx>
#include <vgl/vgl_homg_point_3d.txx>
#include <vgl/vgl_infinite_line_3d.txx>
#include <vgl/vgl_intersection.txx>
#include <vgl/vgl_line_2d.txx>
#include <vgl/vgl_line_3d_2_points.txx>
#include <vgl/vgl_line_segment_2d.txx>
#include <vgl/vgl_line_segment_3d.txx>
#include <vgl/vgl_lineseg_test.txx>
#include <vgl/vgl_plane_3d.txx>
#include <vgl/vgl_point_2d.txx>
#include <vgl/vgl_point_3d.txx>
#include <vgl/vgl_polygon_scan_iterator.txx>
#include <vgl/vgl_polygon_test.txx>
#include <vgl/vgl_polygon.txx>
#include <vgl/vgl_ray_3d.txx>
#include <vgl/vgl_sphere_3d.txx>
#include <vgl/vgl_tolerance.txx>
#include <vgl/vgl_triangle_scan_iterator.txx>
#include <vgl/vgl_triangle_test.txx>
#include <vgl/vgl_vector_2d.txx>
#include <vgl/vgl_vector_3d.txx>
#include <vgl/vgl_window_scan_iterator.txx>

int main() { return 0; }
