USES += contrib/brl contrib/brl/bbas

LIBRARY := bocl

MANPAGE_SOURCES += bocl_cl.h
MANPAGE_SOURCES += bocl_manager.h
MANPAGE_SOURCES += bocl_manager.txx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

#ifndef NOTEST
# SUBDIRS += tests
#endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
