#include <vpgl/algo/vpgl_adjust_rational_trans_onept.h>
#include <vpgl/algo/vpgl_ba_fixed_k_lsqr.h>
#include <vpgl/algo/vpgl_ba_shared_k_lsqr.h>
#include <vpgl/algo/vpgl_backproject.h>
#include <vpgl/algo/vpgl_bundle_adjust.h>
#include <vpgl/algo/vpgl_bundle_adjust_lsqr.h>
#include <vpgl/algo/vpgl_bundle_rolling_shutter_adjust.h>
#include <vpgl/algo/vpgl_camera_bounds.h>
#include <vpgl/algo/vpgl_camera_compute.h>
#include <vpgl/algo/vpgl_camera_from_box.h>
#include <vpgl/algo/vpgl_camera_homographies.h>
#include <vpgl/algo/vpgl_construct_cameras.h>
#include <vpgl/algo/vpgl_em_compute_5_point.h>
#include <vpgl/algo/vpgl_fm_compute_2_point.h>
#include <vpgl/algo/vpgl_fm_compute_7_point.h>
#include <vpgl/algo/vpgl_fm_compute_8_point.h>
#include <vpgl/algo/vpgl_fm_compute_affine_ransac.h>
#include <vpgl/algo/vpgl_fm_compute_ransac.h>
#include <vpgl/algo/vpgl_fm_compute_reg_ransac.h>
#include <vpgl/algo/vpgl_interpolate.h>
#include <vpgl/algo/vpgl_invmap_cost_function.h>
#include <vpgl/algo/vpgl_lens_warp_mapper.h>
#include <vpgl/algo/vpgl_list.h>
#include <vpgl/algo/vpgl_nitf_camera_coverage.h>
#include <vpgl/algo/vpgl_optimize_camera.h>
#include <vpgl/algo/vpgl_ortho_procrustes.h>
#include <vpgl/algo/vpgl_project.h>
#include <vpgl/algo/vpgl_rational_geo_adjust.h>
#include <vpgl/algo/vpgl_ray.h>
#include <vpgl/algo/vpgl_ray_intersect.h>
#include <vpgl/algo/vpgl_vsol_lens_warp.h>

int main() { return 0; }
