# This is the tbl package, containing the image processing library
# as designed by Terry Boult, but converted to be used with vxl,
# and also the "easy" image processing functions for vil, using those.

# image processing
SUBDIRS += vipl vepl vepl2

################################
include ${IUEROOT}/config/top.mk
################################
