# This is the tbl package, containing the image processing library
# as designed by Terry Boult, but converted to be used with vxl.

# image processing
SUBDIRS += vipl vepl

################################
include ${IUEROOT}/config/top.mk
################################
