###############################################################################
# File name: makefile
# Description: Project file for vsol examples
# -----------------------------------------------------------------------------
# Version |Date      | Author                   |Comment
# --------+----------+--------------------------+------------------------------
# 1.0     |2000/05/10| Peter TU                 |Creation
###############################################################################

USES := vxl gel

IULIBS += -lvsol -lvgl -lvnl -lvbl -lvul

MINI_PROG_SOURCES += vsol_spatial_object_example.cxx
MINI_PROG_SOURCES += vsol_point_example.cxx

###############################################################################
include ${IUEROOT}/config/top.mk
###############################################################################
