USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_reg_mutual_info_exe.cxx
MINI_PROG_SOURCES += boxm2_compute_path_uncertainty_exe.cxx

################################
include ${VXLROOT}/config/top.mk
################################
