USES := vxl mul

LIBRARY := vil2-io
VERSION := 1.0

SOURCES += vil2_io_memory_chunk.cxx
MANPAGE_SOURCES += vil2_io_smart_ptr.txx

################################
include ${IUEROOT}/config/top.mk
################################
