USES += core

LIBRARY := vidl_gui
VERSION := 1.0

SOURCES += vidl_gui_param_dialog.cxx
SOURCES += vidl_capture_tableau.cxx
MANPAGE_SOURCES += vidl_capture_tableau_sptr.h

################################
include ${VXLROOT}/config/top.mk
################################
