USES += vxl oxl
USE_MFC := 1

LIBRARY := vgui-mfc

SOURCES += vgui_mfc.cxx
SOURCES += vgui_mfc_adaptor.cxx
SOURCES += vgui_mfc_app.cxx
SOURCES += vgui_mfc_app_init.cxx
SOURCES += vgui_mfc_dialog_impl.cxx
SOURCES += vgui_mfc_doc.cxx
SOURCES += vgui_mfc_mainfrm.cxx
SOURCES += vgui_mfc_statusbar.cxx
SOURCES += vgui_mfc_tag.cxx
SOURCES += vgui_mfc_util.cxx
SOURCES += vgui_mfc_utils.cxx
SOURCES += vgui_mfc_view.cxx
SOURCES += vgui_mfc_window.cxx

################################
include ${IUEROOT}/config/top.mk
################################
