USES += v3p vxl gel 
include $(IUEROOT)/vxl/vnl/algo/config.mk
include ${IUEROOT}/vxl/vil/config.mk

IULIBS = -lgmvl -lvtol -lvdgl -lvsol -lvil -lvgl-algo -lvgl -lvnl-algo -lvnl -lvul -lvbl -lvpl -lvnl

MINI_PROG_SOURCES += gmvl_test.cxx

################################
include ${IUEROOT}/config/top.mk
################################

