#
# crossge@crd.ge.com
#

USES += v3p vxl gel 
#ald_libs += gmvl gbl vil vbl
# the following 5 are needed in conjunction with libvil:
USE_JPEG := 1
USE_TIFF := 1
USE_PNG  := 1
USE_NETLIB := 1
USE_SOCKETS := 1

IULIBS = -lvil -lvbl -lvpl -lgmvl -lgbl -lvnl

MINI_PROG_SOURCES += gmvl_test.cxx

################################
include ${IUEROOT}/config/top.mk
################################

