USES += v3p vxl gel 
include ${IUEROOT}/vxl/vil/config.mk

IULIBS = -lgmvl -lvtol -lvsol -lgbl -lvil -lvgl -lvul -lvbl -lvpl -lvnl

MINI_PROG_SOURCES += gmvl_test.cxx

################################
include ${IUEROOT}/config/top.mk
################################

