USES += contrib/mul core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_dp_solver.cxx
TESTS += test_lbp_solver.cxx
TESTS += test_graph_rep1.cxx
TESTS += test_order_cost.cxx
TESTS += test_csp_solver.cxx
TESTS += test_diffusion_solver.cxx
TESTS += test_make_tri_tree.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
