USES := vxl mul
include ${IUEROOT}/mul/pdf1d/config.mk

MINI_PROG_SOURCES += compare_kernel_estimates.cxx
MINI_PROG_SOURCES += plot_pdf_estimate.cxx
MINI_PROG_SOURCES += select_n_mixtures.cxx
MINI_PROG_SOURCES += select_pdf.cxx
MINI_PROG_SOURCES += test_overlap_pdf.cxx

################################
include ${IUEROOT}/config/top.mk
################################
