USES := vxl mul
include ${IUEROOT}/vxl/vnl/algo/config.mk

IULIBS := -lpdf1d -lmbl -lvgl-io -lvgl -lvnl-io -lvnl-algo -lvnl -lvsl

MINI_PROG_SOURCES += compare_kernel_estimates.cxx
MINI_PROG_SOURCES += plot_pdf_estimate.cxx
MINI_PROG_SOURCES += select_n_mixtures.cxx
MINI_PROG_SOURCES += select_pdf.cxx
MINI_PROG_SOURCES += test_overlap_pdf.cxx

################################
include ${IUEROOT}/config/top.mk
################################
