SET( HAS_VGUI "NO" )
IF(BUILD_VGUI)

  INCLUDE(${MODULE_PATH}/NewCMake/FindOpenGL.cmake)
  IF (OPENGL_FOUND)
  IF (OPENGL_GLU_FOUND)

    INCLUDE_DIRECTORIES( ${OPENGL_INCLUDE_PATH} )
    SET( HAS_VGUI "YES" )
    ADD_DEFINITIONS( -DHAS_OPENGL)

  ENDIF (OPENGL_GLU_FOUND)
  ENDIF (OPENGL_FOUND)

ENDIF(BUILD_VGUI)
