USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/gel core

LIBRARY := segv
VERSION := 1.0

SOURCES += segv_segmentation_manager.cxx
SOURCES += segv_vtol2D_tableau.cxx
MANPAGE_SOURCES += segv_vtol2D_tableau_sptr.h
SOURCES += segv_vtol_soview2D.cxx
SOURCES += segv_menus.cxx

################################
include ${IUEROOT}/config/top.mk
################################
