SOURCES += bbgm_viewer.cxx
SOURCES += bbgm_image_of.cxx
MANPAGE_SOURCES += bbgm_apply.h
MANPAGE_SOURCES += bbgm_detect.h
MANPAGE_SOURCES += bbgm_image_sptr.h
MANPAGE_SOURCES += bbgm_planes_to_sample.h
MANPAGE_SOURCES += bbgm_update.h
MANPAGE_SOURCES += bbgm_image_of.txx
MANPAGE_SOURCES += bbgm_viewer_sptr.h

SUBDIRS += tests
