USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ../algo/config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_move_proj_plane.cxx
TESTS += test_delaunay.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
