USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_move_proj_plane.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
