USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := brip_pro
VERSION := 1.0

SOURCES += brip_extrema_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
