USES += contrib/brl contrib/brl/bbas core

LIBRARY := bvrml
VERSION := 1.0

SOURCES += bvrml_write.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
