SOURCES += bapl_register.cxx
MANPAGE_SOURCES += bapl_processes.h

SOURCES += processes/bapl_connectivity_processes.cxx
SOURCES += processes/bapl_extract_keypoints_process.cxx
SOURCES += processes/bapl_match_keypoints_process.cxx
