#include <rgtl/rgtl_sqt_space.hxx>
RGTL_SQT_SPACE_BASE_INSTANTIATE(2);
RGTL_SQT_SPACE_INSTANTIATE(2, 0);
RGTL_SQT_SPACE_INSTANTIATE(2, 1);
RGTL_SQT_SPACE_INSTANTIATE(2, 2);
RGTL_SQT_SPACE_INSTANTIATE(2, 3);
