#include <rgtl/rgtl_sqt_space.hxx>
RGTL_SQT_SPACE_BASE_INSTANTIATE(3);
RGTL_SQT_SPACE_INSTANTIATE(3, 0);
RGTL_SQT_SPACE_INSTANTIATE(3, 1);
RGTL_SQT_SPACE_INSTANTIATE(3, 2);
RGTL_SQT_SPACE_INSTANTIATE(3, 3);
RGTL_SQT_SPACE_INSTANTIATE(3, 4);
RGTL_SQT_SPACE_INSTANTIATE(3, 5);
