#include <rgtl/rgtl_sqt_cell_geometry.hxx>
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 0);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 1);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 2);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 3);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 4);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(3, 5);
