#include <rgtl/rgtl_sqt_cell_geometry.hxx>
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(2, 0);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(2, 1);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(2, 2);
RGTL_SQT_CELL_GEOMETRY_INSTANTIATE(2, 3);
