#include <rgtl/rgtl_sqt_objects.hxx>
RGTL_SQT_OBJECTS_INSTANTIATE(2);
RGTL_SQT_OBJECTS_FACE_INSTANTIATE(2, 0);
RGTL_SQT_OBJECTS_FACE_INSTANTIATE(2, 1);
RGTL_SQT_OBJECTS_FACE_INSTANTIATE(2, 2);
RGTL_SQT_OBJECTS_FACE_INSTANTIATE(2, 3);
