USES += contrib/prip core
include ../../config.mk
include ${VXLROOT}/core/vil/config.mk

PROGRAM := vpyr_example_simple_segmentation
SOURCES += simple_segmentation.cxx
SOURCES += simple_segmentation_builder.cxx

################################
include ${VXLROOT}/config/top.mk
################################
