USES += contrib/oxl core
include $(IUEROOT)/core/vgui/config.mk

#with_vrml += test_vrml.cxx
#with_vrml += test_deck.cxx
#with_vrml += test_composite.cxx
#with_vrml += test_clear.cxx
#with_vrml += test_blackbox.cxx
#with_vrml += test_twowin.cxx
#MINI_PROG_SOURCES := $(filter-out $(with_vrml),$(wildcard *.cxx))

MINI_PROG_SOURCES += test_2d.cxx
MINI_PROG_SOURCES += test_3d.cxx
MINI_PROG_SOURCES += test_active_visible.cxx
MINI_PROG_SOURCES += test_bitab.cxx
MINI_PROG_SOURCES += test_blackbox.cxx
MINI_PROG_SOURCES += test_blend.cxx
MINI_PROG_SOURCES += test_blend2.cxx
MINI_PROG_SOURCES += test_clear.cxx
MINI_PROG_SOURCES += test_composite.cxx
MINI_PROG_SOURCES += test_composite2d.cxx
MINI_PROG_SOURCES += test_coop.cxx
MINI_PROG_SOURCES += test_deck.cxx
MINI_PROG_SOURCES += test_deck2d.cxx
MINI_PROG_SOURCES += test_dialog.cxx
MINI_PROG_SOURCES += test_enhance.cxx
MINI_PROG_SOURCES += test_event_server.cxx
MINI_PROG_SOURCES += test_func.cxx
MINI_PROG_SOURCES += test_grid_tableau.cxx
MINI_PROG_SOURCES += test_image.cxx
MINI_PROG_SOURCES += test_listmanager2d.cxx
MINI_PROG_SOURCES += test_magnify.cxx
MINI_PROG_SOURCES += test_manipulator.cxx
MINI_PROG_SOURCES += test_menu.cxx
MINI_PROG_SOURCES += test_polytab.cxx
MINI_PROG_SOURCES += test_print_tableau.cxx
MINI_PROG_SOURCES += test_proj.cxx
MINI_PROG_SOURCES += test_rubber.cxx
MINI_PROG_SOURCES += test_smartptr.cxx
MINI_PROG_SOURCES += test_soview.cxx
MINI_PROG_SOURCES += test_spinner.cxx
MINI_PROG_SOURCES += test_texture.cxx
MINI_PROG_SOURCES += test_tritab.cxx
MINI_PROG_SOURCES += test_twowin.cxx
MINI_PROG_SOURCES += test_vrml.cxx

################################
include ${IUEROOT}/config/top.mk
################################
