USES += contrib/brl contrib/gel contrib/brl/bbas core
include ../config.mk

TESTS += bvgl_test_h_matrix_1d.cxx
TESTS += bvgl_test_h_matrix_2d.cxx
TESTS += bvgl_test_h_matrix_3d.cxx
TESTS += bvgl_test_h_matrix_2d_compute_linear.cxx
TESTS += bvgl_test_norm_trans_2d.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
