#ifndef boxm_ocl_processes_h_
#define boxm_ocl_processes_h_

#include <bprb/bprb_func_process.h>
#include <bprb/bprb_macros.h>

//the init functions
DECLARE_FUNC_CONS(boxm_ocl_refine_process);
DECLARE_FUNC_CONS(boxm_ocl_convert_boxm_to_ocl_process);
DECLARE_FUNC_CONS(boxm_ocl_init_render_probe_process);
DECLARE_FUNC_CONS(boxm_ocl_run_render_probe_process);
DECLARE_FUNC_CONS(boxm_ocl_finish_render_probe_process);
DECLARE_FUNC_CONS(boxm_ocl_init_change_detection_process);
DECLARE_FUNC_CONS(boxm_ocl_run_change_detection_process);
DECLARE_FUNC_CONS(boxm_ocl_finish_change_detection_process);
DECLARE_FUNC_CONS(boxm_init_update_bit_scene_process);
DECLARE_FUNC_CONS(boxm_update_bit_scene_process);
DECLARE_FUNC_CONS(boxm_finish_update_bit_scene_process);
DECLARE_FUNC_CONS(boxm_render_update_bit_scene_process);
DECLARE_FUNC_CONS(boxm_query_bit_scene_process);
DECLARE_FUNC_CONS(boxm_ray_probe_process);
DECLARE_FUNC_CONS(boxm_generate_3d_point_process);
DECLARE_FUNC_CONS(boxm_change_detection_bit_scene_process);
DECLARE_FUNC_CONS(boxm_init_bit_scene_process);
#endif
