USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm-ocl-pro

SOURCES += boxm_ocl_register.cxx
MANPAGE_SOURCES += boxm_ocl_processes.h

SOURCES += processes/boxm_ocl_refine_process.cxx
SOURCES += processes/boxm_ocl_convert_boxm_to_ocl_process.cxx
SOURCES += processes/boxm_ocl_run_render_probe_process.cxx
SOURCES += processes/boxm_ocl_finish_render_probe_process.cxx
SOURCES += processes/boxm_ocl_init_render_probe_process.cxx
SOURCES += processes/boxm_ocl_init_change_detection_process.cxx
SOURCES += processes/boxm_ocl_run_change_detection_process.cxx
SOURCES += processes/boxm_finish_update_bit_scene_process.cxx
SOURCES += processes/boxm_update_bit_scene_process.cxx
SOURCES += processes/boxm_render_update_bit_scene_process.cxx
SOURCES += processes/boxm_ocl_finish_change_detection_process.cxx
SOURCES += processes/boxm_init_update_bit_scene_process.cxx
SOURCES += processes/boxm_query_bit_scene_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
