USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm-ocl-pro

SOURCES += boxm_ocl_register.cxx
MANPAGE_SOURCES += boxm_ocl_processes.h

SOURCES += processes/boxm_ocl_render_expected_process.cxx
SOURCES += processes/boxm_ocl_stack_render_expected_process.cxx
SOURCES += processes/boxm_ocl_refine_process.cxx
SOURCES += processes/boxm_ocl_ray_bundle_expected_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
