USES += contrib/brl contrib/brl/bseg core

LIBRARY := bapl_io

SOURCES += bapl_io_dsift.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
