USES += contrib/mul core

LIBRARY := ipts
VERSION := 1.0

MANPAGE_SOURCES += ipts_scale_space_peaks.h

SUBDIRS += tools

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################

