USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

TESTMAIN := test_driver.cxx
TESTS += test_quad_interpolate.cxx
TESTS += test_boxm_plane_ransac.cxx
TESTS += test_boxm_rational_camera_utils.cxx
TESTS += test_sigma_normalizer.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
