USES += contrib/gel contrib/gel/mrc core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_lvcs.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
