USES += v3p vxl gel

LIBRARY = gtrl

# main class
SOURCES += gtrl_triangulation.cxx

# helpers
SOURCES += gtrl_triangle.cxx
SOURCES += gtrl_vertex.cxx
SOURCES += gtrl_polygon.cxx

ifndef NOTEST
SUBDIRS += examples
endif

################################
include ${IUEROOT}/config/top.mk
################################
