#
# crossge@crd.ge.com
#
##########################################
include $(IUEROOT)/vxl/vgui/easy-client.mk
##########################################

USES += v3p vxl gel

LIBRARY = makefile

SOURCES += gtrl_triangle.cxx
SOURCES += gtrl_vertex.cxx

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
