# minizip package to zip and unzip files

USES := # nothing
USE_STDC++ := 0

LIBRARY := minizip

SOURCES += iowin32.c
SOURCES += mztools.c
SOURCES += zip.c
SOURCES += ioapi.c
SOURCES += unzip.c
MANPAGE_SOURCES += crypt.h

################################
include ${VXLROOT}/config/top.mk
################################
