USES += contrib/gel core
USE_OPENGL:= 1
TRY_MPEG2 := 1

IMMEDIATE_LIBS := -lvidl -lvgui -lvil -lvul

LIBRARY := jvid
VERSION := 1.0

SOURCES += jvx_manager.cxx

SUBDIRS += bin

################################
include ${IUEROOT}/config/top.mk
################################
