USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_functors

SOURCES += bvpl_negative_gauss_conv_functor.cxx
SOURCES += bvpl_opinion_functor.cxx
SOURCES += bvpl_local_max_functor.cxx
SOURCES += bvpl_find_surface_functor.cxx
SOURCES += bvpl_gauss_convolution_functor.cxx
SOURCES += bvpl_algebraic_functor.cxx
SOURCES += bvpl_positive_gauss_conv_functor.cxx
MANPAGE_SOURCES += bvpl_edge_geometric_mean_functor.txx
MANPAGE_SOURCES += bvpl_edge2d_functor.txx
MANPAGE_SOURCES += bvpl_edge_algebraic_mean_functor.txx

################################
include ${VXLROOT}/config/top.mk
################################
