USES += contrib/gel core

LIBRARY := vpgl-file_formats
VERSION := 1.0

SOURCES += vpgl_nitf_rational_camera.cxx
SOURCES += vpgl_geo_camera.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
