USES += contrib/gel core

LIBRARY := vpgl-file_formats
VERSION := 1.0

SOURCES += vpgl_nitf_rational_camera.cxx

################################
include ${VXLROOT}/config/top.mk
################################
