USES += core
include ../config.mk
include ${VXLROOT}/core/vil/config.mk
include ${VXLROOT}/core/vul/config.mk
include ${VXLROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += vidl1_mpegcodec_example.cxx
MINI_PROG_SOURCES += vidl1_video2images.cxx

PROGRAM = vidl1_player
SOURCES += vidl1_player_main.cxx
SOURCES += vidl1_player_manager.cxx
SOURCES += vidl1_player_menus.cxx

################################
include ${VXLROOT}/config/top.mk
################################
