USES += vxl
include ${IUEROOT}/vxl/vil/io/config.mk
include ${IUEROOT}/vxl/vul/config.mk
include ${IUEROOT}/vxl/testlib/config.mk

TESTMAIN = test_driver.cxx

TESTS += test_include.cxx
TESTS += test_memory_image_format_io.cxx
TESTS += test_memory_image_impl_io.cxx
TESTS += test_memory_image_of_io.cxx
TESTS += test_rgb_io.cxx
TESTS += test_rgba_io.cxx
TESTS += golden_test_vil_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
