USES += vxl

TRY_TIFF := 1
TRY_JPEG := 1
TRY_PNG  := 1 
USE_SOCKETS := 1  
IULIBS := -lvil-io -lvil -lvsl 

TESTS += test_vil_io.cxx # includes test_memory_image_format_io.cxx test_rgb_io.cxx test_rgba_io.cxx test_memory_image_impl_io.cxx test_memory_image_of_io.cxx golden_test_vil_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
