USES += vxl
USES += mul

TRY_TIFF := 1
TRY_JPEG := 1
TRY_PNG  := 1 
USE_SOCKETS := 1  
IULIBS := -lvil-io -lvil -lvsl 

MINI_PROG_SOURCES += 

TESTS += test_vil_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
