#include <boxm2/boxm2_data.hxx>
#include <boxm2/boxm2_data_traits.h>

BOXM2_DATA_INSTANTIATE(BOXM2_NUM_OBS);
BOXM2_DATA_INSTANTIATE(BOXM2_NUM_OBS_SINGLE);
BOXM2_DATA_INSTANTIATE(BOXM2_NUM_OBS_SINGLE_INT);
