#include <boxm2/boxm2_data.hxx>
#include <boxm2/boxm2_data_traits.h>

BOXM2_DATA_INSTANTIATE(BOXM2_AUX);
BOXM2_DATA_INSTANTIATE(BOXM2_AUX0);
BOXM2_DATA_INSTANTIATE(BOXM2_AUX1);
BOXM2_DATA_INSTANTIATE(BOXM2_AUX2);
BOXM2_DATA_INSTANTIATE(BOXM2_AUX3);
BOXM2_DATA_INSTANTIATE(BOXM2_AUX4);
BOXM2_DATA_INSTANTIATE(BOXM2_EXPECTATION);
