USES := vxl rpl mul
include ${IUEROOT}/vxl/vnl/algo/config.mk

IULIBS += -lrrel -lvnl-algo -lvnl
IULIBS += -lmbl -lvbl -lvsl -lvnl-io -lvul

MINI_PROG_SOURCES += homography2d_fit.cxx
MINI_PROG_SOURCES += homography2d_gen.cxx
MINI_PROG_SOURCES += line_fit.cxx
MINI_PROG_SOURCES += line_gen.cxx

################################
include ${IUEROOT}/config/top.mk
################################
