USES += core
LIBRARY := vgl-xio
VERSION := 1.0
IMMEDIATE_LIBS := -lvgl-xio -lvgl

MANPAGE_SOURCES += vgl_xio_box_3d.txx
MANPAGE_SOURCES += vgl_xio_point_2d.txx
MANPAGE_SOURCES += vgl_xio_point_3d.txx
MANPAGE_SOURCES += vgl_xio_vector_3d.txx

################################
include ${VXLROOT}/config/top.mk
################################
