USES := vxl oxl
USE_GTKGLAREA := 1

MINI_PROG_SOURCES += test.cxx
MINI_PROG_SOURCES += movie.cxx

###########################################
include ${IUELOCALROOT}/oxl/vgui/config.mk
include ${IUEROOT}/config/top.mk
################################
