USES += contrib/oxl core
include ${IUEROOT}/core/vgui/config.mk
USE_GTKGLAREA := 1

MINI_PROG_SOURCES += test.cxx
MINI_PROG_SOURCES += movie.cxx

################################
include ${IUEROOT}/config/top.mk
################################
