USES += contrib/brl contrib/brl/bbas core

LIBRARY := bvnl
VERSION := 1.0

SOURCES += bvnl_parabolic_interpolator.cxx
SOURCES += bvnl_quadratic_interpolator.cxx

################################
include ${IUEROOT}/config/top.mk
################################
