# photogrammetry
SUBDIRS += vpgl

# CARMEN
SUBDIRS += carmen_interface

# tests
SUBDIRS += vpgl_tests

################################
include ${IUEROOT}/config/top.mk
################################

