# photogrammetry
SUBDIRS += vpgl

# CARMEN
SUBDIRS += carmen_interface

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

# tests
ifndef NOTEST
SUBDIRS += vpgl_tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################

