#   DESCRIPTION:
#
#   This is the vmal library.

USES += vxl oxl gel

LIBRARY := vmal
VERSION := 1

SOURCES += vmal_convert.cxx
SOURCES += vmal_dense_matching.cxx
SOURCES += vmal_homog2d.cxx
SOURCES += vmal_kl.cxx
SOURCES += vmal_kl_params.cxx
SOURCES += vmal_lines_correlation.cxx
SOURCES += vmal_multi_view_data.cxx
SOURCES += vmal_operators.cxx
SOURCES += vmal_rectifier.cxx
SOURCES += vmal_refine_lines.cxx
SOURCES += vmal_track_lines.cxx

################################
include ${IUEROOT}/config/top.mk
################################
