#   DESCRIPTION:
#
#   This is the vmal library.

USES += contrib/oxl contrib/gel core

LIBRARY := vmal
VERSION := 1

SOURCES += vmal_convert.cxx
SOURCES += vmal_dense_matching.cxx
SOURCES += vmal_homog2d.cxx
SOURCES += vmal_kl.cxx
SOURCES += vmal_kl_params.cxx
SOURCES += vmal_lines_correlation.cxx
SOURCES += vmal_multi_view_data.cxx
SOURCES += vmal_operators.cxx
SOURCES += vmal_rectifier.cxx
SOURCES += vmal_refine_lines.cxx
SOURCES += vmal_track_lines.cxx

MANPAGE_SOURCES += vmal_multi_view_data_edge_sptr.h
MANPAGE_SOURCES += vmal_multi_view_data_vertex_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
