USES = # nothing
USE_STDC++ := 0

LIBRARY := NCSUtil

MANPAGE_SOURCES += NCSPrefsXML.h
MANPAGE_SOURCES += CNCSBase64Coder.h
MANPAGE_SOURCES += NCSPrefsWin.h

################################
include ${VXLROOT}/config/top.mk
################################
