USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

MINI_PROG_SOURCES += boxm2_update_exe.cxx
MINI_PROG_SOURCES += boxm2_render_expected_exe.cxx
MINI_PROG_SOURCES += boxm2_render_view.cxx
MINI_PROG_SOURCES += boxm2_render_hemisphere.cxx
MINI_PROG_SOURCES += boxm2_change_detection_view.cxx
MINI_PROG_SOURCES += boxm2_export_scene.cxx
MINI_PROG_SOURCES += boxm2_update_rgb_exe.cxx
MINI_PROG_SOURCES += boxm2_refine_exe.cxx
MINI_PROG_SOURCES += boxm2_update_trajectory.cxx
MINI_PROG_SOURCES += boxm2_export_trajectory.cxx
MINI_PROG_SOURCES += boxm2_batch_update_view.cxx

################################
include ${VXLROOT}/config/top.mk
################################
