USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

MINI_PROG_SOURCES += boxm2_render_hemisphere.cxx
MINI_PROG_SOURCES += boxm2_export_scene.cxx
MINI_PROG_SOURCES += boxm2_ocl_render_view.cxx
MINI_PROG_SOURCES += boxm2_ocl_refine_scene.cxx

################################
include ${VXLROOT}/config/top.mk
################################
