USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := bvgl_pro
VERSION := 1.0

SOURCES += bvgl_register.cxx

MANPAGE_SOURCES += bvgl_processes.h
SOURCES += processes/bvgl_generate_mask_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
