USES += contrib/gel contrib/oxl core

LIBRARY := gkll

SOURCES += gkll_kl.cxx
SOURCES += gkll_kl_params.cxx
SOURCES += gkll_multi_view_data.cxx

MANPAGE_SOURCES += gkll_multi_view_data_vertex_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
