USES := vxl gel oxl

LIBRARY := gkll

SOURCES += gkll_kl.cxx
SOURCES += gkll_kl_params.cxx
SOURCES += gkll_multi_view_data.cxx

################################
include ${IUEROOT}/config/top.mk
################################
