USE_NETLIB := 1
NO_STDLIBS := 1

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifdef HAS_X11
USE_X11 := 1
MINI_PROG_SOURCES += showme.c
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
