USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := ocl_view
VERSION := 1.0

SOURCES += boxm_cam_tableau.cxx
SOURCES += boxm_ocl_draw_glbuffer_tableau.cxx
SOURCES += boxm_ocl_update_tableau.cxx
SOURCES += boxm_ocl_change_detection_tableau.cxx
SOURCES += boxm_ocl_rerender_tableau.cxx
SOURCES += boxm_ocl_render_bit_tableau.cxx
SOURCES += boxm_update_bit_tableau.cxx
MANPAGE_SOURCES += boxm_ocl_include_glew.h
SOURCES += boxm_vid_tableau.cxx

MANPAGE_SOURCES += boxm_cam_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_update_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_draw_glbuffer_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_change_detection_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_rerender_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_render_bit_tableau_sptr.h
MANPAGE_SOURCES += boxm_update_bit_tableau_sptr.h
MANPAGE_SOURCES += boxm_vid_tableau_sptr.h

################################
include ${VXLROOT}/config/top.mk
################################
