USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := ocl_view
VERSION := 1.0

SOURCES += boxm_cam_tableau.cxx
SOURCES += boxm_ocl_draw_glbuffer_tableau.cxx
SOURCES += boxm_ocl_update_tableau.cxx
MANPAGE_SOURCES += boxm_cam_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_update_tableau_sptr.h
MANPAGE_SOURCES += boxm_ocl_draw_glbuffer_tableau_sptr.h

################################
include ${VXLROOT}/config/top.mk
################################
