USES += core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN = test_driver.cxx

TESTS += test_algo_gauss_filter.cxx
TESTS += test_algo_gauss_reduce.cxx
TESTS += test_algo_convolve_1d.cxx
TESTS += test_algo_convolve_2d.cxx
TESTS += test_algo_correlate_1d.cxx
TESTS += test_algo_correlate_2d.cxx
TESTS += test_algo_exp_filter_1d.cxx
TESTS += test_binary_erode.cxx
TESTS += test_binary_dilate.cxx
TESTS += test_greyscale_dilate.cxx
TESTS += test_greyscale_erode.cxx
TESTS += test_median.cxx
TESTS += test_algo_exp_grad_filter_1d.cxx
TESTS += test_algo_line_filter.cxx
TESTS += test_algo_threshold.cxx
TESTS += test_algo_grid_merge.cxx
TESTS += test_algo_find_4con_boundary.cxx
TESTS += test_algo_fft.cxx
TESTS += test_suppress_non_max.cxx
TESTS += test_algo_histogram.cxx
TESTS += test_algo_histogram_equalise.cxx
TESTS += test_algo_distance_transform.cxx
TESTS += test_algo_trace_4con_boundary.cxx
TESTS += test_algo_blob_finder.cxx
TESTS += test_algo_trace_8con_boundary.cxx
TESTS += test_algo_find_peaks.cxx
TESTS += test_algo_region_finder.cxx
TESTS += test_algo_cartesian_differential_invariants.cxx
TESTS += test_algo_corners.cxx
TESTS += test_algo_sobel.cxx
TESTS += test_algo_abs_shuffle_distance.cxx
TESTS += test_algo_suppress_non_max_edges.cxx
TESTS += test_algo_checker_board.cxx

#MINI_PROG_SOURCES += vil_mil_gauss_general_timings.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
