#include <vil/algo/vil_abs_shuffle_distance.h>
#include <vil/algo/vil_binary_closing.h>
#include <vil/algo/vil_binary_dilate.h>
#include <vil/algo/vil_binary_erode.h>
#include <vil/algo/vil_binary_opening.h>
#include <vil/algo/vil_blob_finder.h>
#include <vil/algo/vil_cartesian_differential_invariants.h>
#include <vil/algo/vil_checker_board.h>
#include <vil/algo/vil_colour_space.h>
#include <vil/algo/vil_convolve_1d.h>
#include <vil/algo/vil_convolve_2d.h>
#include <vil/algo/vil_corners.h>
#include <vil/algo/vil_correlate_1d.h>
#include <vil/algo/vil_correlate_2d.h>
#include <vil/algo/vil_distance_transform.h>
#include <vil/algo/vil_dog_filter_5tap.h>
#include <vil/algo/vil_dog_pyramid.h>
#include <vil/algo/vil_exp_filter_1d.h>
#include <vil/algo/vil_exp_filter_2d.h>
#include <vil/algo/vil_exp_grad_filter_1d.h>
#include <vil/algo/vil_find_4con_boundary.h>
#include <vil/algo/vil_find_peaks.h>
#include <vil/algo/vil_fft.h>
#include <vil/algo/vil_gauss_filter.h>
#include <vil/algo/vil_gauss_reduce.h>
#include <vil/algo/vil_greyscale_closing.h>
#include <vil/algo/vil_greyscale_dilate.h>
#include <vil/algo/vil_greyscale_erode.h>
#include <vil/algo/vil_greyscale_opening.h>
#include <vil/algo/vil_grid_merge.h>
#include <vil/algo/vil_histogram.h>
#include <vil/algo/vil_histogram_equalise.h>
#include <vil/algo/vil_line_filter.h>
#include <vil/algo/vil_median.h>
#include <vil/algo/vil_normalised_correlation_2d.h>
#include <vil/algo/vil_orientations.h>
#include <vil/algo/vil_region_finder.h>
#include <vil/algo/vil_sobel_1x3.h>
#include <vil/algo/vil_sobel_3x3.h>
#include <vil/algo/vil_structuring_element.h>
#include <vil/algo/vil_suppress_non_max.h>
#include <vil/algo/vil_suppress_non_max_edges.h>
#include <vil/algo/vil_threshold.h>
#include <vil/algo/vil_tile_images.h>
#include <vil/algo/vil_trace_4con_boundary.h>
#include <vil/algo/vil_trace_8con_boundary.h>

int main() { return 0; }
