USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

TESTMAIN := test_driver.cxx
SOURCES += open_cl_test_data.cxx
MANPAGE_SOURCES += octree_test_driver.txx
MANPAGE_SOURCES += ray_bundle_test_driver.txx
MANPAGE_SOURCES += stat_test_driver.txx
MANPAGE_SOURCES += online_update_test_manager.txx
SOURCES += bit_tree_test_manager.cxx
SOURCES += ocl_scene_test_manager.cxx

TESTS += test_octree.cxx
TESTS += test_expected_image.cxx
TESTS += test_backproject_ray.cxx
TESTS += test_ray_bundle.cxx
TESTS += test_octree_image.cxx
TESTS += test_statistics.cxx
TESTS += test_refine.cxx
TESTS += test_update.cxx
TESTS += test_file_io.cxx
TESTS += test_scene_io.cxx
TESTS += test_scene_convert.cxx
TESTS += test_camera.cxx
TESTS += test_bit_tree.cxx

MINI_PROG_SOURCES += test_include.cxx
MINI_PROG_SOURCES += test_template_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
