USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

TESTMAIN := test_driver.cxx
SOURCES += open_cl_test_data.cxx
MANPAGE_SOURCES += octree_test_driver.txx
MANPAGE_SOURCES += ray_bundle_test_driver.txx

TESTS += test_octree.cxx
TESTS += test_expected_image.cxx
TESTS += test_backproject_ray.cxx
TESTS += test_ray_bundle.cxx
TESTS += test_octree_stack.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
