#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifdef WIN32
PROGRAM := awfmfc

SOURCES += awfmfcView.cpp
SOURCES += awfmfcDoc.cpp
SOURCES += awfmfc.rc
SOURCES += awfmfc.cpp
SOURCES += StdAfx.cpp
SOURCES += MainFrm.cpp
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
