USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../segv/config.mk
include ${VXLROOT}/core/vgui/config.mk
include ${VXLROOT}/core/vpl/config.mk
include ${VXLROOT}/core/vul/config.mk
include ${VXLROOT}/core/vil/config.mk

MINI_PROG_SOURCES += seg.cxx
MINI_PROG_SOURCES += seg_vil.cxx
MINI_PROG_SOURCES += seg_misc.cxx
MINI_PROG_SOURCES += negate.cxx
MINI_PROG_SOURCES += vil_convert.cxx
MINI_PROG_SOURCES += generate_tiff_pyramids.cxx
MINI_PROG_SOURCES += generate_tiff_rset.cxx
MINI_PROG_SOURCES += gen_tiff_rset_dir.cxx

################################
include ${VXLROOT}/config/top.mk
################################
