USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ${VXLROOT}/contrib/brl/bseg/segv/config.mk
include ${VXLROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += seg.cxx
MINI_PROG_SOURCES += seg_vil.cxx
MINI_PROG_SOURCES += negate.cxx
MINI_PROG_SOURCES += vil_convert.cxx

################################
include ${VXLROOT}/config/top.mk
################################
