USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ${IUEROOT}/contrib/brl/bseg/segv/config.mk
include ${IUEROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += seg.cxx
MINI_PROG_SOURCES += seg_vil.cxx

################################
include ${IUEROOT}/config/top.mk
################################
