USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

TESTMAIN := test_driver.cxx
TESTS += test_bayesian_optimizer.cxx
TESTS += test_edges.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
