SUBDIRS += kym
SUBDIRS += fsm
#SUBDIRS += awf
SUBDIRS += capes
SUBDIRS += geoff
SUBDIRS += vgui_example_mfc

################################
include ${IUEROOT}/config/top.mk
################################
