# basic services package
SUBDIRS += bbas

# segmentation package
SUBDIRS += bseg

# video view library
SUBDIRS += vvid

# multiview library
#SUBDIRS += bmvl
 
# standalone executables
SUBDIRS += bexe

# process libraries
SUBDIRS += bpro

# 3rd party libraries
SUBDIRS += b3p

################################
include ${VXLROOT}/config/top.mk
################################
