# basic services package
SUBDIRS += bbas

# segmentation package
SUBDIRS += bseg

# video view library
SUBDIRS += vvid

# multiview library
SUBDIRS += bmvl
 
# standalone executables
SUBDIRS += bexe
 
################################
include ${IUEROOT}/config/top.mk
################################
