USES += contrib/brl contrib/brl/bbas core

LIBRARY := bgrl2_algo

SOURCES += bgrl2_algs.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
