USES += contrib/mul core
include ../config.mk
include $(IUEROOT)/core/vpl/config.mk
include $(IUEROOT)/core/testlib/config.mk

TESTS += test_pdf1d.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
