USES += contrib/mul core
include ../config.mk
include ${VXLROOT}/contrib/mul/mbl/config.mk
include ${VXLROOT}/core/vnl/config.mk
include ${VXLROOT}/core/vsl/config.mk
include $(VXLROOT)/core/vpl/config.mk
include $(VXLROOT)/core/testlib/config.mk

TESTS += test_pdf1d.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
