USES += vxl mul
include ${IUEROOT}/mul/pdf1d/config.mk
include $(IUEROOT)/vxl/testlib/config.mk

TESTS += test_pdf1d.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
