#! /bin/sh
# Convert C++ to TeX:

rm -f display-image.tex draw-line.tex 2d-example.tex 3d-example.tex menubar-example.tex popup-example.tex dialog-example.tex gtk-display-image.tex gtk-movie-player.tex mouse-position.tex mouse-draw-line.tex rubberband.tex

$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/display-image.cxx > display-image.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/draw-line.cxx > draw-line.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/2d-example.cxx > 2d-example.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/3d-example.cxx > 3d-example.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/menubar-example.cxx > menubar-example.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/popup-example.cxx > popup-example.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/dialog-example.cxx > dialog-example.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/mouse-position.cxx > mouse-position.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/mouse-draw-line.cxx > mouse-draw-line.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/rubberband.cxx > rubberband.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/gtk-display-image.cxx > gtk-display-image.tex
$IUEROOT/Documentation/bin/c++2vawf $IUEROOT/vxl/vgui/examples/kym/gtk-movie-player.cxx > gtk-movie-player.tex

latex vgui_users_guide
latex vgui_users_guide
dvips vgui_users_guide -o vgui_users_guide.ps

rm -f display-image.tex draw-line.tex 2d-example.tex 3d-example.tex menubar-example.tex popup-example.tex dialog-example.tex gtk-display-image.tex gtk-movie-player.tex mouse-position.tex mouse-draw-line.tex rubberband.tex
