USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_cam_iostream.cxx
TESTS += test_video_corr_processor.cxx
TESTS += test_video_site_io.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
