USES += contrib/brl contrib/brl/bseg core

LIBRARY := brip
VERSION := 1.0

SOURCES += brip_float_ops.cxx
MANPAGE_SOURCES += brip_vil_ops.h

################################
include ${IUEROOT}/config/top.mk
################################
