#ifndef bstm_ocl_processes_h_
#define bstm_ocl_processes_h_

#include <bprb/bprb_func_process.h>
#include <bprb/bprb_macros.h>

DECLARE_FUNC_CONS(bstm_ocl_render_expected_image_process);
DECLARE_FUNC_CONS(bstm_ocl_render_expected_change_process);

DECLARE_FUNC_CONS(bstm_ocl_render_gl_expected_image_process);
DECLARE_FUNC_CONS(bstm_ocl_render_gl_expected_color_process);
DECLARE_FUNC_CONS(bstm_ocl_change_detection_process);
DECLARE_FUNC_CONS(bstm_ocl_label_along_ray_process);
DECLARE_FUNC_CONS(bstm_ocl_update_process);
DECLARE_FUNC_CONS(bstm_ocl_update_color_process);

DECLARE_FUNC_CONS(bstm_ocl_get_surface_pt_process);
DECLARE_FUNC_CONS(bstm_ocl_minfo_process);
DECLARE_FUNC_CONS(bstm_ocl_track_process);
DECLARE_FUNC_CONS(bstm_create_opencl_cache_process);
DECLARE_FUNC_CONS(bstm_clear_opencl_cache_process);
DECLARE_FUNC_CONS(bstm_ocl_update_change_process);
#endif
