#include <bsta/bsta_attributes.h>
#include <bsta/bsta_basic_functors.h>
#include <bsta/bsta_beta.h>
#include <bsta/bsta_beta_f1.h>
#include <bsta/bsta_detector_gaussian.h>
#include <bsta/bsta_detector_mixture.h>
#include <bsta/bsta_distribution.h>
#include <bsta/bsta_gauss.h>
#include <bsta/bsta_gauss_fd1.h>
#include <bsta/bsta_gauss_fd2.h>
#include <bsta/bsta_gauss_fd3.h>
#include <bsta/bsta_gauss_ff1.h>
#include <bsta/bsta_gauss_ff2.h>
#include <bsta/bsta_gauss_ff3.h>
#include <bsta/bsta_gauss_id1.h>
#include <bsta/bsta_gauss_id2.h>
#include <bsta/bsta_gauss_id3.h>
#include <bsta/bsta_gauss_if1.h>
#include <bsta/bsta_gauss_if2.h>
#include <bsta/bsta_gauss_if3.h>
#include <bsta/bsta_gauss_if4.h>
#include <bsta/bsta_gauss_sd1.h>
#include <bsta/bsta_gauss_sd2.h>
#include <bsta/bsta_gauss_sd3.h>
#include <bsta/bsta_gauss_sf1.h>
#include <bsta/bsta_gauss_sf2.h>
#include <bsta/bsta_gauss_sf3.h>
#include <bsta/bsta_gaussian.h>
#include <bsta/bsta_gaussian_full.h>
#include <bsta/bsta_gaussian_indep.h>
#include <bsta/bsta_gaussian_sphere.h>
#include <bsta/bsta_histogram.h>
#include <bsta/bsta_histogram_base.h>
#include <bsta/bsta_histogram_sptr.h>
#include <bsta/bsta_int_histogram_1d.h>
#include <bsta/bsta_int_histogram_2d.h>
#include <bsta/bsta_joint_histogram.h>
#include <bsta/bsta_joint_histogram_3d.h>
#include <bsta/bsta_joint_histogram_3d_base.h>
#include <bsta/bsta_joint_histogram_3d_sptr.h>
#include <bsta/bsta_joint_histogram_base.h>
#include <bsta/bsta_joint_histogram_sptr.h>
#include <bsta/bsta_k_medoid.h>
#include <bsta/bsta_kent.h>
#include <bsta/bsta_mixture.h>
#include <bsta/bsta_mixture_fixed.h>
#include <bsta/bsta_otsu_threshold.h>
#include <bsta/bsta_parzen.h>
#include <bsta/bsta_parzen_sf1.h>
#include <bsta/bsta_parzen_sf2.h>
#include <bsta/bsta_parzen_sf3.h>
#include <bsta/bsta_parzen_sphere.h>
#include <bsta/bsta_random_wrapper.h>
#include <bsta/bsta_sampler.h>
#include <bsta/bsta_spherical_histogram.h>
#include <bsta/bsta_von_mises.h>
#include <bsta/bsta_weibull.h>

int main() { return 0; }
