
USES = vxl

VXL := 1

# Examples may use vbl....
IULIBS = -lvil -lvbl -lvcl

include ../vil_config.mk

include $(IUELOCALROOT)/config/top-params.mk

MINI_PROG_SOURCES += vil_convolve_1d.cxx
MINI_PROG_SOURCES += vil_convolve.cxx
MINI_PROG_SOURCES += vil_convert.cxx
MINI_PROG_SOURCES += vil_crop.cxx
MINI_PROG_SOURCES += vil_info.cxx
MINI_PROG_SOURCES += vil_print_section.cxx
MINI_PROG_SOURCES += vil_scale.cxx
MINI_PROG_SOURCES += vil_flipud.cxx

include $(IUELOCALROOT)/config/top-rules.mk
