
USES = vxl

VXL := 1

IULIBS = -lvil -lvcl

include ../vil_config.mk

include $(IUELOCALROOT)/config/top-params.mk

MINI_PROG_SOURCES += vil_convert.cxx
MINI_PROG_SOURCES += vil_crop.cxx
MINI_PROG_SOURCES += vil_info.cxx
MINI_PROG_SOURCES += vil_print_section.cxx

include $(IUELOCALROOT)/config/top-rules.mk
