USES = vxl
# The following three are needed, as libvil uses tiff, jpeg, png if available:
TRY_TIFF := 1
TRY_JPEG := 1
TRY_PNG  := 1

# Examples may use vbl....
IULIBS = -lvil -lvbl -lvpl -lvcl

MINI_PROG_SOURCES += vil_convolve_1d.cxx
MINI_PROG_SOURCES += vil_convolve.cxx
MINI_PROG_SOURCES += vil_convert.cxx
MINI_PROG_SOURCES += vil_crop.cxx
MINI_PROG_SOURCES += vil_info.cxx
MINI_PROG_SOURCES += vil_print_section.cxx
MINI_PROG_SOURCES += vil_scale.cxx
MINI_PROG_SOURCES += vil_flipud.cxx
MINI_PROG_SOURCES += vil_clamp_example.cxx
MINI_PROG_SOURCES += vil_scale_intensities_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
