USES += core
include ${IUEROOT}/core/vil/algo/config.mk
include ${IUEROOT}/core/vul/config.mk
include ${IUEROOT}/core/testlib/config.mk

MINI_PROG_SOURCES += example1.cxx
MINI_PROG_SOURCES += example2.cxx
MINI_PROG_SOURCES += example3.cxx
MINI_PROG_SOURCES += example4.cxx
MINI_PROG_SOURCES += example5.cxx
MINI_PROG_SOURCES += example6.cxx
MINI_PROG_SOURCES += file_example1.cxx
MINI_PROG_SOURCES += file_example2.cxx
MINI_PROG_SOURCES += file_example3.cxx
MINI_PROG_SOURCES += file_example4.cxx
MINI_PROG_SOURCES += algo_example1.cxx
MINI_PROG_SOURCES += algo_example2.cxx

MINI_PROG_SOURCES += vil_convolve_tool.cxx
MINI_PROG_SOURCES += vil_correlate_grad_tool.cxx
MINI_PROG_SOURCES += vil_exp_grad_filter_tool.cxx
MINI_PROG_SOURCES += vil_image_copy.cxx
MINI_PROG_SOURCES += example_interpolate.cxx
MINI_PROG_SOURCES += example_complex.cxx

################################
include ${IUEROOT}/config/top.mk
################################
