USES = vxl mul
include ${IUEROOT}/vxl/vil/config.mk
include ${IUEROOT}/vxl/testlib/config.mk
IULIBS += -lvil2 -lvil2-algo

MINI_PROG_SOURCES += example1.cxx
MINI_PROG_SOURCES += example2.cxx
MINI_PROG_SOURCES += example3.cxx
MINI_PROG_SOURCES += example4.cxx
MINI_PROG_SOURCES += example5.cxx
MINI_PROG_SOURCES += example6.cxx
MINI_PROG_SOURCES += file_example1.cxx
MINI_PROG_SOURCES += file_example2.cxx
MINI_PROG_SOURCES += algo_example1.cxx

################################
include ${IUEROOT}/config/top.mk
################################
