USES += core
include ../config.mk

MINI_PROG_SOURCES += example1.cxx
MINI_PROG_SOURCES += example2.cxx
MINI_PROG_SOURCES += example3.cxx
MINI_PROG_SOURCES += example4.cxx
MINI_PROG_SOURCES += example5.cxx
MINI_PROG_SOURCES += example6.cxx
MINI_PROG_SOURCES += file_example1.cxx
MINI_PROG_SOURCES += file_example2.cxx
MINI_PROG_SOURCES += file_example3.cxx
MINI_PROG_SOURCES += file_example4.cxx

MINI_PROG_SOURCES += vil_image_copy.cxx
MINI_PROG_SOURCES += vil_rotate_image.cxx
MINI_PROG_SOURCES += example_interpolate.cxx
MINI_PROG_SOURCES += vil_resample_image.cxx
#MINI_PROG_SOURCES += generate_nitf_pyramid_images.cxx

################################
include ${VXLROOT}/config/top.mk
################################
