# camera calibration
#SUBDIRS += bcal

# 3-d reconstruction 
#SUBDIRS += brct

# multi-view gui stuff , xerces is required to read stuff in from Tjr
SUBDIRS += bmvv

################################
include ${IUEROOT}/config/top.mk
################################
