USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm_batch

SOURCES += reg_boxm.cxx

################################
include ${VXLROOT}/config/top.mk
################################
