USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_batch
VERSION := 1.0

SOURCES += reg_boxm.cxx

################################
include ${VXLROOT}/config/top.mk
################################
