# This is the geometry conversions directory makefile

USES := vxl gel COOL GeneralUtility SpatialObjects Numerics
IMMEDIATE_LIBS := -lvdgl -vbl -lDigitalGeometry -lSpatialBasics -lBasics

SUBDIRS := tests

MANPAGE_SOURCES += DigitalCurve_to_vdgl.h

################################
include ${IUEROOT}/config/top.mk
################################
