USES += contrib/mul core
include ${IUEROOT}/contrib/mul/ipts/config.mk

MINI_PROG_SOURCES += find_dog_peaks.cxx

################################
include ${IUEROOT}/config/top.mk
################################
