USES += contrib/mul core
include ${VXLROOT}/core/vul/config.mk
include ${VXLROOT}/contrib/mul/ipts/config.mk

MINI_PROG_SOURCES += find_dog_peaks.cxx
MINI_PROG_SOURCES += find_scale_corners.cxx
MINI_PROG_SOURCES += find_scale_entropy_peaks.cxx
MINI_PROG_SOURCES += show_local_entropy.cxx
SOURCES += find_scale_orient_entropy_peaks.cxx
SOURCES += show_orientation_entropy.cxx

################################
include ${VXLROOT}/config/top.mk
################################
