USES += contrib/mul core
include ${IUEROOT}/contrib/mul/ipts/config.mk

MINI_PROG_SOURCES += find_dog_peaks.cxx
MINI_PROG_SOURCES += find_scale_corners.cxx

################################
include ${IUEROOT}/config/top.mk
################################
