USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/brl/bmvl core
include ../config.mk
include ${VXLROOT}/core/vgui/config.mk

#MINI_PROG_SOURCES += mviewer.cxx
#MINI_PROG_SOURCES += modtom.cxx
MINI_PROG_SOURCES += recon.cxx
MINI_PROG_SOURCES += cal.cxx
MINI_PROG_SOURCES += ftool.cxx

################################
include ${VXLROOT}/config/top.mk
################################
