USES := contrib/brl contrib/brl/bbas contrib/brl/bmvl contrib/oxl contrib/gel core
include ../config.mk

PROGRAM := mviewer
SOURCES += mviewer.cxx

################################
include ${IUEROOT}/config/top.mk
################################
