USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/brl/bmvl core
include ../config.mk

#MINI_PROG_SOURCES += mviewer.cxx
#MINI_PROG_SOURCES += modtom.cxx
MINI_PROG_SOURCES += recon.cxx

################################
include ${IUEROOT}/config/top.mk
################################
