USES += contrib/mul core

LIBRARY := msm-utils
VERSION := 1.0

SOURCES += msm_draw_shape_to_eps.cxx
SOURCES += msm_shape_mode_view.cxx

################################
include ${VXLROOT}/config/top.mk
################################
