#include <boxm/algo/rt/boxm_change_3d_functor.h>
#include <boxm/algo/rt/boxm_change_probability_functor.h>
#include <boxm/algo/rt/boxm_compute_num_rays_statistics.h>
#include <boxm/algo/rt/boxm_edge_tangent_updater.h>
#include <boxm/algo/rt/boxm_edge_updater.h>
#include <boxm/algo/rt/boxm_expected_edge_functor.h>
#include <boxm/algo/rt/boxm_generate_edge_sample_functor.h>
#include <boxm/algo/rt/boxm_generate_edge_tangent_sample_functor.h>
#include <boxm/algo/rt/boxm_generate_opt2_sample_functor.h>
#include <boxm/algo/rt/boxm_generate_opt3_sample_functor.h>
#include <boxm/algo/rt/boxm_generate_opt_sample_functor.h>
#include <boxm/algo/rt/boxm_generate_shadow_sample_functor.h>
#include <boxm/algo/rt/boxm_opt2_optimizer.h>
#include <boxm/algo/rt/boxm_opt3_optimizer.h>
#include <boxm/algo/rt/boxm_opt_appearance_estimator.h>
#include <boxm/algo/rt/boxm_opt_rt_bayesian_optimizer.h>
#include <boxm/algo/rt/boxm_pre_infinity_functor.h>
#include <boxm/algo/rt/boxm_render_expected_depth_functor.h>
#include <boxm/algo/rt/boxm_render_expected_edge_image_functor.h>
#include <boxm/algo/rt/boxm_render_expected_edge_tangent_image_functor.h>
#include <boxm/algo/rt/boxm_render_expected_image_functor.h>
#include <boxm/algo/rt/boxm_render_expected_shadow_image_functor.h>
#include <boxm/algo/rt/boxm_rpc_registration.h>
#include <boxm/algo/rt/boxm_shadow_app_initializer.h>
#include <boxm/algo/rt/boxm_shadow_appearance_estimator.h>
#include <boxm/algo/rt/boxm_shadow_bayes_optimizer.h>
#include <boxm/algo/rt/boxm_sun_vis_prob_functor.h>
#include <boxm/algo/rt/boxm_update_image_functor.h>

int main() { return 0; }
