# van-duc region finder (ported from TargetJr)
SUBDIRS += gevd

# matcher
SUBDIRS += geml

# octree stuff from Geoff's thesis
SUBDIRS += octree

# Multi-view database
SUBDIRS += gmvl

# Dense matcher
SUBDIRS += vsrl

# Triangulation code
SUBDIRS += gtrl

# spatial objects
SUBDIRS += vsol

# topology
SUBDIRS += gst vtol

# digital  geometry
SUBDIRS += vdgl

SUBDIRS += mrc
# photogrammetry in mrc/vpgl
# coordinate systems addon in mrc/vcsl

# Kanade-Lucas-Tomasi feature tracker
SUBDIRS += vgel gkll

# Dense matcher
SUBDIRS += vmal

# Experiments with the vidl library and vgui (JLM)
SUBDIRS += jvid

################################
include ${IUEROOT}/config/top.mk
################################
