# spatial objects
SUBDIRS += vsol

# digital  geometry
SUBDIRS += vdgl

# topology
SUBDIRS += vtol gst

# van-duc region finder (ported from TargetJr)
SUBDIRS += gevd

# matcher
SUBDIRS += geml

# Multi-view database
SUBDIRS += gmvl

# Dense matcher
SUBDIRS += vsrl vmal

# Triangulation code
SUBDIRS += gtrl

# octree stuff from Geoff's thesis
SUBDIRS += octree

SUBDIRS += mrc
# photogrammetry in mrc/vpgl
# coordinate systems add-on in mrc/vcsl

# Kanade-Lucas-Tomasi feature tracker
SUBDIRS += vgel gkll

# Experiments with the vidl_vil1 library and vgui (JLM)
SUBDIRS += jvid

# Intensity face attributes (MPP)
SUBDIRS += vifa

################################
include ${IUEROOT}/config/top.mk
################################
