USES += vxl mul
include ${IUEROOT}/mul/mil3d/config.mk

TESTS += test_mil3d.cxx # includes test_image_3d_of.cxx test_transform_3d.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
