USES += vxl mul
include ${IUEROOT}/vxl/vnl/algo/config.mk
include ${IUEROOT}/vxl/vil/config.mk

IULIBS := -lmil3d -lmil -lvpdfl -lmbl -lvnl-io -lvnl-algo -lvgl-io -lvgl -lvnl -lvil -lvsl -lvpl

TESTS += test_mil3d.cxx # includes test_image_3d_of.cxx test_transform_3d.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
