USES += contrib/mul core
include ../config.mk
include ${VXLROOT}/contrib/mul/mil/config.mk
include ${VXLROOT}/core/vgl/config.mk
include ${VXLROOT}/core/vnl/config.mk
include ${VXLROOT}/core/vsl/config.mk
include $(VXLROOT)/core/vpl/config.mk
include $(VXLROOT)/core/testlib/config.mk

TESTS += test_mil3d.cxx # includes test_image_3d_of.cxx test_transform_3d.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
