#ifndef bstm_multi_processes_h_
#define bstm_multi_processes_h_

#include <bprb/bprb_func_process.h>
#include <bprb/bprb_macros.h>

//the init functions
DECLARE_FUNC_CONS(bstm_multi_write_scene_xml_process);
DECLARE_FUNC_CONS(bstm_multi_create_scene_process);
DECLARE_FUNC_CONS(bstm_multi_load_scene_process);
DECLARE_FUNC_CONS(bstm_multi_create_cache_process);
DECLARE_FUNC_CONS(bstm_multi_clear_cache_process);
DECLARE_FUNC_CONS(bstm_multi_write_cache_process);
DECLARE_FUNC_CONS(bstm_multi_add_block_process);
DECLARE_FUNC_CONS(bstm_multi_scene_statistics_process);
DECLARE_FUNC_CONS(bstm_multi_bundle_to_scene_process);
DECLARE_FUNC_CONS(bstm_multi_boxm2_scene_to_bstm_multi_process);
DECLARE_FUNC_CONS(bstm_multi_describe_scene_process);
DECLARE_FUNC_CONS(bstm_multi_scene_bbox_process);
DECLARE_FUNC_CONS(bstm_multi_scene_lvcs_process);

#endif
