USES += contrib/conversions core

#TESTMAIN := test_driver.cxx

TESTS += 

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
