USES := conversions vxl

#TESTMAIN := test_driver.cxx

TESTS += 

IULIBS := 

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
