USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vpgl_pro
VERSION := 1.0

MANPAGE_SOURCES += vpgl_processes.h
SOURCES += processes/vpgl_load_proj_camera_process.cxx
SOURCES += processes/vpgl_load_rational_camera_process.cxx
SOURCES += processes/vpgl_load_rational_camera_nitf_process.cxx
SOURCES += processes/vpgl_load_perspective_camera_process.cxx
SOURCES += processes/vpgl_save_perspective_camera_process.cxx
SOURCES += processes/vpgl_save_rational_camera_process.cxx
SOURCES += processes/vpgl_nitf_camera_coverage_process.cxx
SOURCES += vpgl_register.cxx

################################
include ${VXLROOT}/config/top.mk
################################
