USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vpgl_pro
VERSION := 1.0

SOURCES += vpgl_load_proj_camera_process.cxx
SOURCES += vpgl_load_rational_camera_process.cxx
SOURCES += vpgl_load_perspective_camera_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
