USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vpgl_pro
VERSION := 1.0

SOURCES += vpgl_register.cxx
MANPAGE_SOURCES += vpgl_processes.h
SOURCES += processes/vpgl_load_proj_camera_process.cxx
SOURCES += processes/vpgl_load_rational_camera_process.cxx
SOURCES += processes/vpgl_load_rational_camera_nitf_process.cxx
SOURCES += processes/vpgl_load_perspective_camera_process.cxx
SOURCES += processes/vpgl_save_perspective_camera_process.cxx
SOURCES += processes/vpgl_save_rational_camera_process.cxx
SOURCES += processes/vpgl_nitf_camera_coverage_process.cxx
SOURCES += processes/vpgl_load_local_rational_camera_process.cxx
SOURCES += processes/vpgl_scale_perspective_camera_process.cxx
SOURCES += processes/vpgl_projective_to_rational_camera_process.cxx
SOURCES += processes/vpgl_create_local_rational_camera_nitf_process.cxx
SOURCES += processes/vpgl_create_local_rational_camera_process.cxx
SOURCES += processes/vpgl_create_perspective_camera_process.cxx
SOURCES += processes/vpgl_correct_rational_camera_process.cxx
SOURCES += processes/vpgl_save_perspective_camera_vrml_process.cxx
SOURCES += processes/vpgl_project_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
