#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

USES := vxl
USES += mul

LIBRARY := vbl-io
VERSION := 1.0

SOURCES += vbl_io_user_info.cxx

# Additional files to document:
# MANPAGE_SOURCES += yyyyyyyyyyy.txx

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
