USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2_cpp

SUBDIRS += pro algo

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
