USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2_cpp

SOURCES += boxm2_cpp_render_process.cxx
SOURCES += boxm2_cpp_processor.cxx
SOURCES += boxm2_mog3_grey_processor.cxx
MANPAGE_SOURCES += boxm2_render_exp_image_functor.h
MANPAGE_SOURCES += boxm2_cpp_process_base.h
MANPAGE_SOURCES += boxm2_cast_ray_function.h
SOURCES += boxm2_cpp_update_process.cxx
MANPAGE_SOURCES += boxm2_update_image_functor.h
SOURCES += boxm2_cpp_refine_process.cxx
MANPAGE_SOURCES += boxm2_refine_block_function.h
MANPAGE_SOURCES += boxm2_data_serial_iterator.h

################################
include ${VXLROOT}/config/top.mk
################################
