USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := bppy
VERSION := 1.0

SOURCES += batch.cxx
SOURCES += reg.cxx

################################
include ${VXLROOT}/config/top.mk
################################
