USES = vxl

IULIBS += -lvcsl
IULIBS += -lvbl
IULIBS += -lvnl
IULIBS += -lvcl

MINI_PROG_SOURCES += example1.cxx

################################
include ${IUEROOT}/config/top.mk
################################
