USES := vxl gel
include $(IUEROOT)/gel/gevd/config.mk
include $(IUEROOT)/vxl/testlib/config.mk

TESTS += test_gevd_bufferxy.cxx
TESTS += test_gevd_memory_mixin.cxx
TESTS += test_gevd_param_mixin.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################

