USES += contrib/gel core
include ../config.mk
include $(IUEROOT)/core/testlib/config.mk
include $(IUEROOT)/core/vpl/config.mk

TESTS += test_gevd_bufferxy.cxx
TESTS += test_gevd_memory_mixin.cxx
TESTS += test_gevd_param_mixin.cxx
TESTS += test_gevd_float_operators.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################

