// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef FLTK_blender_ui_h
#define FLTK_blender_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *stackpane_frame;
#include <vgui/impl/Fl/vgui_Fl_adaptor.h>
extern vgui_Fl_adaptor *flpane;
#include <FL/Fl_Value_Slider.H>
extern void alpha_sliderCB(Fl_Value_Slider*, void*);
extern Fl_Value_Slider *alpha_slider;
#include <FL/Fl_Box.H>
extern Fl_Box *pad;
Fl_Window* make_window();
#endif // FLTK_blender_ui_h
