// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "Fl_movie_ui.h"

Fl_Group *stackpane_frame=(Fl_Group *)0;

vgui_Fl_adaptor *flpane=(vgui_Fl_adaptor *)0;

Fl_Group *stackcontrol=(Fl_Group *)0;

Fl_Output *image_name=(Fl_Output *)0;

Fl_Scrollbar *scroll_pane=(Fl_Scrollbar *)0;

Fl_Group *decoration=(Fl_Group *)0;

Fl_Group *movieplayer=(Fl_Group *)0;

Fl_Button *play=(Fl_Button *)0;

Fl_Button *stop=(Fl_Button *)0;

Fl_Roller *speed=(Fl_Roller *)0;

Fl_Button *start=(Fl_Button *)0;

Fl_Button *end=(Fl_Button *)0;

Fl_Output *fps=(Fl_Output *)0;

Fl_Group *title=(Fl_Group *)0;

Fl_Group *padding2=(Fl_Group *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(538, 486);
    w = o;
    o->labelfont(2);
    o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    { Fl_Group* o = stackpane_frame = new Fl_Group(5, 60, 525, 420);
      o->box(FL_ENGRAVED_BOX);
      o->align(FL_ALIGN_CLIP);
      { vgui_Fl_adaptor* o = flpane = new vgui_Fl_adaptor(10, 90, 514, 366, "vgui_Fl_adaptor");
        Fl_Group::current()->resizable(o);
      }
      { Fl_Group* o = stackcontrol = new Fl_Group(10, 65, 515, 25);
        { Fl_Output* o = image_name = new Fl_Output(10, 65, 125, 20);
          o->textsize(12);
          o->callback((Fl_Callback*)image_nameCB);
        }
        o->end();
      }
      { Fl_Scrollbar* o = scroll_pane = new Fl_Scrollbar(9, 460, 515, 15);
        o->type(1);
        o->maximum(10);
        o->slider_size(0.1);
        o->callback((Fl_Callback*)scroll_paneCB);
      }
      o->end();
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = decoration = new Fl_Group(0, -15, 530, 70);
      { Fl_Group* o = movieplayer = new Fl_Group(185, 10, 345, 35);
        o->box(FL_BORDER_BOX);
        o->color(41);
        o->align(FL_ALIGN_CENTER);
        { Fl_Button* o = play = new Fl_Button(190, 15, 30, 25, "@>");
          o->type(1);
          o->down_box(FL_DOWN_BOX);
          o->labeltype(FL_SYMBOL_LABEL);
          o->callback((Fl_Callback*)playCB);
        }
        { Fl_Button* o = stop = new Fl_Button(225, 15, 30, 25, "@||");
          o->down_box(FL_DOWN_BOX);
          o->labeltype(FL_SYMBOL_LABEL);
          o->callback((Fl_Callback*)stopCB);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Roller* o = speed = new Fl_Roller(265, 20, 110, 15);
          o->type(1);
          o->minimum(-125);
          o->maximum(125);
          o->step(1);
          o->value(5);
          o->callback((Fl_Callback*)speedCB);
        }
        { Fl_Button* o = start = new Fl_Button(465, 15, 25, 25, "@<<");
          o->down_box(FL_DOWN_BOX);
          o->labeltype(FL_SYMBOL_LABEL);
          o->callback((Fl_Callback*)startCB);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Button* o = end = new Fl_Button(495, 15, 25, 25, "@>>");
          o->down_box(FL_DOWN_BOX);
          o->labeltype(FL_SYMBOL_LABEL);
          o->callback((Fl_Callback*)endCB);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Output* o = fps = new Fl_Output(410, 15, 40, 20, "fps:");
          o->labelsize(12);
          o->labelcolor(7);
          o->textsize(12);
        }
        o->end();
      }
      { Fl_Group* o = title = new Fl_Group(15, 10, 80, 30, "TargetJr");
        o->box(FL_ENGRAVED_BOX);
        o->color(41);
        o->selection_color(41);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(1);
        o->labelcolor(49);
        o->align(FL_ALIGN_CENTER);
        o->end();
      }
      { Fl_Group* o = padding2 = new Fl_Group(110, 50, 55, 5);
        o->box(FL_FLAT_BOX);
        o->end();
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    o->end();
  }
  return w;
}
