// generated by Fast Light User Interface Designer (fluid) version 1.00

#ifndef FLTK_movie_ui_h
#define FLTK_movie_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *stackpane_frame;
#include <vgui/impl/Fl/vgui_Fl_adaptor.h>
extern vgui_Fl_adaptor *flpane;
extern Fl_Group *stackcontrol;
#include <FL/Fl_Output.H>
extern void image_nameCB(Fl_Output*, void*);
extern Fl_Output *image_name;
#include <FL/Fl_Scrollbar.H>
extern void scroll_paneCB(Fl_Scrollbar*, void*);
extern Fl_Scrollbar *scroll_pane;
extern Fl_Group *decoration;
extern Fl_Group *movieplayer;
#include <FL/Fl_Button.H>
extern void playCB(Fl_Button*, void*);
extern Fl_Button *play;
extern void stopCB(Fl_Button*, void*);
extern Fl_Button *stop;
#include <FL/Fl_Roller.H>
extern void speedCB(Fl_Roller*, void*);
extern Fl_Roller *speed;
extern void startCB(Fl_Button*, void*);
extern Fl_Button *start;
extern void endCB(Fl_Button*, void*);
extern Fl_Button *end;
extern Fl_Output *fps;
extern Fl_Group *title;
extern Fl_Group *padding2;
Fl_Window* make_window();
#endif // FLTK_movie_ui_h
