// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "Fl_twowin_ui.h"

vgui_Fl_adaptor *flpane1=(vgui_Fl_adaptor *)0;

vgui_Fl_adaptor *flpane2=(vgui_Fl_adaptor *)0;

Fl_Box *pad=(Fl_Box *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(593, 260);
    w = o;
    o->labelfont(2);
    o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    { vgui_Fl_adaptor* o = flpane1 = new vgui_Fl_adaptor(4, 6, 281, 251, "flpane1");
      o->box(FL_FLAT_BOX);
      o->color(1);
    }
    { vgui_Fl_adaptor* o = flpane2 = new vgui_Fl_adaptor(290, 7, 298, 250, "flpane2");
      o->box(FL_FLAT_BOX);
      o->color(2);
    }
    { Fl_Box* o = pad = new Fl_Box(156, 77, 320, 38);
      o->hide();
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  return w;
}
