USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${VXLROOT}/core/vbl/config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS += test_bugl.cxx
TESTS += test_random_transform_set_2d.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
