USES += contrib/brl contrib/brl/bbas core
include ../config.mk

TESTS += test_bugl.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
