#include <vsol/vsol_box_2d.h>
#include <vsol/vsol_box_2d_sptr.h>
#include <vsol/vsol_box_3d.h>
#include <vsol/vsol_box_3d_sptr.h>
#include <vsol/vsol_conic_2d.h>
#include <vsol/vsol_conic_2d_sptr.h>
#include <vsol/vsol_curve_2d.h>
#include <vsol/vsol_curve_2d_sptr.h>
#include <vsol/vsol_curve_3d.h>
#include <vsol/vsol_curve_3d_sptr.h>
#include <vsol/vsol_group_2d.h>
#include <vsol/vsol_group_2d_sptr.h>
#include <vsol/vsol_group_3d.h>
#include <vsol/vsol_group_3d_sptr.h>
#include <vsol/vsol_line_2d.h>
#include <vsol/vsol_line_2d_sptr.h>
#include <vsol/vsol_line_3d.h>
#include <vsol/vsol_line_3d_sptr.h>
#include <vsol/vsol_point_2d.h>
#include <vsol/vsol_point_2d_sptr.h>
#include <vsol/vsol_point_3d.h>
#include <vsol/vsol_point_3d_sptr.h>
#include <vsol/vsol_polygon_2d.h>
#include <vsol/vsol_polygon_2d_sptr.h>
#include <vsol/vsol_polygon_3d.h>
#include <vsol/vsol_polygon_3d_sptr.h>
#include <vsol/vsol_polyhedron.h>
#include <vsol/vsol_polyhedron_sptr.h>
#include <vsol/vsol_polyline_2d.h>
#include <vsol/vsol_polyline_2d_sptr.h>
#include <vsol/vsol_polyline_3d.h>
#include <vsol/vsol_polyline_3d_sptr.h>
#include <vsol/vsol_digital_curve_2d.h>
#include <vsol/vsol_digital_curve_2d_sptr.h>
#include <vsol/vsol_digital_curve_3d.h>
#include <vsol/vsol_digital_curve_3d_sptr.h>
#include <vsol/vsol_rectangle_2d.h>
#include <vsol/vsol_rectangle_2d_sptr.h>
#include <vsol/vsol_rectangle_3d.h>
#include <vsol/vsol_rectangle_3d_sptr.h>
#include <vsol/vsol_region_2d.h>
#include <vsol/vsol_region_2d_sptr.h>
#include <vsol/vsol_region_3d.h>
#include <vsol/vsol_region_3d_sptr.h>
#include <vsol/vsol_spatial_object_2d.h>
#include <vsol/vsol_spatial_object_2d_sptr.h>
#include <vsol/vsol_spatial_object_3d.h>
#include <vsol/vsol_spatial_object_3d_sptr.h>
#include <vsol/vsol_surface_3d.h>
#include <vsol/vsol_surface_3d_sptr.h>
#include <vsol/vsol_tetrahedron.h>
#include <vsol/vsol_tetrahedron_sptr.h>
#include <vsol/vsol_triangle_2d.h>
#include <vsol/vsol_triangle_2d_sptr.h>
#include <vsol/vsol_triangle_3d.h>
#include <vsol/vsol_triangle_3d_sptr.h>
#include <vsol/vsol_volume_3d.h>
#include <vsol/vsol_volume_3d_sptr.h>

int main() { return 0; }
