USES += contrib/gel core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTS += test_vertex_2d.cxx
TESTS += test_zero_chain.cxx
TESTS += test_edge_2d.cxx
TESTS += test_one_chain.cxx
TESTS += test_face_2d.cxx
TESTS += test_two_chain.cxx
TESTS += test_block.cxx
TESTS += vtol_test_refcounting.cxx
TESTS += test_cycle_processor.cxx
TESTS += vtol_test_timing.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
