USES += contrib/brl core

LIBRARY := bsvg_pro
VERSION := 1.0

MANPAGE_SOURCES += bsvg_processes.h
SOURCES += processes/bsvg_plot_roc_process.cxx
SOURCES += bsvg_register.cxx

################################
include ${VXLROOT}/config/top.mk
################################
