USES += contrib/mul core
include ../config.mk

MINI_PROG_SOURCES += print_log_properties.cxx
MINI_PROG_SOURCES += sample_stats.cxx

################################
include ${VXLROOT}/config/top.mk
################################
