USES += contrib/mul core
include ../config.mk

MINI_PROG_SOURCES += print_log_properties.cxx
MINI_PROG_SOURCES += sample_stats.cxx
MINI_PROG_SOURCES += mbl_masked_file_merge.cxx
MINI_PROG_SOURCES += mbl_mask_logic.cxx
MINI_PROG_SOURCES += mbl_mask_on_mask.cxx
MINI_PROG_SOURCES += mbl_apply_mask_to_file.cxx

################################
include ${VXLROOT}/config/top.mk
################################
