USES += contrib/oul core

LIBRARY := oufgl
IMMEDIATE_LIBS = -lvil

#SOURCES += asyncio.cxx
SOURCES += frame_grabber_v4l.cxx
SOURCES += frame_grabber_vil.cxx
MANPAGE_SOURCES += frame_grabber.h

SUBDIRS += examples

################################
include ${VXLROOT}/config/top.mk
################################
