USES += vxl oul
LIBRARY := oufgl
IMMEDIATE_LIBS = -lvil

SOURCES += asyncio.cpp
SOURCES += frame_grabber_pxc200.cc
MANPAGE_SOURCES += frame_grabber.h
MANPAGE_SOURCES += bt848.h
MANPAGE_SOURCES += pxc200.h
MANPAGE_SOURCES += sysdep.h

################################
include ${IUEROOT}/config/top.mk
################################
