MANPAGE_SOURCES += bsta_adaptive_updater.txx
MANPAGE_SOURCES += bsta_bayes_functor.h
MANPAGE_SOURCES += bsta_gaussian_stats.h
MANPAGE_SOURCES += bsta_gaussian_updater.h
MANPAGE_SOURCES += bsta_mixture_functors.h
MANPAGE_SOURCES += bsta_truth_updater.txx
