USES += contrib/mul core

LIBRARY := msm
VERSION := 1.0

SOURCES += msm_points.cxx
#SOURCES += msm_add_all_loaders.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
