TESTMAIN := test_driver.cxx
TESTS += test_matcher.cxx
TESTS += test_transform.cxx
TESTS += test_compute_tracks.cxx
TESTS += test_lowe_pyramid_set.cxx
TESTS += test_match_keypoints.cxx
TESTS += test_roi.cxx
MINI_PROG_SOURCES += test_include.cxx
