USES = vxl gel
IULIBS += -lvtol -lvsol -lvgl -lvbl -lvnl -lvul

MINI_PROG_SOURCES += example2d.cxx
#MINI_PROG_SOURCES += example3d.cxx

################################
include ${IUEROOT}/config/top.mk
################################
