USES += contrib/gel core
include ../config.mk

MINI_PROG_SOURCES += example2d.cxx
MINI_PROG_SOURCES += example3d.cxx
MINI_PROG_SOURCES += example_vdgl.cxx

################################
include ${VXLROOT}/config/top.mk
################################
