USES = # completely independent!

LIBRARY := JPEG
VERSION := 1.0

SOURCES += jcapimin.cc
SOURCES += jcapistd.cc 
SOURCES += jccoefct.cc 
SOURCES += jccolor.cc 
SOURCES += jcdctmgr.cc 
SOURCES += jchuff.cc
SOURCES += jcinit.cc 
SOURCES += jcmainct.cc 
SOURCES += jcmarker.cc 
SOURCES += jcmaster.cc 
SOURCES += jcomapi.cc 
SOURCES += jcparam.cc 
SOURCES += jcphuff.cc 
SOURCES += jcprepct.cc 
SOURCES += jcsample.cc 
SOURCES += jctrans.cc 
SOURCES += jdapimin.cc 
SOURCES += jdapistd.cc
SOURCES += jdatadst.cc 
SOURCES += jdatasrc.cc 
SOURCES += jdcoefct.cc 
SOURCES += jdcolor.cc 
SOURCES += jddctmgr.cc 
SOURCES += jdhuff.cc
SOURCES += jdinput.cc 
SOURCES += jdmainct.cc 
SOURCES += jdmarker.cc 
SOURCES += jdmaster.cc 
SOURCES += jdmerge.cc 
SOURCES += jdphuff.cc
SOURCES += jdpostct.cc 
SOURCES += jdsample.cc 
SOURCES += jdtrans.cc 
SOURCES += jerror.cc 
SOURCES += jfdctflt.cc 
SOURCES += jfdctfst.cc
SOURCES += jfdctint.cc 
SOURCES += jidctflt.cc 
SOURCES += jidctfst.cc 
SOURCES += jidctint.cc 
SOURCES += jidctred.cc 
SOURCES += jquant1.cc
SOURCES += jquant2.cc 
SOURCES += jutils.cc 
SOURCES += jmemmgr.cc 
SOURCES += jmemansi.cc


##########################################
include ${SYS_IUPACKAGES}/config/top.mk
##########################################

