USES += contrib/gel contrib/gel/mrc core
include ../config.mk
include ${VXLROOT}/core/vgl/config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_icam_view_sphere.cxx
TESTS += test_minimizer.cxx
TESTS += test_icam_transform.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
