USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += bwm_img_main.cxx
MINI_PROG_SOURCES += bwm_main.cxx

################################
include ${VXLROOT}/config/top.mk
################################
