USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ../reg/config.mk
include ../algo/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/config.mk
include ${VXLROOT}/core/vgui/config.mk
include ${VXLROOT}/core/vgl/config.mk
include ${VXLROOT}/core/vil/config.mk

MINI_PROG_SOURCES += bwm_main.cxx
MINI_PROG_SOURCES += bwm_batch_project.cxx
MINI_PROG_SOURCES += bwm_batch_project_meshes_to_perspective_video.cxx
MINI_PROG_SOURCES += bwm_bundler_to_video_site.cxx

################################
include ${VXLROOT}/config/top.mk
################################
