USES += vxl gel

IULIBS := -lvdgl -lvbl -lvnl-algo -lnetlib -lvnl -lvsol -lvgl 

MINI_PROG_SOURCES += test_vdgl.cxx
MINI_PROG_SOURCES += test1_vdgl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
