USES += vxl gel
include $(IUEROOT)/vxl/vnl/algo/config.mk

IULIBS := -lvdgl -lvbl -lvul -lvgl-algo -lvgl -lvnl-algo -lvnl -lvsol

MINI_PROG_SOURCES += test_vdgl.cxx
MINI_PROG_SOURCES += test1_vdgl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
