# Combinatorial Maps and Topological Maps handling
SUBDIRS += vmap

# Digital Topology
SUBDIRS += vdtop

# Combinatorial Pyramids and Topological Pyramids handling
SUBDIRS += vpyr

################################
include ${VXLROOT}/config/top.mk
################################
