# Digital Topology
SUBDIRS += vdtop

# Combinatorial Maps and Topological Maps handling
SUBDIRS += vmap

# Combinatorial Pyramids and Topological Pyramids handling
SUBDIRS += vpyr

################################
include ${IUEROOT}/config/top.mk
################################
