USES += contrib/brl contrib/brl/bbas contrib/gel core

LIBRARY := btol
VERSION := 1.0

SOURCES += btol_edge_algs.cxx
SOURCES += btol_vertex_algs.cxx

################################
include ${IUEROOT}/config/top.mk
################################
