USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2-class

SOURCES += boxm2_class_generate_samples.cxx

SUBDIRS += exe

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
