#ifndef rrel_fwd_h_
#define rrel_fwd_h_

class rrel_affine_est;
class rrel_cauchy_obj;
class rrel_wls_obj;
class rrel_estimation_problem;
class rrel_homography2d_est;
class rrel_homography2d_est_aff;
class rrel_estimation_problem;
class rrel_wls_obj;
class rrel_irls;
class rrel_kernel_density_obj;
class rrel_linear_regression;
class rrel_lms_obj;
class rrel_lts_obj;
class rrel_m_est_obj;
class rrel_mlesac_obj;
class rrel_muse_key_type;
class rrel_muse_table_entry;
class rrel_muse_table;
class rrel_muse_table;
class rrel_muset_obj;
class rrel_objective;
class rrel_orthogonal_regression;
class rrel_quad_est;
class rrel_objective;
class rrel_estimation_problem;
class rrel_ran_sam_search;
class rrel_ransac_obj;
class rrel_shift2d_est;
class rrel_trunc_quad_obj;
class rrel_tukey_obj;
class rrel_wgted_ran_sam_search;
class rrel_wls_obj;

#endif //rrel_fwd_h_
