USES = vxl
include ${IUEROOT}/vxl/vnl/algo/config.mk

# Examples may use vbl....
include ${IUEROOT}/vxl/vbl/config.mk

MINI_PROG_SOURCES += vnl_calc.cxx

################################
include $(IUEROOT)/config/top.mk
################################
