USES += core
include ${IUEROOT}/core/vnl/algo/config.mk
include ${IUEROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += vnl_calc.cxx

################################
include $(IUEROOT)/config/top.mk
################################
