USES += core

LIBRARY := vpgl-xio
VERSION := 1.0

SOURCES += vpgl_xio_lvcs.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
