USES += contrib/oxl core
include ${IUELOCALROOT}/core/vgui/config.mk
include ${IUELOCALROOT}/contrib/oxl/osl/config.mk

MINI_PROG_SOURCES += satellite.cxx

MINI_PROG_SOURCES += raw-glut1.cxx
MINI_PROG_SOURCES += raw-glut2.cxx
MINI_PROG_SOURCES += slab-glut.cxx

MINI_PROG_SOURCES += display-points.cxx
MINI_PROG_SOURCES += display-canny.cxx
MINI_PROG_SOURCES += display-pyramid.cxx
MINI_PROG_SOURCES += display-images.cxx
MINI_PROG_SOURCES += harris-moments.cxx

MINI_PROG_SOURCES += polygon-scan.cxx

################################
include ${IUEROOT}/config/top.mk
################################
