USES += contrib/gel contrib/oxl core
include ../config.mk

MINI_PROG_SOURCES += dense_matcher_full.cxx
MINI_PROG_SOURCES += make_3d_output.cxx

################################
include ${IUEROOT}/config/top.mk
################################
