USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := icam_pro
VERSION := 1.0

MANPAGE_SOURCES += icam_processes.h
SOURCES += icam_register.cxx

SOURCES += processes/icam_create_view_sphere_process.cxx
SOURCES += processes/icam_register_image_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
