USES += vxl gel
include ${IUEROOT}/vxl/vnl/algo/config.mk

IULIBS := -lvdgl -lvtol -lvsol -lvnl-algo -lvbl -lvnl -lvgl

MINI_PROG_SOURCES += test_vdgl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
