USES += vxl gel
include ${IUEROOT}/vxl/vnl/algo/config.mk
include ${IUEROOT}/vxl/vul/config.mk

IULIBS := -lvtol -lvdgl -lvsol -lvgl-algo -lvgl -lvnl-algo -lvnl -lvbl -lvul

MINI_PROG_SOURCES += test_vdgl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
