USES += contrib/gel core
include $(IUEROOT)/contrib/gel/vtol/config.mk

MINI_PROG_SOURCES += test_vdgl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
