USES += contrib/brl contrib/brl/bbas contrib/gel core

LIBRARY := bsol
VERSION := 1.0

SOURCES += bsol_hough_line_index.cxx

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
