USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_volm_prepare_location_hypotheses.cxx
MINI_PROG_SOURCES += boxm2_volumetric_matcher_compose.cxx
MINI_PROG_SOURCES += boxm2_volumetric_matcher_p0.cxx
MINI_PROG_SOURCES += boxm2_volumetric_matcher_p1.cxx

################################
include ${VXLROOT}/config/top.mk
################################
