USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_volumetric_matcher_exe.cxx
MINI_PROG_SOURCES += boxm2_volm_prepare_location_hypotheses.cxx

################################
include ${VXLROOT}/config/top.mk
################################
