USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_volm_prepare_location_hypotheses.cxx
MINI_PROG_SOURCES += boxm2_volumetric_matcher_p0.cxx
MINI_PROG_SOURCES += boxm2_volumetric_matcher_p1.cxx
MINI_PROG_SOURCES += boxm2_volumetric_render_index_depth_img.cxx
MINI_PROG_SOURCES += boxm2_volumetric_evaluate_roi.cxx
MINI_PROG_SOURCES += boxm2_volumetric_create_prob_map.cxx
MINI_PROG_SOURCES += boxm2_volumetric_evaluate_roi_max_score.cxx

################################
include ${VXLROOT}/config/top.mk
################################
