USES += contrib/brl contrib/gel contrib/brl/bbas core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTS += test_hough_index.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
