USES += contrib/gel core

LIBRARY := vpgl-xio
VERSION := 1.0

MANPAGE_SOURCES += vpgl_xio_calibration_matrix.txx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
#SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
