SUBDIRS := ouel ouml
MANPAGE_SOURCES += oul_copyright.h

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifeq ($(OS),"Linux2")
SUBDIRS += oufgl 
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
