SUBDIRS := ouel ouml

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifeq ($(OS),"Linux2")
SUBDIRS += oufgl 
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
