USES += core
include ../config.mk
include ${VXLROOT}/core/vul/config.mk # vul_timer used
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN = test_driver.cxx
SOURCES += test_util.cxx
TESTS += test_fft.cxx
TESTS += test_fft1d.cxx
TESTS += test_fft2d.cxx
TESTS += test_rnpoly_roots.cxx
TESTS += test_sparse_matrix.cxx
TESTS += test_qsvd.cxx
TESTS += test_functions.cxx
TESTS += test_rpoly_roots.cxx
TESTS += test_cpoly_roots.cxx
TESTS += test_determinant.cxx
TESTS += test_rank.cxx
TESTS += test_qr.cxx
TESTS += test_svd.cxx
TESTS += test_real_eigensystem.cxx
TESTS += test_complex_eigensystem.cxx
TESTS += test_symmetric_eigensystem.cxx
TESTS += test_generalized_eigensystem.cxx
TESTS += test_levenberg_marquardt.cxx
TESTS += test_minimizers.cxx
TESTS += test_convolve.cxx
TESTS += test_amoeba.cxx
TESTS += test_cholesky.cxx
TESTS += test_algo.cxx
TESTS += test_integral.cxx
TESTS += test_powell.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
