USES += core

LIBRARY := vgl-algo
VERSION := 1.0
IMMEDIATE_LIBS := -lvnl-algo -lvnl

SOURCES += vgl_algo.cxx # need at least one file for SunPro
MANPAGE_SOURCES += vgl_rtree.txx
MANPAGE_SOURCES += vgl_homg_operators_1d.txx
MANPAGE_SOURCES += vgl_homg_operators_2d.txx
MANPAGE_SOURCES += vgl_homg_operators_3d.txx

################################
include ${IUEROOT}/config/top.mk
################################
