USES += core

LIBRARY := vgl-algo
VERSION := 1.0
IMMEDIATE_LIBS := -lvnl-algo -lvnl

MANPAGE_SOURCES += vgl_algo_fwd.h
MANPAGE_SOURCES += vgl_rtree.txx
MANPAGE_SOURCES += vgl_orient_box_3d.txx
MANPAGE_SOURCES += vgl_homg_operators_1d.txx
MANPAGE_SOURCES += vgl_homg_operators_2d.txx
MANPAGE_SOURCES += vgl_homg_operators_3d.txx
MANPAGE_SOURCES += vgl_h_matrix_1d.txx
MANPAGE_SOURCES += vgl_h_matrix_2d.txx
MANPAGE_SOURCES += vgl_h_matrix_3d.txx
MANPAGE_SOURCES += vgl_p_matrix.txx
MANPAGE_SOURCES += vgl_norm_trans_2d.txx
MANPAGE_SOURCES += vgl_norm_trans_3d.txx
MANPAGE_SOURCES += vgl_h_matrix_1d_compute.h
SOURCES += vgl_h_matrix_1d_compute_3point.cxx
SOURCES += vgl_h_matrix_1d_compute_linear.cxx
SOURCES += vgl_h_matrix_1d_compute_optimize.cxx
MANPAGE_SOURCES += vgl_h_matrix_2d_compute.h
SOURCES += vgl_h_matrix_2d_compute_4point.cxx
SOURCES += vgl_h_matrix_2d_compute_linear.cxx
MANPAGE_SOURCES += vgl_h_matrix_2d_optimize.h
SOURCES += vgl_h_matrix_2d_optimize_lmq.cxx
MANPAGE_SOURCES += vgl_fit_lines_2d.txx
MANPAGE_SOURCES += vgl_line_2d_regression.txx
MANPAGE_SOURCES += vgl_convex_hull_2d.txx
MANPAGE_SOURCES += vgl_conic_2d_regression.txx
MANPAGE_SOURCES += vgl_fit_conics_2d.txx

################################
include ${VXLROOT}/config/top.mk
################################
