USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += vidl2_player_main.cxx
MINI_PROG_SOURCES += vidl2_player_manager.cxx
MINI_PROG_SOURCES += vidl2_player_menus.cxx
MINI_PROG_SOURCES += vidl2_dshow_file_example.cxx
MINI_PROG_SOURCES += vidl2_dshow_live_example.cxx
MINI_PROG_SOURCES += vidl2_v4l_live_example.cxx

################################
include ${VXLROOT}/config/top.mk
################################
