USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += vidl2_player_main.cxx
MINI_PROG_SOURCES += vidl2_player_manager.cxx
MINI_PROG_SOURCES += vidl2_player_menus.cxx

################################
include ${VXLROOT}/config/top.mk
################################
