//#include <bpgl/algo/bpgl_adjust_rational_trans_onept.h>
//#include <bpgl/algo/bpgl_ba_fixed_k_lsqr.h>
//#include <bpgl/algo/bpgl_ba_shared_k_lsqr.h>
//#include <bpgl/algo/bpgl_backproject.h>
//#include <bpgl/algo/bpgl_bundle_adjust.h>
//#include <bpgl/algo/bpgl_bundle_adjust_lsqr.h>
#include <bpgl/algo/bpgl_bundle_rolling_shutter_adjust.h>
//#include <bpgl/algo/bpgl_camera_bounds.h>
//#include <bpgl/algo/bpgl_camera_compute.h>
#include <bpgl/algo/bpgl_camera_from_box.h>
#include <bpgl/algo/bpgl_camera_homographies.h>
#include <bpgl/algo/bpgl_construct_cameras.h>
//#include <bpgl/algo/bpgl_em_compute_5_point.h>
//#include <bpgl/algo/bpgl_fm_compute_2_point.h>
//#include <bpgl/algo/bpgl_fm_compute_7_point.h>
//#include <bpgl/algo/bpgl_fm_compute_8_point.h>
#include <bpgl/algo/bpgl_fm_compute_affine_ransac.h>
#include <bpgl/algo/bpgl_fm_compute_ransac.h>
#include <bpgl/algo/bpgl_fm_compute_reg_ransac.h>
#include <bpgl/algo/bpgl_interpolate.h>
//#include <bpgl/algo/bpgl_invmap_cost_function.h>
#include <bpgl/algo/bpgl_list.h>
#include <bpgl/algo/bpgl_nitf_camera_coverage.h>
//#include <bpgl/algo/bpgl_optimize_camera.h>
//#include <bpgl/algo/bpgl_ortho_procrustes.h>
//#include <bpgl/algo/bpgl_rational_geo_adjust.h>
//#include <bpgl/algo/bpgl_ray.h>
//#include <bpgl/algo/bpgl_ray_intersect.h>
//#include <bpgl/algo/bpgl_triangulate_points.h>
#include <bpgl/algo/bpgl_vsol_lens_warp.h>
#include <bpgl/algo/bpgl_project.h>
#include <bpgl/algo/bpgl_transform_camera.h>

int main() { return 0; }
