USES += contrib/brl contrib/brl/bseg core

LIBRARY := breg3d_pro
VERSION := 1.0

SOURCES += breg3d_set_occupancy_plane_process.cxx
SOURCES += breg3d_ekf_camera_optimize_process.cxx
SOURCES += breg3d_init_ekf_camera_optimizer_process.cxx
SOURCES += breg3d_zero_occupancy_borders_process.cxx
SOURCES += breg3d_init_ekf_camera_optimizer_planar_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
