SOURCES += icam_sample.cxx
SOURCES += icam_view_metadata.cxx
SOURCES += icam_view_sphere.cxx
SOURCES += icam_cost_func.cxx
SOURCES += icam_depth_transform.cxx
SOURCES += icam_minimizer.cxx
SOURCES += icam_depth_trans_pyramid.cxx
SOURCES += icam_utils.cxx
SOURCES += icam_transform_2d.cxx
MANPAGE_SOURCES += icam_image.h

SUBDIRS += tests
