USES += contrib/gel core

LIBRARY := vgel_kl

SOURCES += convolve.c
SOURCES += klt.c
SOURCES += pnmio.c
SOURCES += selectGoodFeatures.c
SOURCES += trackFeatures.c
SOURCES += error.c
SOURCES += klt_util.c
SOURCES += pyramid.c
SOURCES += storeFeatures.c
SOURCES += writeFeatures.c
MANPAGE_SOURCES += base.h

################################
include ${IUEROOT}/config/top.mk
################################
