USES += core contrib/brl contrib/brl/bbas
include ../config.mk

TESTS += test_legendre_polynomial.cxx
TESTS += test_integral.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
