#include <vil/algo/vil_binary_closing.h>
#include <vil/algo/vil_binary_dilate.h>
#include <vil/algo/vil_binary_erode.h>
#include <vil/algo/vil_binary_opening.h>
#include <vil/algo/vil_blob_finder.h>
#include <vil/algo/vil_cartesian_differential_invariants.h>
#include <vil/algo/vil_convolve_1d.h>
#include <vil/algo/vil_convolve_2d.h>
#include <vil/algo/vil_corners.h>
#include <vil/algo/vil_correlate_1d.h>
#include <vil/algo/vil_correlate_2d.h>
#include <vil/algo/vil_distance_transform.h>
#include <vil/algo/vil_dog_filter_5tap.h>
#include <vil/algo/vil_dog_pyramid.h>
#include <vil/algo/vil_exp_filter_1d.h>
#include <vil/algo/vil_exp_filter_2d.h>
#include <vil/algo/vil_exp_grad_filter_1d.h>
#include <vil/algo/vil_find_4con_boundary.h>
#include <vil/algo/vil_find_peaks.h>
#include <vil/algo/vil_fft.h>
#include <vil/algo/vil_gauss_filter.h>
#include <vil/algo/vil_gauss_reduce.h>
#include <vil/algo/vil_greyscale_closing.h>
#include <vil/algo/vil_greyscale_dilate.h>
#include <vil/algo/vil_greyscale_erode.h>
#include <vil/algo/vil_greyscale_opening.h>
#include <vil/algo/vil_grid_merge.h>
#include <vil/algo/vil_histogram.h>
#include <vil/algo/vil_histogram_equalise.h>
#include <vil/algo/vil_line_filter.h>
#include <vil/algo/vil_median.h>
#include <vil/algo/vil_normalised_correlation_2d.h>
#include <vil/algo/vil_region_finder.h>
#include <vil/algo/vil_sobel_1x3.h>
#include <vil/algo/vil_sobel_3x3.h>
#include <vil/algo/vil_structuring_element.h>
#include <vil/algo/vil_suppress_non_max.h>
#include <vil/algo/vil_threshold.h>
#include <vil/algo/vil_trace_4con_boundary.h>
#include <vil/algo/vil_trace_8con_boundary.h>
#include <vil/vil_bicub_interp.h>
#include <vil/vil_bilin_interp.h>
#include <vil/vil_clamp.h>
#include <vil/vil_convert.h>
#include <vil/vil_copy.h>
#include <vil/vil_crop.h>
#include <vil/vil_decimate.h>
#include <vil/vil_file_format.h>
#include <vil/vil_fill.h>
#include <vil/vil_flip.h>
#include <vil/vil_fwd.h>
#include <vil/vil_image_resource.h>
#include <vil/vil_image_resource_plugin.h>
#include <vil/vil_image_view.h>
#include <vil/vil_image_view_base.h>
#include <vil/vil_load.h>
#include <vil/vil_math.h>
#include <vil/vil_memory_chunk.h>
#include <vil/vil_memory_image.h>
#include <vil/vil_new.h>
#include <vil/vil_open.h>
#include <vil/vil_pixel_format.h>
#include <vil/vil_pixel_traits.h>
#include <vil/vil_plane.h>
#include <vil/vil_print.h>
#include <vil/vil_property.h>
#include <vil/vil_resample_bicub.h>
#include <vil/vil_resample_bilin.h>
#include <vil/vil_rgb.h>
#include <vil/vil_rgba.h>
#include <vil/vil_rotate.h>
#include <vil/vil_sample_grid_bicub.h>
#include <vil/vil_sample_grid_bilin.h>
#include <vil/vil_sample_profile_bicub.h>
#include <vil/vil_sample_profile_bilin.h>
#include <vil/vil_save.h>
#include <vil/vil_smart_ptr.h>
#include <vil/vil_stream.h>
#include <vil/vil_stream_read.h>
#include <vil/vil_stream_write.h>
#include <vil/vil_stream_core.h>
#include <vil/vil_stream_fstream.h>
#include <vil/vil_stream_section.h>
#include <vil/vil_stream_url.h>
#include <vil/vil_transform.h>
#include <vil/vil_transpose.h>
#include <vil/vil_view_as.h>

int main() { return 0; }
