#include <vil/vil_bicub_interp.h>
#include <vil/vil_bilin_interp.h>
#include <vil/vil_clamp.h>
#include <vil/vil_convert.h>
#include <vil/vil_copy.h>
#include <vil/vil_crop.h>
#include <vil/vil_decimate.h>
#include <vil/vil_exception.h>
#include <vil/vil_file_format.h>
#include <vil/vil_fill.h>
#include <vil/vil_flip.h>
#include <vil/vil_fwd.h>
#include <vil/vil_image_resource_sptr.h>
#include <vil/vil_image_resource.h>
#include <vil/vil_image_resource_plugin.h>
#include <vil/vil_image_view.h>
#include <vil/vil_image_view_base.h>
#include <vil/vil_load.h>
#include <vil/vil_math.h>
#include <vil/vil_memory_chunk.h>
#include <vil/vil_memory_image.h>
#include <vil/vil_nearest_neighbour_interp.h>
#include <vil/vil_new.h>
#include <vil/vil_open.h>
#include <vil/vil_pixel_format.h>
#include <vil/vil_pixel_traits.h>
#include <vil/vil_plane.h>
#include <vil/vil_print.h>
#include <vil/vil_property.h>
#include <vil/vil_resample_bicub.h>
#include <vil/vil_resample_bilin.h>
#include <vil/vil_rgb.h>
#include <vil/vil_rgba.h>
#include <vil/vil_rotate.h>
#include <vil/vil_sample_grid_bicub.h>
#include <vil/vil_sample_grid_bilin.h>
#include <vil/vil_sample_profile_bicub.h>
#include <vil/vil_sample_profile_bilin.h>
#include <vil/vil_save.h>
#include <vil/vil_smart_ptr.h>
#include <vil/vil_stream.h>
#include <vil/vil_stream_read.h>
#include <vil/vil_stream_write.h>
#include <vil/vil_stream_core.h>
#include <vil/vil_stream_fstream.h>
#include <vil/vil_stream_section.h>
#include <vil/vil_stream_url.h>
#include <vil/vil_transform.h>
#include <vil/vil_transpose.h>
#include <vil/vil_view_as.h>
#include <vil/vil_warp.h>

int main() { return 0; }
