#include <vil2/algo/vil2_binary_closing.h>
#include <vil2/algo/vil2_binary_dilate.h>
#include <vil2/algo/vil2_binary_erode.h>
#include <vil2/algo/vil2_binary_opening.h>
#include <vil2/algo/vil2_convolve_1d.h>
#include <vil2/algo/vil2_convolve_2d.h>
#include <vil2/algo/vil2_correlate_1d.h>
#include <vil2/algo/vil2_correlate_2d.h>
#include <vil2/algo/vil2_exp_filter_1d.h>
#include <vil2/algo/vil2_exp_grad_filter_1d.h>
#include <vil2/algo/vil2_find_4con_boundary.h>
#include <vil2/algo/vil2_gauss_filter.h>
#include <vil2/algo/vil2_gauss_reduce.h>
#include <vil2/algo/vil2_greyscale_closing.h>
#include <vil2/algo/vil2_greyscale_dilate.h>
#include <vil2/algo/vil2_greyscale_erode.h>
#include <vil2/algo/vil2_greyscale_opening.h>
#include <vil2/algo/vil2_grid_merge.h>
#include <vil2/algo/vil2_line_filter.h>
#include <vil2/algo/vil2_median.h>
#include <vil2/algo/vil2_normalised_correlation_2d.h>
#include <vil2/algo/vil2_sobel_1x3.h>
#include <vil2/algo/vil2_sobel_3x3.h>
#include <vil2/algo/vil2_structuring_element.h>
#include <vil2/algo/vil2_threshold.h>
#include <vil2/vil2_bilin_interp.h>
#include <vil2/vil2_clamp.h>
#include <vil2/vil2_convert.h>
#include <vil2/vil2_copy.h>
#include <vil2/vil2_crop.h>
#include <vil2/vil2_decimate.h>
#include <vil2/vil2_file_format.h>
#include <vil2/vil2_fill.h>
#include <vil2/vil2_flip.h>
#include <vil2/vil2_fwd.h>
#include <vil2/vil2_image_resource.h>
#include <vil2/vil2_image_resource_plugin.h>
#include <vil2/vil2_image_view.h>
#include <vil2/vil2_image_view_base.h>
#include <vil2/vil2_load.h>
#include <vil2/vil2_math.h>
#include <vil2/vil2_memory_chunk.h>
#include <vil2/vil2_memory_image.h>
#include <vil2/vil2_new.h>
#include <vil2/vil2_open.h>
#include <vil2/vil2_pixel_format.h>
#include <vil2/vil2_pixel_traits.h>
#include <vil2/vil2_plane.h>
#include <vil2/vil2_print.h>
#include <vil2/vil2_property.h>
#include <vil2/vil2_resample_bilin.h>
#include <vil2/vil2_rgb.h>
#include <vil2/vil2_rgba.h>
#include <vil2/vil2_sample_grid_bilin.h>
#include <vil2/vil2_sample_profile_bilin.h>
#include <vil2/vil2_save.h>
#include <vil2/vil2_smart_ptr.h>
#include <vil2/vil2_stream.h>
#include <vil2/vil2_stream_16bit.h>
#include <vil2/vil2_stream_32bit.h>
#include <vil2/vil2_stream_core.h>
#include <vil2/vil2_stream_fstream.h>
#include <vil2/vil2_stream_section.h>
#include <vil2/vil2_stream_url.h>
#include <vil2/vil2_transform.h>
#include <vil2/vil2_transpose.h>
#include <vil2/vil2_view_as.h>
#include <vil2/vil2_vil1.h>

int main() { return 0; }
