USES += contrib/brl contrib/brl/bbas core
include ../config.mk

TESTMAIN := test_driver.cxx

TESTS += test_generate_mesh.cxx

MINI_PROG_SOURCES += test_include.cxx
MINI_PROG_SOURCES += test_template_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
