USES += contrib/brl
USE_MPEG2 := 1
include ${IUELOCALROOT}/core/vidl_vil1/config.mk
include ${IUELOCALROOT}/core/vil1/config.mk
include ${IUELOCALROOT}/core/vul/config.mk

MINI_PROG_SOURCES += frame_extractor.cxx
MINI_PROG_SOURCES += video_description.cxx

################################
include ${IUEROOT}/config/top.mk
################################
