USES += contrib/brl contrib/brl/bseg
include ${IUELOCALROOT}/core/vul/config.mk
include ${IUELOCALROOT}/core/vidl/config.mk
include ${IUELOCALROOT}/core/vil/algo/config.mk

MINI_PROG_SOURCES += frame_extractor.cxx
MINI_PROG_SOURCES += video_description.cxx
MINI_PROG_SOURCES += motion_test.cxx

################################
include ${IUEROOT}/config/top.mk
################################
