USES += contrib/brl contrib/brl/bbas core

LIBRARY := brad-io
VERSION := 1.0

SOURCES += brad_io_image_metadata.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
