USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm_opencl_render_expected_process_exe.cxx

################################
include ${VXLROOT}/config/top.mk
################################
