USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm_opencl_render_expected_process_exe.cxx
MINI_PROG_SOURCES += boxm_opencl_render_ocl_scene_exe.cxx
MINI_PROG_SOURCES += boxm_ocl_update_view.cxx
MINI_PROG_SOURCES += boxm_ocl_render_view.cxx
MINI_PROG_SOURCES += boxm_opencl_change_detection_view.cxx
MINI_PROG_SOURCES += boxm_build_foreground_distribution.cxx
MINI_PROG_SOURCES += boxm_ocl_rerender_view.cxx
MINI_PROG_SOURCES += boxm_ocl_rerender_adjacent_frames.cxx
MINI_PROG_SOURCES += boxm_ocl_render_bit_view.cxx

################################
include ${VXLROOT}/config/top.mk
################################
