USES += contrib/brl contrib/brl/bseg core

LIBRARY := volm_io

SOURCES += boxm2_volm_io_locations.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
