USES += contrib/brl contrib/brl/bbas core

LIBRARY := bpgl_algo_examples
VERSION := 1.0

MINI_PROG_SOURCES += bpgl_synth_bundle_adjust.cxx

################################
include ${VXLROOT}/config/top.mk
################################
