#include <vil3d/algo/vil3d_abs_shuffle_distance.h>
#include <vil3d/algo/vil3d_anisotropic_filter.h>
#include <vil3d/algo/vil3d_binary_closing.h>
#include <vil3d/algo/vil3d_binary_dilate.h>
#include <vil3d/algo/vil3d_binary_erode.h>
#include <vil3d/algo/vil3d_binary_opening.h>
#include <vil3d/algo/vil3d_convolve_1d.h>
#include <vil3d/algo/vil3d_corners.h>
#include <vil3d/algo/vil3d_distance_transform.h>
#include <vil3d/algo/vil3d_erode.h>
#include <vil3d/algo/vil3d_exp_distance_transform.h>
#include <vil3d/algo/vil3d_exp_filter.h>
#include <vil3d/algo/vil3d_fill_border.h>
#include <vil3d/algo/vil3d_fill_boundary.h>
#include <vil3d/algo/vil3d_find_blobs.h>
#include <vil3d/algo/vil3d_find_peaks.h>
#include <vil3d/algo/vil3d_gauss_reduce.h>
#include <vil3d/algo/vil3d_grad_1x3.h>
#include <vil3d/algo/vil3d_grad_3x3x3.h>
#include <vil3d/algo/vil3d_histogram.h>
#include <vil3d/algo/vil3d_histogram_equalise.h>
#include <vil3d/algo/vil3d_locally_z_normalise.h>
#include <vil3d/algo/vil3d_make_distance_filter.h>
#include <vil3d/algo/vil3d_make_edt_filter.h>
#include <vil3d/algo/vil3d_max_product_filter.h>
#include <vil3d/algo/vil3d_normalised_correlation_3d.h>
#include <vil3d/algo/vil3d_overlap.h>
#include <vil3d/algo/vil3d_quad_distance_function.h>
#include <vil3d/algo/vil3d_smooth_121.h>
#include <vil3d/algo/vil3d_structuring_element.h>
#include <vil3d/algo/vil3d_suppress_non_max_edges.h>
#include <vil3d/algo/vil3d_threshold.h>
#include <vil3d/algo/vil3d_world_gradients.h>

int main() { return 0; }
