USES += contrib/gel contrib/brl contrib/brl/bseg core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
SOURCES += test_ifa_factory.cxx

TESTS += test_coll_lines_params.cxx
TESTS += test_group_pgram_params.cxx
TESTS += test_image_histogram.cxx
TESTS += test_int_face_attr.cxx
TESTS += test_int_face_attr_common_params.cxx
TESTS += test_int_faces_adj_attr.cxx
TESTS += test_int_faces_attr.cxx
TESTS += test_norm_params.cxx
TESTS += test_parallel_params.cxx
TESTS += test_region_proc.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
