#include <vcsl/vcsl_angle.h>
#include <vcsl/vcsl_angle_sptr.h>
#include <vcsl/vcsl_angle_unit.h>
#include <vcsl/vcsl_angle_unit_sptr.h>
#include <vcsl/vcsl_axis.h>
#include <vcsl/vcsl_axis_sptr.h>
#include <vcsl/vcsl_cartesian.h>
#include <vcsl/vcsl_cartesian_2d.h>
#include <vcsl/vcsl_cartesian_2d_sptr.h>
#include <vcsl/vcsl_cartesian_3d.h>
#include <vcsl/vcsl_cartesian_3d_sptr.h>
#include <vcsl/vcsl_cartesian_sptr.h>
#include <vcsl/vcsl_composition.h>
#include <vcsl/vcsl_composition_sptr.h>
#include <vcsl/vcsl_coordinate_system.h>
#include <vcsl/vcsl_coordinate_system_sptr.h>
#include <vcsl/vcsl_cylindrical.h>
#include <vcsl/vcsl_cylindrical_sptr.h>
#include <vcsl/vcsl_cylindrical_to_cartesian_3d.h>
#include <vcsl/vcsl_cylindrical_to_cartesian_3d_sptr.h>
#include <vcsl/vcsl_degree.h>
#include <vcsl/vcsl_degree_sptr.h>
#include <vcsl/vcsl_dimension.h>
#include <vcsl/vcsl_dimension_sptr.h>
#include <vcsl/vcsl_displacement.h>
#include <vcsl/vcsl_displacement_sptr.h>
#include <vcsl/vcsl_geocentric.h>
#include <vcsl/vcsl_geocentric_sptr.h>
#include <vcsl/vcsl_geodetic.h>
#include <vcsl/vcsl_geodetic_sptr.h>
#include <vcsl/vcsl_geographic.h>
#include <vcsl/vcsl_geographic_sptr.h>
#include <vcsl/vcsl_graph.h>
#include <vcsl/vcsl_graph_sptr.h>
#include <vcsl/vcsl_lambertian.h>
#include <vcsl/vcsl_lambertian_sptr.h>
#include <vcsl/vcsl_length.h>
#include <vcsl/vcsl_length_sptr.h>
#include <vcsl/vcsl_length_unit.h>
#include <vcsl/vcsl_length_unit_sptr.h>
#include <vcsl/vcsl_matrix.h>
#include <vcsl/vcsl_matrix_param.h>
#include <vcsl/vcsl_matrix_param_sptr.h>
#include <vcsl/vcsl_matrix_sptr.h>
#include <vcsl/vcsl_meter.h>
#include <vcsl/vcsl_meter_sptr.h>
#include <vcsl/vcsl_micron.h>
#include <vcsl/vcsl_micron_sptr.h>
#include <vcsl/vcsl_millimeter.h>
#include <vcsl/vcsl_millimeter_sptr.h>
#include <vcsl/vcsl_perspective.h>
#include <vcsl/vcsl_perspective_sptr.h>
#include <vcsl/vcsl_polar.h>
#include <vcsl/vcsl_polar_sptr.h>
#include <vcsl/vcsl_radian.h>
#include <vcsl/vcsl_radian_sptr.h>
#include <vcsl/vcsl_rotation.h>
#include <vcsl/vcsl_rotation_sptr.h>
#include <vcsl/vcsl_scale.h>
#include <vcsl/vcsl_scale_sptr.h>
#include <vcsl/vcsl_spatial.h>
#include <vcsl/vcsl_spatial_sptr.h>
#include <vcsl/vcsl_spatial_transformation.h>
#include <vcsl/vcsl_spatial_transformation_sptr.h>
#include <vcsl/vcsl_spherical.h>
#include <vcsl/vcsl_spherical_sptr.h>
#include <vcsl/vcsl_spheroid.h>
#include <vcsl/vcsl_spheroid_sptr.h>
#include <vcsl/vcsl_translation.h>
#include <vcsl/vcsl_translation_sptr.h>
#include <vcsl/vcsl_unit.h>
#include <vcsl/vcsl_unit_sptr.h>
#include <vcsl/vcsl_utm.h>
#include <vcsl/vcsl_utm_sptr.h>

int main() { return 0; }
