USES = # nothing
USE_STDC++ := 0

LIBRARY := NCScnet2

MANPAGE_SOURCES += NCSWinHttp.h
MANPAGE_SOURCES += cnet.h

SUBDIRS += ../../NCSUtil

################################
include ${VXLROOT}/config/top.mk
################################
