USES += contrib/brl core

LIBRARY := bmsh3d_pro
VERSION := 1.0

SOURCES += bmsh3d_cmdpara.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
