USES += contrib/mul core

LIBRARY := vil3d-algo
VERSION := 1.0

MANPAGE_SOURCES += vil3d_gauss_reduce.h
SOURCES += vil3d_grad_1x3.cxx
MANPAGE_SOURCES += vil3d_grad_1x3.txx
MANPAGE_SOURCES += vil3d_threshold.txx
SOURCES += vil3d_binary_dilate.cxx
SOURCES += vil3d_binary_erode.cxx
MANPAGE_SOURCES += vil3d_binary_closing.h
MANPAGE_SOURCES += vil3d_binary_opening.h
SOURCES += vil3d_structuring_element.cxx
MANPAGE_SOURCES += vil3d_exp_filter.h
MANPAGE_SOURCES += vil3d_normalised_correlation_3d.h
MANPAGE_SOURCES += vil3d_convolve_1d.h
SOURCES += vil3d_histogram.cxx
SOURCES += vil3d_histogram_equalise.cxx
SOURCES += vil3d_distance_transform.cxx
SOURCES += vil3d_fill_boundary.cxx
MANPAGE_SOURCES += vil3d_anisotropic_filter.h
MANPAGE_SOURCES += vil3d_gauss_reduce.txx
MANPAGE_SOURCES += vil3d_corners.txx
MANPAGE_SOURCES += vil3d_find_peaks.h
MANPAGE_SOURCES += vil3d_grad_3x3x3.h
MANPAGE_SOURCES += vil3d_quad_distance_function.h
MANPAGE_SOURCES += vil3d_abs_shuffle_distance.txx
MANPAGE_SOURCES += vil3d_smooth_121.h
MANPAGE_SOURCES += vil3d_exp_distance_transform.h
MANPAGE_SOURCES += vil3d_max_product_filter.h
SOURCES += vil3d_make_distance_filter.cxx
SOURCES += vil3d_make_edt_filter.cxx
SOURCES += vil3d_overlap.cxx
MANPAGE_SOURCES += vil3d_locally_z_normalise.h
SOURCES += vil3d_find_blobs.cxx

################################
include ${VXLROOT}/config/top.mk
################################
