USES += contrib/mul core

LIBRARY := vil3d-algo
VERSION := 1.0

MANPAGE_SOURCES += vil3d_gauss_reduce.h
SOURCES += vil3d_grad_1x3.cxx
MANPAGE_SOURCES += vil3d_grad_1x3.txx
MANPAGE_SOURCES += vil3d_threshold.txx

################################
include ${IUEROOT}/config/top.mk
################################
