USES += contrib/mul core

LIBRARY := vil3d-algo
VERSION := 1.0

MANPAGE_SOURCES += vil3d_gauss_reduce.h
SOURCES += vil3d_grad_1x3.cxx
MANPAGE_SOURCES += vil3d_grad_1x3.txx
MANPAGE_SOURCES += vil3d_threshold.txx
SOURCES += vil3d_binary_dilate.cxx
SOURCES += vil3d_binary_erode.cxx
MANPAGE_SOURCES += vil3d_binary_closing.h
MANPAGE_SOURCES += vil3d_binary_opening.h
SOURCES += vil3d_structuring_element.cxx
MANPAGE_SOURCES += vil3d_exp_filter.h

################################
include ${IUEROOT}/config/top.mk
################################
