USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_kernels_io

SOURCES += bvpl_io_kernel.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
