USES := vxl mul

LIBRARY := vil2-algo
VERSION := 1.0

SOURCES += vil2_algo_sobel_3x3.cxx
MANPAGE_SOURCES += vil2_algo_sobel_3x3.txx

################################
include ${IUEROOT}/config/top.mk
################################
