USES := vxl mul

LIBRARY := vil2-algo
VERSION := 1.0

SOURCES += vil2_sobel_3x3.cxx
MANPAGE_SOURCES += vil2_sobel_3x3.txx
SOURCES += vil2_gauss_reduce.cxx
MANPAGE_SOURCES += vil2_gauss_reduce.txx
MANPAGE_SOURCES += vil2_convolve_1d.h
MANPAGE_SOURCES += vil2_convolve_2d.h
MANPAGE_SOURCES += vil2_exp_filter_1d.h
SOURCES += vil2_binary_erode.cxx
SOURCES += vil2_binary_dilate.cxx
SOURCES += vil2_structuring_element.cxx

################################
include ${IUEROOT}/config/top.mk
################################
