USES += contrib/brl contrib/gel contrib/brl/bbas contrib/brl/bseg core
include ../sdet/config.mk

TESTS += sdet_test_detector.cxx
TESTS += sdet_test_region_proc.cxx

PARAMS_sdet_test_detector := jar-closeup.tif
PARAMS_sdet_test_region_proc := jar-closeup.tif

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
