USES += contrib/brl contrib/gel contrib/brl/bbas contrib/brl/bseg core
include ${IUEROOT}/contrib/brl/bseg/sdet/config.mk

TESTS += sdet_test_detector.cxx
TESTS += sdet_test_region_proc.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
