#include <bseg/bmrf/bmrf_arc.h>
#include <bseg/bmrf/bmrf_arc_sptr.h>
#include <bseg/bmrf/bmrf_curve_3d_builder.h>
#include <bseg/bmrf/bmrf_curvel_3d.h>
#include <bseg/bmrf/bmrf_curvel_3d_sptr.h>
#include <bseg/bmrf/bmrf_epi_point.h>
#include <bseg/bmrf/bmrf_epi_point_sptr.h>
#include <bseg/bmrf/bmrf_epi_seg.h>
#include <bseg/bmrf/bmrf_epi_seg_compare.h>
#include <bseg/bmrf/bmrf_epi_seg_sptr.h>
#include <bseg/bmrf/bmrf_epi_transform.h>
#include <bseg/bmrf/bmrf_epipole.h>
#include <bseg/bmrf/bmrf_gamma_func.h>
#include <bseg/bmrf/bmrf_gamma_func_sptr.h>
#include <bseg/bmrf/bmrf_network.h>
#include <bseg/bmrf/bmrf_network_builder.h>
#include <bseg/bmrf/bmrf_network_builder_params.h>
#include <bseg/bmrf/bmrf_network_sptr.h>
#include <bseg/bmrf/bmrf_node.h>
#include <bseg/bmrf/bmrf_node_sptr.h>

#include <bseg/brip/brip_histogram.h>
#include <bseg/brip/brip_mutual_info.h>
#include <bseg/brip/brip_para_cvrg.h>
#include <bseg/brip/brip_para_cvrg_params.h>
#include <bseg/brip/brip_region_pixel.h>
#include <bseg/brip/brip_region_pixel_sptr.h>
#include <bseg/brip/brip_roi.h>
#include <bseg/brip/brip_roi_sptr.h>
#include <bseg/brip/brip_vil1_float_ops.h>
#include <bseg/brip/brip_vil_float_ops.h>
#include <bseg/brip/brip_vil_ops.h>
#include <bseg/brip/brip_watershed.h>
#include <bseg/brip/brip_watershed_params.h>

#include <bseg/sdet/sdet_contour.h>
#include <bseg/sdet/sdet_detector.h>
#include <bseg/sdet/sdet_detector_params.h>
#include <bseg/sdet/sdet_edge_champher.h>
#include <bseg/sdet/sdet_edgel_regions.h>
#include <bseg/sdet/sdet_fit_lines.h>
#include <bseg/sdet/sdet_fit_lines_params.h>
#include <bseg/sdet/sdet_grid_finder.h>
#include <bseg/sdet/sdet_grid_finder_params.h>
#include <bseg/sdet/sdet_harris_detector.h>
#include <bseg/sdet/sdet_harris_detector_params.h>
#include <bseg/sdet/sdet_region.h>
#include <bseg/sdet/sdet_region_edge.h>
#include <bseg/sdet/sdet_region_edge_sptr.h>
#include <bseg/sdet/sdet_region_proc.h>
#include <bseg/sdet/sdet_region_proc_params.h>
#include <bseg/sdet/sdet_region_sptr.h>
#include <bseg/sdet/sdet_vehicle_finder.h>
#include <bseg/sdet/sdet_vehicle_finder_params.h>
#include <bseg/sdet/sdet_watershed_region_proc.h>
#include <bseg/sdet/sdet_watershed_region_proc_params.h>

#include <bseg/segv/segv_menus.h>
#include <bseg/segv/segv_segmentation_manager.h>
#include <bseg/segv/segv_vtol2D_tableau.h>
#include <bseg/segv/segv_vtol2D_tableau_sptr.h>
#include <bseg/segv/segv_vtol_soview2D.h>

#include <bseg/strk/strk_art_info_model.h>
#include <bseg/strk/strk_art_info_model_sptr.h>
#include <bseg/strk/strk_art_model_display_process.h>
#include <bseg/strk/strk_corr_tracker_process.h>
#include <bseg/strk/strk_epi_point.h>
#include <bseg/strk/strk_epi_point_sptr.h>
#include <bseg/strk/strk_epi_seg.h>
#include <bseg/strk/strk_epi_seg_sptr.h>
#include <bseg/strk/strk_epipolar_grouper.h>
#include <bseg/strk/strk_epipolar_grouper_params.h>
#include <bseg/strk/strk_epipolar_grouper_process.h>
#include <bseg/strk/strk_info_model_tracker.h>
#include <bseg/strk/strk_info_model_tracker_params.h>
#include <bseg/strk/strk_info_model_tracker_process.h>
#include <bseg/strk/strk_info_tracker.h>
#include <bseg/strk/strk_info_tracker_params.h>
#include <bseg/strk/strk_info_tracker_process.h>
#include <bseg/strk/strk_region_info.h>
#include <bseg/strk/strk_region_info_params.h>
#include <bseg/strk/strk_track_display_process.h>
#include <bseg/strk/strk_tracker.h>
#include <bseg/strk/strk_tracker_params.h>
#include <bseg/strk/strk_tracking_face_2d.h>
#include <bseg/strk/strk_tracking_face_2d_sptr.h>

#include <bseg/vpro/vpro_basis_generator_process.h>
#include <bseg/vpro/vpro_capture_process.h>
#include <bseg/vpro/vpro_edge_line_process.h>
#include <bseg/vpro/vpro_edge_process.h>
#include <bseg/vpro/vpro_epipolar_space_process.h>
#include <bseg/vpro/vpro_fourier_params.h>
#include <bseg/vpro/vpro_fourier_process.h>
#include <bseg/vpro/vpro_frame_diff_params.h>
#include <bseg/vpro/vpro_frame_diff_process.h>
#include <bseg/vpro/vpro_grid_finder_process.h>
#include <bseg/vpro/vpro_harris_corner_process.h>
#include <bseg/vpro/vpro_ihs_process.h>
#include <bseg/vpro/vpro_line_fit_process.h>
#include <bseg/vpro/vpro_lucas_kanade_process.h>
#include <bseg/vpro/vpro_motion_params.h>
#include <bseg/vpro/vpro_motion_process.h>
#include <bseg/vpro/vpro_region_process.h>
#include <bseg/vpro/vpro_spatial_filter_params.h>
#include <bseg/vpro/vpro_spatial_filter_process.h>
#include <bseg/vpro/vpro_video_process.h>
#include <bseg/vpro/vpro_video_process_sptr.h>

int main() { return 0; }
