USES += core
LIBRARY := vnl-xio
VERSION := 1.0
IMMEDIATE_LIBS := -lvnl-xio -lvnl

MANPAGE_SOURCES += vnl_xio_matrix_fixed.txx
MANPAGE_SOURCES += vnl_xio_quaternion.txx
MANPAGE_SOURCES += vnl_xio_vector.txx
MANPAGE_SOURCES += vnl_xio_vector_fixed.txx

################################
include ${VXLROOT}/config/top.mk
################################
