USES += contrib/mul core
include ../config.mk
include ${IUEROOT}/core/vul/config.mk
include ${IUEROOT}/core/testlib/config.mk

MINI_PROG_SOURCES += example1.cxx
MINI_PROG_SOURCES += example2.cxx
MINI_PROG_SOURCES += example3.cxx
MINI_PROG_SOURCES += example4.cxx
MINI_PROG_SOURCES += make_dog_pyramid.cxx

################################
include ${IUEROOT}/config/top.mk
################################
