USES := # nothing
USE_STDC++ := 0
USE_TIFF := 1

LIBRARY := geotiff
VERSION := 1.0

MANPAGE_SOURCES += tiffio.h

MANPAGE_SOURCES += geo_config.h
MANPAGE_SOURCES += defs.h
MANPAGE_SOURCES += geo_keyp.h
MANPAGE_SOURCES += geokeys.h
MANPAGE_SOURCES += geonames.h
MANPAGE_SOURCES += geotiff.h
MANPAGE_SOURCES += geotiffio.h
MANPAGE_SOURCES += geovalues.h
MANPAGE_SOURCES += xtiffio.h

SOURCES += cpl_csv.c
SOURCES += cpl_serv.c
SOURCES += geo_extra.c
SOURCES += geo_free.c
SOURCES += geo_get.c
SOURCES += geo_names.c
SOURCES += geo_new.c
SOURCES += geo_normalize.c
SOURCES += geo_print.c
SOURCES += geo_set.c
SOURCES += geo_tiffp.c
SOURCES += geo_trans.c
SOURCES += geo_write.c
SOURCES += geotiff_proj4.c
SOURCES += xtiff.c

IULIBS += -ltiff

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
