LIBRARY := Qv

USES := v3p vxl

INCDIRS += .

SOURCES += vecutil.cxx
SOURCES += QvLib.cxx
SOURCES += wrltraverse.cxx
SOURCES += wrlbuild.cxx
SOURCES += QvVisitor.cxx
SOURCES += QvVrmlFile.cxx

# DEFINES += -D__PC__

include ${IUEROOT}/config/top.mk
