LIBRARY := Qv

USE_STDC++ := 0 # for using vcl

SOURCES += vecutil.cxx
SOURCES += QvLib.cxx
SOURCES += wrltraverse.cxx
SOURCES += wrlbuild.cxx
SOURCES += QvVisitor.cxx
SOURCES += QvVrmlFile.cxx

# The following source files are not needed and hence not compiled into the lib:
# SOURCES += Qv.cxx
# SOURCES += QvAsciiText.cxx
MANPAGE_SOURCES += QvAsciiText.h
MANPAGE_SOURCES += QvBasic.h
# SOURCES += QvChildList.cxx
MANPAGE_SOURCES += QvChildList.h
# SOURCES += QvCone.cxx
MANPAGE_SOURCES += QvCone.h
# SOURCES += QvCoordinate3.cxx
MANPAGE_SOURCES += QvCoordinate3.h
# SOURCES += QvCube.cxx
MANPAGE_SOURCES += QvCube.h
# SOURCES += QvCylinder.cxx
MANPAGE_SOURCES += QvCylinder.h
# SOURCES += QvDB.cxx
MANPAGE_SOURCES += QvDB.h
# SOURCES += QvDebugError.cxx
MANPAGE_SOURCES += QvDebugError.h
# SOURCES += QvDict.cxx
MANPAGE_SOURCES += QvDict.h
# SOURCES += QvDirectionalLight.cxx
MANPAGE_SOURCES += QvDirectionalLight.h
# SOURCES += QvElement.cxx
MANPAGE_SOURCES += QvElement.h
# SOURCES += QvErrors.cxx
# SOURCES += QvExtensions.cxx
MANPAGE_SOURCES += QvExtensions.h
# SOURCES += QvField.cxx
MANPAGE_SOURCES += QvField.h
# SOURCES += QvFieldData.cxx
MANPAGE_SOURCES += QvFieldData.h
# SOURCES += QvFields.cxx
MANPAGE_SOURCES += QvFields.h
# SOURCES += QvFontStyle.cxx
MANPAGE_SOURCES += QvFontStyle.h
# SOURCES += QvGroup.cxx
MANPAGE_SOURCES += QvGroup.h
# SOURCES += QvIndexedFaceSet.cxx
MANPAGE_SOURCES += QvIndexedFaceSet.h
# SOURCES += QvIndexedLineSet.cxx
MANPAGE_SOURCES += QvIndexedLineSet.h
# SOURCES += QvInfo.cxx
MANPAGE_SOURCES += QvInfo.h
# SOURCES += QvInput.cxx
MANPAGE_SOURCES += QvInput.h
# SOURCES += QvLOD.cxx
MANPAGE_SOURCES += QvLOD.h
# SOURCES += QvLists.cxx
MANPAGE_SOURCES += QvLists.h
# SOURCES += QvMFColor.cxx
MANPAGE_SOURCES += QvMFColor.h
# SOURCES += QvMFFace.cxx
MANPAGE_SOURCES += QvMFFace.h
# SOURCES += QvMFFloat.cxx
MANPAGE_SOURCES += QvMFFloat.h
# SOURCES += QvMFLong.cxx
MANPAGE_SOURCES += QvMFLong.h
# SOURCES += QvMFString.cxx
MANPAGE_SOURCES += QvMFString.h
# SOURCES += QvMFVec2f.cxx
MANPAGE_SOURCES += QvMFVec2f.h
# SOURCES += QvMFVec3f.cxx
MANPAGE_SOURCES += QvMFVec3f.h
# SOURCES += QvMaterial.cxx
MANPAGE_SOURCES += QvMaterial.h
# SOURCES += QvMaterialBinding.cxx
MANPAGE_SOURCES += QvMaterialBinding.h
# SOURCES += QvMatrixTransform.cxx
MANPAGE_SOURCES += QvMatrixTransform.h
# SOURCES += QvName.cxx
# SOURCES += QvNode.cxx
MANPAGE_SOURCES += QvNode.h
# SOURCES += QvNodes.cxx
MANPAGE_SOURCES += QvNodes.h
# SOURCES += QvNormal.cxx
MANPAGE_SOURCES += QvNormal.h
# SOURCES += QvNormalBinding.cxx
MANPAGE_SOURCES += QvNormalBinding.h
# SOURCES += QvOrthographicCamera.cxx
MANPAGE_SOURCES += QvOrthographicCamera.h
# SOURCES += QvPList.cxx
MANPAGE_SOURCES += QvPList.h
# SOURCES += QvPerspectiveCamera.cxx
MANPAGE_SOURCES += QvPerspectiveCamera.h
# SOURCES += QvPointLight.cxx
MANPAGE_SOURCES += QvPointLight.h
# SOURCES += QvPointSet.cxx
MANPAGE_SOURCES += QvPointSet.h
# SOURCES += QvReadError.cxx
MANPAGE_SOURCES += QvReadError.h
# SOURCES += QvRotation.cxx
MANPAGE_SOURCES += QvRotation.h
# SOURCES += QvSFBitMask.cxx
MANPAGE_SOURCES += QvSFBitMask.h
# SOURCES += QvSFBool.cxx
MANPAGE_SOURCES += QvSFBool.h
# SOURCES += QvSFColor.cxx
MANPAGE_SOURCES += QvSFColor.h
# SOURCES += QvSFEnum.cxx
MANPAGE_SOURCES += QvSFEnum.h
# SOURCES += QvSFFloat.cxx
MANPAGE_SOURCES += QvSFFloat.h
# SOURCES += QvSFImage.cxx
MANPAGE_SOURCES += QvSFImage.h
# SOURCES += QvSFLong.cxx
MANPAGE_SOURCES += QvSFLong.h
# SOURCES += QvSFMatrix.cxx
MANPAGE_SOURCES += QvSFMatrix.h
# SOURCES += QvSFRotation.cxx
MANPAGE_SOURCES += QvSFRotation.h
# SOURCES += QvSFString.cxx
MANPAGE_SOURCES += QvSFString.h
# SOURCES += QvSFVec2f.cxx
MANPAGE_SOURCES += QvSFVec2f.h
# SOURCES += QvSFVec3f.cxx
MANPAGE_SOURCES += QvSFVec3f.h
# SOURCES += QvScale.cxx
MANPAGE_SOURCES += QvScale.h
# SOURCES += QvSeparator.cxx
MANPAGE_SOURCES += QvSeparator.h
# SOURCES += QvShapeHints.cxx
MANPAGE_SOURCES += QvShapeHints.h
# SOURCES += QvSphere.cxx
MANPAGE_SOURCES += QvSphere.h
# SOURCES += QvSpotLight.cxx
MANPAGE_SOURCES += QvSpotLight.h
# SOURCES += QvState.cxx
MANPAGE_SOURCES += QvState.h
# SOURCES += QvString.cxx
MANPAGE_SOURCES += QvString.h
MANPAGE_SOURCES += QvSubField.h
MANPAGE_SOURCES += QvSubNode.h
# SOURCES += QvSwitch.cxx
MANPAGE_SOURCES += QvSwitch.h
# SOURCES += QvTexture2.cxx
MANPAGE_SOURCES += QvTexture2.h
# SOURCES += QvTexture2Transform.cxx
MANPAGE_SOURCES += QvTexture2Transform.h
# SOURCES += QvTextureCoordinate2.cxx
MANPAGE_SOURCES += QvTextureCoordinate2.h
# SOURCES += QvTransform.cxx
MANPAGE_SOURCES += QvTransform.h
# SOURCES += QvTransformSeparator.cxx
MANPAGE_SOURCES += QvTransformSeparator.h
# SOURCES += QvTranslation.cxx
MANPAGE_SOURCES += QvTranslation.h
# SOURCES += QvUnknownNode.cxx
MANPAGE_SOURCES += QvUnknownNode.h
# SOURCES += QvWWWAnchor.cxx
MANPAGE_SOURCES += QvWWWAnchor.h
# SOURCES += QvWWWInline.cxx
MANPAGE_SOURCES += QvWWWInline.h
MANPAGE_SOURCES += Qv_pi.h
MANPAGE_SOURCES += color.h
MANPAGE_SOURCES += mtl.h
MANPAGE_SOURCES += vectors.h

ifndef NOTEST
MINI_PROG_SOURCES += test-compute-vrml-centroid.cxx
IULIBS += -lQv
endif

# DEFINES += -D__PC__

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifeq "$(TJ_GCC30)" "1"
# gcc 3.1 needs too much virtual memory with -O2
FLAGS_QvLib.cxx += -O1
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
