LIBRARY = Qv

USES = vxl

INCDIRS = . $(IUEROOT)/v3p

SOURCES = QvLib.cpp
SOURCES += wrltraverse.cpp
SOURCES += wrlbuild.cpp
SOURCES += vecutil.cpp

# DEFINES += -D__PC__

include ${IUEROOT}/config/top.mk
