USES += contrib/brl contrib/brl/bseg core

LIBRARY := boxm_io
VERSION := 1.0

SOURCES += boxm_scene_parser.cxx

################################
include ${VXLROOT}/config/top.mk
################################
