USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := sdet_pro
VERSION := 1.0

SOURCES += sdet_register.cxx

MANPAGE_SOURCES += sdet_processes.h
SOURCES += processes/sdet_detect_edges_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
