SOURCES += mfpf_add_all_loaders.cxx
SOURCES += mfpf_edge_finder.cxx
SOURCES += mfpf_edge_finder_builder.cxx
SOURCES += mfpf_norm_corr1d.cxx
SOURCES += mfpf_norm_corr1d_builder.cxx
SOURCES += mfpf_norm_corr2d.cxx
SOURCES += mfpf_norm_corr2d_builder.cxx
SOURCES += mfpf_point_finder.cxx
SOURCES += mfpf_point_finder_builder.cxx
SOURCES += mfpf_profile_pdf.cxx
SOURCES += mfpf_profile_pdf_builder.cxx
SOURCES += mfpf_region_pdf.cxx
SOURCES += mfpf_region_pdf_builder.cxx
MANPAGE_SOURCES += mfpf_norm_vec.h
MANPAGE_SOURCES += mfpf_sample_region.h

SUBDIRS += tests
