USES += contrib/gel contrib/gel/mrc core
include ${VXLROOT}/contrib/gel/mrc/vpgl/config.mk

MINI_PROG_SOURCES += main.cpp

################################
include ${VXLROOT}/config/top.mk
################################
