USES += contrib/gel contrib/gel/mrc core
include ${IUEROOT}/contrib/gel/mrc/vpgl/config.mk

MINI_PROG_SOURCES += main.cpp

################################
include ${IUEROOT}/config/top.mk
################################
