USES += vxl
USE_NETLIB := 1
IULIBS := -lvgl-algo -lvgl -lvnl-algo -lvnl

MINI_PROG_SOURCES += vgl_conic_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
