USES += vxl
include ${IUEROOT}/vxl/vgl/algo/config.mk
include ${IUEROOT}/vxl/vnl/algo/config.mk

MINI_PROG_SOURCES += vgl_conic_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
