USES += core
include ${VXLROOT}/core/vgl/algo/config.mk
include ${VXLROOT}/core/vnl/algo/config.mk
include ${VXLROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += vgl_conic_example.cxx
MINI_PROG_SOURCES += calculate_homography.cxx

################################
include ${VXLROOT}/config/top.mk
################################
