#
# Find the native JPEG library
#

IF(NOT HAS_NATIVE_JPEG)


  FIND_PATH(NATIVE_JPEG_INCLUDE_PATH jpeglib.h
  /usr/local/include
  /usr/include
  )
  
  FIND_LIBRARY(NATIVE_JPEG_LIBRARIES jpeg
  /usr/lib
  /usr/local/lib
  )
  
  SET(HAS_NATIVE_JPEG "NO")
  
  IF(NATIVE_JPEG_LIBRARIES)
    IF(NATIVE_JPEG_INCLUDE_PATH)
  
      SET(HAS_NATIVE_JPEG "YES")
  
    ENDIF(NATIVE_JPEG_INCLUDE_PATH)
  ENDIF(NATIVE_JPEG_LIBRARIES)
ENDIF(NOT HAS_NATIVE_JPEG)
