# try to find fltk, using the FindFLTK.cmake file from CMake

IF (NOT HAS_FLTK)
  INCLUDE(${CMAKE_ROOT}/Modules/FindFLTK.cmake)

  IF (FLTK_INCLUDE_PATH)
    IF (FLTK_LIBRARY)
      SET($FLTK_LIBRARIES ${FLTK_LIBRARY})
      ADD_DEFINITIONS( -DHAS_GLUT )
      SET(HAS_FLTK "YES")
    ENDIF (FLTK_LIBRARY)
  ENDIF (FLTK_INCLUDE_PATH)

ENDIF (NOT HAS_FLTK)
