#
# Find the native JPEG library
#

IF(NOT HAS_NATIVE_JPEG)
  FIND_PATH(NATIVE_JPEG_INCLUDE_PATH jpeglib.h
  /usr/local/include
  /usr/include
  )
  
  FIND_LIBRARY(NATIVE_JPEG_LIBRARY jpeg
  /usr/lib
  /usr/local/lib
  )
  
  SET(HAS_NATIVE_JPEG "NO")
  
  IF(NATIVE_JPEG_LIBRARY)
    IF(NATIVE_JPEG_INCLUDE_PATH)
  
      SET(HAS_NATIVE_JPEG "YES")
  
      INCLUDE_DIRECTORIES( ${NATIVE_JPEG_INCLUDE_PATH} )
      LINK_LIBRARIES( ${NATIVE_JPEG_LIBRARY} )
  
    ENDIF(NATIVE_JPEG_INCLUDE_PATH)
  ENDIF(NATIVE_JPEG_LIBRARY)
ENDIF(NOT HAS_NATIVE_JPEG)
