#
# Find the native JPEG library
#

FIND_PATH(NATIVE_JPEG_INCLUDE_PATH jpeglib.h
/usr/local/include
/usr/include
)

FIND_LIBRARY(NATIVE_JPEG_LIB_PATH jpeg
/usr/lib
/usr/local/lib
)

SET(HAS_NATIVE_JPEG "NO" CACHE)

IF(NATIVE_JPEG_LIB_PATH)
  IF(NATIVE_JPEG_INCLUDE_PATH)
    SET(NATIVE_JPEG_LIBRARY "jpeg" CACHE)
    SET(HAS_NATIVE_JPEG "YES" CACHE)
  ENDIF(NATIVE_JPEG_INCLUDE_PATH)
ENDIF(NATIVE_JPEG_LIB_PATH)
