#
# Try to find Qv
#

IF(NOT HAS_QV)

  SET( HAS_QV "YES" )

  ADD_DEFINITIONS( -DHAS_QV )
  LINK_LIBRARIES( Qv )
  SET (QV_INCLUDE_PATH ${allvxl_SOURCE_DIR}/v3p)
  INCLUDE_DIRECTORIES(${QV_INCLUDE_PATH})

ENDIF(NOT HAS_QV)
