#include <sdet/sdet_mrf_bp_sptr.h>
#include <sdet/sdet_mrf_site_bp_sptr.h>
#include <sdet/sdet_region_edge_sptr.h>
#include <sdet/sdet_region_sptr.h>
#include <sdet/sdet_texture_classifier_sptr.h>
#include <sdet/sdet_atmospheric_image_classifier.h>
#include <sdet/sdet_contour.h>
#include <sdet/sdet_denoise_mrf.h>
#include <sdet/sdet_denoise_mrf_bp.h>
#include <sdet/sdet_denoise_mrf_bp_params.h>
#include <sdet/sdet_denoise_mrf_params.h>
#include <sdet/sdet_detector.h>
#include <sdet/sdet_detector_params.h>
#include <sdet/sdet_edge_champher.h>
#include <sdet/sdet_edgel_regions.h>
#include <sdet/sdet_fit_conics.h>
#include <sdet/sdet_fit_conics_params.h>
#include <sdet/sdet_fit_lines.h>
#include <sdet/sdet_fit_lines_params.h>
#include <sdet/sdet_gauss_fit.h>
#include <sdet/sdet_grid_finder.h>
#include <sdet/sdet_grid_finder_params.h>
#include <sdet/sdet_harris_detector.h>
#include <sdet/sdet_harris_detector_params.h>
#include <sdet/sdet_image_mesh.h>
#include <sdet/sdet_image_mesh_params.h>
#include <sdet/sdet_img_edge.h>
#include <sdet/sdet_mrf_bp.h>
#include <sdet/sdet_mrf_site_bp.h>
#include <sdet/sdet_nms.h>
#include <sdet/sdet_nonmax_suppression.h>
#include <sdet/sdet_nonmax_suppression_params.h>
#include <sdet/sdet_region.h>
#include <sdet/sdet_region_edge.h>
#include <sdet/sdet_region_proc.h>
#include <sdet/sdet_region_proc_params.h>
#include <sdet/sdet_texture_classifier.h>
#include <sdet/sdet_texture_classifier_params.h>
#include <sdet/sdet_third_order_edge_det.h>
#include <sdet/sdet_third_order_edge_det_params.h>
#include <sdet/sdet_vrml_display.h>
#include <sdet/sdet_watershed_region_proc.h>
#include <sdet/sdet_watershed_region_proc_params.h>
#include <sdet/sdet_edgel.h>
#include <sdet/sdet_edgel_link_graph.h>
#include <sdet/sdet_edgemap.h>
#include <sdet/sdet_sel.h>
#include <sdet/sdet_symbolic_edge_linker.h>
#include <sdet/sdet_symbolic_edge_linker_params.h>

int main() { return 0; }
