USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += bstm_ocl_render_view.cxx
MINI_PROG_SOURCES += bstm_ocl_multi_render_view.cxx

################################
include ${VXLROOT}/config/top.mk
################################
