USES += contrib/brl contrib/brl/bbas core

LIBRARY := bsl
VERSION := 1.0

SOURCES += bsl_opinion.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
