USES += contrib/oxl core
include ${IUEROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += multiple-windows.cxx

################################
include ${IUEROOT}/config/top.mk
################################
