USES += contrib/oxl core
include ${VXLROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += multiple-windows.cxx

################################
include ${VXLROOT}/config/top.mk
################################
