USES += vxl oxl

#USE_OPENGL := 1
#USE_GLUT := 1
#USE_GTKGLAREA := 1
#USE_HERMES := 1

MINI_PROG_SOURCES += multiple-windows.cxx

##########################################
include ${IUELOCALROOT}/oxl/vgui/config.mk
include ${IUEROOT}/config/top.mk
################################
