USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bpro_batch

SOURCES += bpro_batch.cxx

################################
include ${VXLROOT}/config/top.mk
################################
