#ifndef v3p_netlib_unmangle_h
#define v3p_netlib_unmangle_h

/* This header undefines mangled names defined by v3p_netlib_mangle.h. */

/* Functions */

#undef balanc_
#undef balbak_
#undef caxpy_
#undef ccopy_
#undef cdiv_
#undef cdotc_
#undef cqrdc_
#undef cqrsl_
#undef cscal_
#undef csrot_
#undef csvdc_
#undef cswap_
#undef dasum_
#undef daxpy_
#undef dcabs1_
#undef dcopy_
#undef ddot_
#undef dgpfa2f_
#undef dgpfa3f_
#undef dgpfa5f_
#undef dgpfa_
#undef dlabax_
#undef dlabcm_
#undef dlabfc_
#undef dlaeig_
#undef dlager_
#undef dlaran_
#undef dmvpc_
#undef dnlaso_
#undef dnppla_
#undef dnrm2_
#undef dnwla_
#undef dortqr_
#undef dpoco_
#undef dpodi_
#undef dpofa_
#undef dposl_
#undef dqrdc_
#undef dqrsl_
#undef drot_
#undef drotg_
#undef dscal_
#undef dsvdc_
#undef dswap_
#undef dvsort_
#undef dznrm2_
#undef elmhes_
#undef eltran_
#undef epslon_
#undef gpfa2f_
#undef gpfa3f_
#undef gpfa5f_
#undef gpfa_
#undef hqr2_
#undef hqr_
#undef pythag_
#undef rebak_
#undef reduc_
#undef rg_
#undef rs_
#undef rsg_
#undef saxpy_
#undef scnrm2_
#undef scopy_
#undef sdot_
#undef setdgpfa_
#undef setgpfa_
#undef snrm2_
#undef sqrdc_
#undef sqrsl_
#undef srot_
#undef srotg_
#undef sscal_
#undef ssvdc_
#undef sswap_
#undef tql1_
#undef tql2_
#undef tqlrat_
#undef tred1_
#undef tred2_
#undef urand_
#undef zaxpy_
#undef zcopy_
#undef zdotc_
#undef zdrot_
#undef zqrdc_
#undef zqrsl_
#undef zscal_
#undef zsvdc_
#undef zswap_

#endif
