USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvxm_batch
VERSION := 1.0

SOURCES += reg_bvxm.cxx

################################
include ${VXLROOT}/config/top.mk
################################
