USES := conversions vxl gel COOL GeneralUtility SpatialObjects Numerics

TESTS += test_DigitalCurve_to_vdgl.cxx

IULIBS := -lvdgl -lvsol -lvgl -lvnl -lvbl
IULIBS += -lDigitalGeometry -lCompGeom -lTopology -lGroups -lGeometry -lSpatialBasics -lBasics -lSolver -lNumerics

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
