USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${VXLROOT}/core/vgui/wx/config.mk
include ${VXLROOT}/core/vgui/config.mk
USE_WXWIDGETS := 1

PROGRAM := wx_example

SOURCES += bwm_wx_app.cxx
SOURCES += bwm_wx_frame.cxx
MANPAGE_SOURCES += bwm_wx_menu.h

###################################
include ${VXLROOT}/config/params.mk
###################################
