USES += contrib/brl contrib/brl/bbas core
include ../config.mk

PROGRAM := wx_example

SOURCES += bwm_wx_app.cxx
SOURCES += bwm_wx_frame.cxx
MANPAGE_SOURCES += bwm_wx_menu.h

###################################
include ${VXLROOT}/config/params.mk
###################################
