USES += contrib/mul core
include ../config.mk

MINI_PROG_SOURCES += copy_image.cxx
MINI_PROG_SOURCES += mvl2_to_divx.cxx

################################
include ${IUEROOT}/config/top.mk
################################
