USES += core
include ../config.mk
include ${IUEROOT}/core/vbl/config.mk
include ${IUEROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += vidl_mpegcodec_example.cxx
MINI_PROG_SOURCES += vidl_video2images.cxx

PROGRAM = vidl_player
SOURCES += vidl_player_main.cxx
SOURCES += vidl_player_manager.cxx
SOURCES += vidl_player_menus.cxx

################################
include ${IUEROOT}/config/top.mk
################################
