USES += core
include ../config.mk
include ${IUEROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += vidl_mpegcodec_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
