USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bbgm_batch
VERSION := 1.0

SOURCES += reg_bbgm.cxx

################################
include ${VXLROOT}/config/top.mk
################################
