# fsm@robots.ox.ac.uk
# this file is generated by rules.mk
ifeq ($(strip $(TRY_OPENGL)),1)
  ifeq ($(strip $(HAS_OPENGL)),1)
    USE_OPENGL := 1
  endif
endif

ifeq ($(strip $(TRY_GLUT)),1)
  ifeq ($(strip $(HAS_GLUT)),1)
    USE_GLUT := 1
  endif
endif

ifeq ($(strip $(TRY_FLTK)),1)
  ifeq ($(strip $(HAS_FLTK)),1)
    USE_FLTK := 1
  endif
endif

ifeq ($(strip $(TRY_GTKGLAREA)),1)
  ifeq ($(strip $(HAS_GTKGLAREA)),1)
    USE_GTKGLAREA := 1
  endif
endif

ifeq ($(strip $(TRY_MOTIFGL)),1)
  ifeq ($(strip $(HAS_MOTIFGL)),1)
    USE_MOTIFGL := 1
  endif
endif

ifeq ($(strip $(TRY_JPEG)),1)
  ifeq ($(strip $(HAS_JPEG)),1)
    USE_JPEG := 1
  endif
endif

ifeq ($(strip $(TRY_MPEG)),1)
  ifeq ($(strip $(HAS_MPEG)),1)
    USE_MPEG := 1
  endif
endif

ifeq ($(strip $(TRY_DCMTK)),1)
  ifeq ($(strip $(HAS_DCMTK)),1)
    USE_DCMTK := 1
  endif
endif

ifeq ($(strip $(TRY_MPEG2)),1)
  ifeq ($(strip $(HAS_MPEG2)),1)
    USE_MPEG2 := 1
  endif
endif

ifeq ($(strip $(TRY_AVI)),1)
  ifeq ($(strip $(HAS_AVI)),1)
    USE_AVI := 1
  endif
endif

ifeq ($(strip $(TRY_TIFF)),1)
  ifeq ($(strip $(HAS_TIFF)),1)
    USE_TIFF := 1
  endif
endif

ifeq ($(strip $(TRY_PNG)),1)
  ifeq ($(strip $(HAS_PNG)),1)
    USE_PNG := 1
  endif
endif

ifeq ($(strip $(TRY_SDL)),1)
  ifeq ($(strip $(HAS_SDL)),1)
    USE_SDL := 1
  endif
endif

ifeq ($(strip $(TRY_HERMES)),1)
  ifeq ($(strip $(HAS_HERMES)),1)
    USE_HERMES := 1
  endif
endif

