USES = vxl
include ${IUEROOT}/vxl/vpl/config.mk
include ${IUEROOT}/vxl/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_unistd.cxx
TESTS += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
