USES := # nothing
USE_STDC++ := 0
USE_OPENJPEG2 := 1

LIBRARY := openjpeg2
VERSION := 1.0

SOURCES += raw.c
SOURCES += invert.c
SOURCES += function_list.c
SOURCES += openjpeg.c
MANPAGE_SOURCES += int.h
MANPAGE_SOURCES += t1_luts.h
SOURCES += jp2.c
SOURCES += dwt.c
SOURCES += j2k.c
MANPAGE_SOURCES += opj_configure.h
SOURCES += j2k_lib.c
SOURCES += bio.c
SOURCES += event.c
SOURCES += mct.c
SOURCES += tgt.c
SOURCES += mqc.c
SOURCES += profile.c
SOURCES += t1.c
SOURCES += jpt.c
SOURCES += pi.c
MANPAGE_SOURCES += fix.h
SOURCES += tcd.c
MANPAGE_SOURCES += opj_includes.h
SOURCES += image.c
MANPAGE_SOURCES += opj_malloc.h
SOURCES += cio.c
SOURCES += t2.c

################################
include ${VXLROOT}/config/top.mk
################################
