USES := # nothing
USE_STDC++ := 0
USE_OPENJPEG2 := 1

LIBRARY := openjpeg2
VERSION := 1.0

MANPAGE_SOURCES += raw.h
MANPAGE_SOURCES += invert.h
MANPAGE_SOURCES += function_list.h
MANPAGE_SOURCES += openjpeg.h
MANPAGE_SOURCES += int.h
MANPAGE_SOURCES += t1_luts.h
MANPAGE_SOURCES += jp2.h
MANPAGE_SOURCES += dwt.h
MANPAGE_SOURCES += j2k.h
MANPAGE_SOURCES += opj_configure.h
MANPAGE_SOURCES += j2k_lib.h
MANPAGE_SOURCES += bio.h
MANPAGE_SOURCES += event.h
MANPAGE_SOURCES += mct.h
MANPAGE_SOURCES += tgt.h
MANPAGE_SOURCES += mqc.h
MANPAGE_SOURCES += profile.h
MANPAGE_SOURCES += t1.h
MANPAGE_SOURCES += jpt.h
MANPAGE_SOURCES += pi.h
MANPAGE_SOURCES += fix.h
MANPAGE_SOURCES += tcd.h
MANPAGE_SOURCES += opj_includes.h
MANPAGE_SOURCES += image.h
MANPAGE_SOURCES += opj_malloc.h
MANPAGE_SOURCES += cio.h
MANPAGE_SOURCES += t2.h

################################
include ${VXLROOT}/config/top.mk
################################
