USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bvpl_batch

SOURCES += reg_bvpl.cxx

################################
include ${VXLROOT}/config/top.mk
################################
