USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_pro

SOURCES += bvpl_register.cxx
MANPAGE_SOURCES += bvpl_processes.h

SOURCES += processes/bvpl_neighborhood_operator_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_vector_process.cxx
SOURCES += processes/bvpl_vector_operator_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_process.cxx
SOURCES += processes/bvpl_convert_direction_to_hue_process.cxx
SOURCES += processes/bvpl_create_gauss3d_xx_kernel_process.cxx
SOURCES += processes/bvpl_create_gauss3d_xx_kernel_vector_process.cxx
SOURCES += processes/bvpl_compare_surface_and_normal_process.cxx
SOURCES += processes/bvpl_susan_opinion_operator_process.cxx
SOURCES += processes/bvpl_kernel_id_to_axis_process.cxx
SOURCES += processes/bvpl_create_corner2d_kernel_vector_process.cxx
SOURCES += processes/bvpl_non_max_suppression_process.cxx
SOURCES += processes/bvpl_visualize_response_process.cxx
SOURCES += processes/bvpl_convert_id_to_hue_process.cxx
SOURCES += processes/bvpl_extract_top_response_process.cxx
SOURCES += processes/bvpl_operate_ocp_and_app_proccess.cxx
SOURCES += processes/bvpl_create_corner2d_kernel_process.cxx
SOURCES += processes/bvpl_suppress_and_combine_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
