USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_pro

SOURCES += bvpl_register.cxx
MANPAGE_SOURCES += bvpl_processes.h

SOURCES += processes/bvpl_neighborhood_operator_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
