USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_pro

SOURCES += bvpl_register.cxx
MANPAGE_SOURCES += bvpl_processes.h

SOURCES += processes/bvpl_neighborhood_operator_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_vector_process.cxx
SOURCES += processes/bvpl_vector_operator_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_process.cxx
SOURCES += processes/bvpl_convert_direction_to_hue_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
