USES := vxl tbl
include ${IUEROOT}/vxl/vil/config.mk

TESTS += test_threshold.cxx

IULIBS += -lvipl -lvil

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
