USES := vxl mul

LIBRARY := vil3d-io
VERSION := 1.0

SOURCES += vil3d_io_dummy.cxx
MANPAGE_SOURCES += vil3d_io_image_view.h

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
