USES += contrib/brl core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTS += bcal_test.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
