USES += contrib/brl contrib/gel core
include ../config.mk

TESTS += bcal_test.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
