USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/brl/bmvl core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTS += bcal_test.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
