USES = # nothing
USE_STDC++ := 0

LIBRARY := NCSEcw

MANPAGE_SOURCES += ComNCSRenderer.h
MANPAGE_SOURCES += comissue.h
MANPAGE_SOURCES += NCSEcwCom.h
MANPAGE_SOURCES += NCSEcwCP.h

SUBDIRS += ../../NCSUtil/NCSUtil_Static
SUBDIRS += ../../NCSnet/NCScnet2
SUBDIRS += ../../NCSnet/NCScnet2/NCScnet2_Static

################################
include ${VXLROOT}/config/top.mk
################################
