USES += contrib/brl contrib/brl/bbas

LIBRARY := bocl_pro

SOURCES += bocl_register.cxx
MANPAGE_SOURCES += bocl_processes.h

SOURCES += processes/bocl_get_device_process.cxx
SOURCES += processes/bocl_init_manager_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
