IULIBS += -lbwm_algo
include ${VXLROOT}/contrib/brl/bseg/sdet/config.mk
include ${VXLROOT}/contrib/brl/bseg/brip/config.mk
include ${VXLROOT}/contrib/brl/bbas/bgui/config.mk
include ${VXLROOT}/contrib/brl/bbas/bsta/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/algo/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/file_formats/config.mk
include ${VXLROOT}/contrib/gel/mrc/vpgl/config.mk
include ${VXLROOT}/contrib/gel/vdgl/config.mk
include ${VXLROOT}/contrib/gel/vtol/config.mk
include ${VXLROOT}/contrib/gel/vsol/config.mk
include ${VXLROOT}/core/vgui/config.mk
include ${VXLROOT}/core/vil/algo/config.mk
include ${VXLROOT}/core/vil/config.mk
include ${VXLROOT}/core/vgl/algo/config.mk
include ${VXLROOT}/core/vgl/config.mk
include ${VXLROOT}/core/vnl/algo/config.mk
include ${VXLROOT}/core/vnl/config.mk
include ${VXLROOT}/contrib/brl/b3p/shapelib/config.mk
