USES += contrib/gel contrib/oxl core
include ../config.mk
include ${VXLROOT}/contrib/gel/vtol/config.mk
include ${VXLROOT}/core/vil/config.mk

MINI_PROG_SOURCES += kl_tracker.cxx

################################
include ${VXLROOT}/config/top.mk
################################
