USES := gel vxl oxl v3p
include ${IUEROOT}/vxl/vil/config.mk
include ${IUEROOT}/vxl/vnl/algo/config.mk

IULIBS := -lvgel_kl -lvgel -lvtol -lvsol -lvidl -lmvl -lvnl-algo -lvgl -lvnl -lvil -lvbl -lvul

MINI_PROG_SOURCES += kl_tracker.cxx

################################
include ${IUEROOT}/config/top.mk
################################
