USES += core
include ../config.mk
include ${IUEROOT}/core/vul/config.mk

MINI_PROG_SOURCES += algo_example1.cxx
MINI_PROG_SOURCES += algo_example2.cxx
MINI_PROG_SOURCES += vil_convolve_tool.cxx
MINI_PROG_SOURCES += vil_correlate_grad_tool.cxx
MINI_PROG_SOURCES += vil_exp_grad_filter_tool.cxx
MINI_PROG_SOURCES += example_complex.cxx

################################
include ${IUEROOT}/config/top.mk
################################
