USES += vxl oxl
include ../config.mk
include ${IUEROOT}/vxl/vul/config.mk
include ${IUEROOT}/vxl/vil/config.mk

# Harris corner detector
MINI_PROG_SOURCES += run_osl_harris.cxx

#
MINI_PROG_SOURCES += run_osl_canny.cxx
MINI_PROG_SOURCES += topology_edges.cxx
MINI_PROG_SOURCES += break_lines.cxx
MINI_PROG_SOURCES += fit_lines.cxx

################################
include ${IUEROOT}/config/top.mk
################################
