USES += contrib/brl contrib/gel contrib/brl/bbas core
include ${IUEROOT}/core/vgui/config.mk

LIBRARY := bgui
VERSION := 1.0

SOURCES += bgui_picker_tableau.cxx
MANPAGE_SOURCES += bgui_picker_tableau_sptr.h
SOURCES += bgui_vtol2D_tableau.cxx
MANPAGE_SOURCES += bgui_vtol2D_tableau_sptr.h
SOURCES += bgui_vtol_soview2D.cxx
SOURCES += bgui_image_tableau.cxx
MANPAGE_SOURCES += bgui_image_tableau_sptr.h
SOURCES += bgui_style.cxx
MANPAGE_SOURCES += bgui_style_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
