USES += contrib/brl contrib/gel contrib/brl/bbas contrib/brl/bseg core
include ${IUEROOT}/core/vgui/config.mk

LIBRARY := bgui
VERSION := 1.0

SOURCES += bgui_picker_tableau.cxx
MANPAGE_SOURCES += bgui_picker_tableau_sptr.h
SOURCES += bgui_vtol2D_tableau.cxx
MANPAGE_SOURCES += bgui_vtol2D_tableau_sptr.h
SOURCES += bgui_vtol_soview2D.cxx
SOURCES += bgui_image_tableau.cxx
MANPAGE_SOURCES += bgui_image_tableau_sptr.h
SOURCES += bgui_style.cxx
MANPAGE_SOURCES += bgui_style_sptr.h
SOURCES += bgui_vsol_camera_tableau.cxx
MANPAGE_SOURCES += bgui_vsol_camera_tableau_sptr.h
SOURCES += bgui_vsol_soview2D.cxx
SOURCES += bgui_vsol2D_tableau.cxx
MANPAGE_SOURCES += bgui_vsol2D_tableau_sptr.h 
SOURCES += bgui_displaybase_tableau.cxx
MANPAGE_SOURCES += bgui_displaybase_tableau_sptr.h
SOURCES += bgui_displaylist2D_tableau.cxx
MANPAGE_SOURCES += bgui_displaylist2D_tableau_sptr.h
SOURCES += bgui_easy2D_tableau.cxx
MANPAGE_SOURCES += bgui_easy2D_tableau_sptr.h
SOURCES += bgui_linked_vsol2D_tableau.cxx
MANPAGE_SOURCES += bgui_linked_vsol2D_tableau_sptr.h
SOURCES += bgui_linked_vsol_soview2D.cxx
SOURCES += bgui_histogram_tableau.cxx
MANPAGE_SOURCES += bgui_histogram_tableau_sptr.h
SOURCES += bgui_selector_tableau.cxx
MANPAGE_SOURCES += bgui_selector_tableau_sptr.h
SOURCES += bgui_bmrf_soview2D.cxx

################################
include ${IUEROOT}/config/top.mk
################################
