USES = vxl oxl
USE_OPENGL := 1
USE_NETLIB := 1
include ${IUELOCALROOT}/oxl/vgui/easy-client.mk

MINI_PROG_SOURCES += main.cxx

################################
include $(IUEROOT)/config/top.mk
################################
