USES += contrib/oxl core
include ${IUELOCALROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += main.cxx

################################
include $(IUEROOT)/config/top.mk
################################
