USES += contrib/oxl core
include ${VXLROOT}/contrib/oxl/vrml/config.mk
include ${VXLROOT}/core/vgui/config.mk

MINI_PROG_SOURCES += main.cxx

################################
include $(VXLROOT)/config/top.mk
################################
