USES += contrib/oxl core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
