USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/brl/bmvl contrib/gel core

LIBRARY := btom
VERSION := 1.0

SOURCES += btom_gauss_cylinder.cxx
MANPAGE_SOURCES += btom_gauss_cylinder_sptr.h
SOURCES += btom_slice_simulator.cxx
SOURCES += btom_slice_simulator_params.cxx

################################
include ${IUEROOT}/config/top.mk
################################
