/*
 * This file is generated by IncBuildNumber.ksh
 * Change only the major version, or build number if you are editing manually.
 * last updated: Tue Mar 21 08:24:57 WAST 2006
 */
#define NCS_VERSION_NUMBER 3,3,0,161
#define NCS_VERSION_STRING "3,3,0,161\0"
#define NCS_VERSION_STRING_NO_NULL "3,3,0,161"
#define NCS_VERSION_STRING_DOT_DEL "3.3.0.161"
#define NCS_SERVER_VERSION_NUMBER 7.5
#define NCS_SERVER_VERSION_STRING "7.5"
#define NCS_ECWSDK_VERSION_NUMBER 3.3
#define NCS_ECWSDK_VERSION_STRING "3.3"
#define NCS_HEADEREDITOR_VERSION_NUMBER 2.52
#define NCS_HEADEREDITOR_VERSION_STRING "2.52"
