USES += v3p # for Qv
USES += vxl
USE_OPENGL:=1

LIBRARY := vgui-vrml

SOURCES += vgui_vrml_texture_map.cxx
SOURCES += vgui_vrml_draw_visitor.cxx
SOURCES += vgui_vrml_tableau.cxx

#SOURCES += VGUI_vrml.cxx
#SOURCES += VrmlFile.cxx
#SOURCES += VrmlVisitor.cxx
#SOURCES += VrmlDrawVisitor.cxx

#SOURCES += projective_skew.cxx
#SOURCES += setup_lights.cxx

################################
include ${IUEROOT}/config/top.mk
################################
