USES += v3p # for Qv
USES += vxl oxl
USE_OPENGL:=1

LIBRARY := vgui-vrml

SOURCES += vgui_vrml_texture_map.cxx
SOURCES += vgui_vrml_draw_visitor.cxx
SOURCES += vgui_vrml_tableau.cxx

################################
include ${IUEROOT}/config/top.mk
################################
