USES += contrib/gel core
include ../config.mk

MINI_PROG_SOURCES += register_images_exe.cxx
MINI_PROG_SOURCES += compute_homographies_exe.cxx

################################
include ${VXLROOT}/config/top.mk
################################
