USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_kernels

SOURCES += bvpl_edge3d_kernel_factory.cxx
SOURCES += bvpl_create_directions.cxx
SOURCES += bvpl_neighborhood_kernel_factory.cxx
SOURCES += bvpl_gauss3d_xx_kernel_factory.cxx
SOURCES += bvpl_weighted_cube_kernel_factory.cxx
SOURCES += bvpl_kernel.cxx
SOURCES += bvpl_kernel_factory.cxx
SOURCES += bvpl_corner2d_kernel_factory.cxx
SOURCES += bvpl_taylor_basis_factory.cxx
SOURCES += bvpl_edge2d_kernel_factory.cxx
SOURCES += bvpl_gauss3d_x_kernel_factory.cxx
MANPAGE_SOURCES += bvpl_kernel_iterator.h

SUBDIRS += pro io

################################
include ${VXLROOT}/config/top.mk
################################
