USES += contrib/brl contrib/brl/bbas core

LIBRARY := bcal
VERSION := 1.0

SOURCES += camera.cpp
SOURCES += CameraNode.cpp
SOURCES += ZhangCameraNode.cpp
SOURCES += cam_test.cpp

################################
include ${IUEROOT}/config/top.mk
################################
