USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2_batch

SOURCES += reg_boxm2.cxx

################################
include ${VXLROOT}/config/top.mk
################################
