USES += core
include ../config.mk

TESTS += vidl_test.cxx
MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
