USES += contrib/brl contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += bapl_draw_keypoints.cxx
MINI_PROG_SOURCES += bapl_lowe_recognizer.cxx
MINI_PROG_SOURCES += bapl_make_pyramids.cxx

################################
include ${VXLROOT}/config/top.mk
################################
