USES += contrib/brl/b3p
include ../config.mk

MINI_PROG_SOURCES += SimpleTest.cpp
MINI_PROG_SOURCES += StdAfx.cpp

################################
include ${VXLROOT}/config/top.mk
################################
