USES += contrib/brl contrib/brl/bbas core

LIBRARY := bsta-io
VERSION := 1.0

MANPAGE_SOURCES += bsta_io_attributes.h
MANPAGE_SOURCES += bsta_io_gaussian_angles_1d.h
MANPAGE_SOURCES += bsta_io_gaussian_full.h
MANPAGE_SOURCES += bsta_io_gaussian_indep.h
MANPAGE_SOURCES += bsta_io_gaussian_sphere.h
MANPAGE_SOURCES += bsta_io_gaussian_x_y_theta.h
MANPAGE_SOURCES += bsta_io_mixture.h
MANPAGE_SOURCES += bsta_io_mixture_fixed.h

################################
include ${VXLROOT}/config/top.mk
################################
