USE_NETLIB := 1
NO_STDLIBS := 1

TESTS += lbfgs-example.c
TESTS += lsqr-test.c

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
