USE_NETLIB := 1
NO_STDLIBS := 1

TESTS += lbfgs-example.c
TESTS += lsqr-test.c
TESTS += slamch-test.c
TESTS += tricall.c
TESTS += integral-test.c

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
