USES += contrib/brl contrib/brl/bbas core

LIBRARY := bgeo
VERSION := 1.0
DEFINES += -DBUILDING_GEO_DLL

SOURCES += bgeo_lvcs.cxx
MANPAGE_SOURCES += bgeo_lvcs_sptr.h
SOURCES += bgeo_datum_conversion.cxx
MANPAGE_SOURCES += bgeo_earth_constants.h

MANPAGE_SOURCES += bgeo_dll.h

SUBDIRS += tests
