#include <boxm2/io/boxm2_stream_cache.txx>
#include <vcl_vector.h>
#include <boxm2/boxm2_data_traits.h>

BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_ALPHA);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_MOG2_RGB);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_MOG3_GREY_16);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_MOG3_GREY);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_AUX);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_AUX0);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_AUX1);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_AUX2);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_AUX3);
BOXM2_STREAM_CACHE_INSTANTIATE(BOXM2_NUM_OBS_SINGLE);

