USES += core
include ../config.mk

TESTMAIN = test_driver.cxx
TESTS += test_assert.cxx
TESTS += test_macros.cxx
TESTS += test_args.cxx
PARAMS_test_args = one two
TESTS += test_root_dir.cxx
MINI_PROG_SOURCES += test_link.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
