USES = vxl

TESTMAIN = test_driver.cxx
TESTS += test_assert.cxx
TESTS += test_macros.cxx
TESTS += test_args.cxx
TESTS += test_root_dir.cxx

PARAMS_test_args = one two

IULIBS := -ltestlib

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
