USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += bmsh3d_mesh2ply.cxx
MINI_PROG_SOURCES += example_triangles.cxx

################################
include ${VXLROOT}/config/top.mk
################################
