USES += contrib/gel core

IMMEDIATE_LIBS += -lvtol

LIBRARY := vtol-algo
VERSION := 1.0

SOURCES += vtol_extract_topology.cxx

################################
include ${IUEROOT}/config/top.mk
################################
