USES += contrib/gel core
include ../config.mk
include ${VXLROOT}/core/vul/config.mk

MINI_PROG_SOURCES += vpgl_synth_bundle_adjust.cxx

################################
include ${VXLROOT}/config/top.mk
################################
