USES += contrib/brl contrib/brl/bseg core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_ekf_camera_optimizer_seq.cxx
TESTS += test_homography_generator.cxx
TESTS += test_ekf_camera_optimizer.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
