USES += core
include ${IUEROOT}/core/vil/config.mk
include ${IUEROOT}/core/vil2/config.mk
include ${IUEROOT}/core/vul/config.mk

MINI_PROG_SOURCES += create_image_vil.cxx
MINI_PROG_SOURCES += create_image_vil2.cxx

SUBDIRS += vnl_calc

################################
include ${IUEROOT}/config/top.mk
################################
