USES += core
include ${VXLROOT}/core/vil/config.mk
include ${VXLROOT}/core/vul/config.mk

MINI_PROG_SOURCES += create_image_vil.cxx

SUBDIRS += vnl_calc

################################
include ${VXLROOT}/config/top.mk
################################
