USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vil_pro
VERSION := 1.0

SOURCES += vil_io_image_view_base.cxx
SOURCES += vil_load_image_view_process.cxx
SOURCES += vil_save_image_view_process.cxx
SOURCES += vil_binary_image_op_process.cxx
SOURCES += vil_map_image_process.cxx
MANPAGE_SOURCES += vil_math_functors.h

################################
include ${VXLROOT}/config/top.mk
################################
