USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bstm_batch

SOURCES += reg_bstm.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
