USES += vxl
USES += mul
IULIBS := -lvsl

TESTS += test_indent.cxx
TESTS += test_vsl_io.cxx
TESTS += test_binary_io.cxx

TESTS += test_arbitrary_length_int_conversion.cxx
TESTS += test_clipon_polymorphic_io.cxx
TESTS += test_complex_io.cxx
TESTS += test_deque_io.cxx
TESTS += test_list_io.cxx
TESTS += test_map_io.cxx
TESTS += test_polymorphic_io.cxx
TESTS += test_set_io.cxx
TESTS += test_stack_io.cxx
TESTS += test_string_io.cxx
TESTS += test_vector_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
