USES += vxl
USES += mul
IULIBS := -lvsl

TESTS += test_indent.cxx
TESTS += test_vsl_io.cxx
TESTS += test_binary_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
