USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm

SOURCES += dummy.cxx

MANPAGE_SOURCES += boxm_opt3_optimizer.txx
MANPAGE_SOURCES += boxm_edge_tangent_updater.txx
MANPAGE_SOURCES += boxm_opt_rt_bayesian_optimizer.txx
MANPAGE_SOURCES += boxm_opt2_optimizer.txx
MANPAGE_SOURCES += boxm_edge_updater.txx

MANPAGE_SOURCES += boxm_render_expected_shadow_image_functor.h
MANPAGE_SOURCES += boxm_generate_edge_tangent_sample_functor.h
MANPAGE_SOURCES += boxm_generate_opt2_sample_functor.h
MANPAGE_SOURCES += boxm_change_probability_functor.h
MANPAGE_SOURCES += boxm_opt_appearance_estimator.h
MANPAGE_SOURCES += boxm_update_image_functor.h
MANPAGE_SOURCES += boxm_rpc_registration.h
MANPAGE_SOURCES += boxm_sun_vis_prob_functor.h
MANPAGE_SOURCES += boxm_generate_edge_sample_functor.h
MANPAGE_SOURCES += boxm_render_expected_image_functor.h
MANPAGE_SOURCES += boxm_generate_opt_sample_functor.h
MANPAGE_SOURCES += boxm_pre_infinity_functor.h
MANPAGE_SOURCES += boxm_render_expected_edge_tangent_image_functor.h
MANPAGE_SOURCES += boxm_render_expected_edge_image_functor.h
MANPAGE_SOURCES += boxm_render_expected_depth_functor.h
MANPAGE_SOURCES += boxm_generate_opt3_sample_functor.h
MANPAGE_SOURCES += boxm_change_3d_functor.h

SUBDIRS += pro

################################
include ${VXLROOT}/config/top.mk
################################
