TESTMAIN = vcl_tests.cxx
# All tests are called from vcl_tests.cxx
#SOURCES += test_vcl_rel_ops.cxx
TESTS   += test_vcl_compiler.cxx
SOURCES += test_vcl_headers.cxx
SOURCES += test_vcl_iterator.cxx
SOURCES += test_vcl_iostream.cxx
SOURCES += test_vcl_fstream.cxx
SOURCES += test_vcl_map.cxx
SOURCES += test_vcl_multimap.cxx
SOURCES += test_vcl_vector.cxx
SOURCES += test_vcl_list.cxx
SOURCES += test_vcl_string.cxx
SOURCES += test_vcl_set.cxx
SOURCES += test_vcl_deque.cxx
SOURCES += test_vcl_complex.cxx
SOURCES += test_vcl_algorithm.cxx
SOURCES += test_vcl_new.cxx
SOURCES += test_vcl_cmath.cxx
SOURCES += test_vcl_stlfwd.cxx
SOURCES += test_vcl_exception.cxx
SOURCES += test_vcl_cctype.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
