TESTMAIN = test_driver.cxx
TESTS += test_cstdio.cxx
PARAMS_test_cstdio := test_cstdio.txt
TESTS += test_compiler.cxx
TESTS += test_iterator.cxx
TESTS += test_iostream.cxx
TESTS += test_fstream.cxx
TESTS += test_map.cxx
TESTS += test_multimap.cxx
TESTS += test_vector.cxx
TESTS += test_list.cxx
TESTS += test_string.cxx
TESTS += test_set.cxx
TESTS += test_deque.cxx
TESTS += test_complex.cxx
TESTS += test_algorithm.cxx
TESTS += test_new.cxx
TESTS += test_cmath.cxx
SOURCES += test_stlfwd.cxx
TESTS += test_exception.cxx
TESTS += test_cctype.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
