ifneq (1,$(strip $(HAS_NATIVE_NETLIB)))
SUBDIRS += netlib
endif

ifneq (1,$(strip $(HAS_NATIVE_JPEG)))
SUBDIRS += jpeg
endif

ifneq (1,$(strip $(HAS_NATIVE_TIFF)))
SUBDIRS += tiff
endif

################################
include ${IUEROOT}/config/top.mk
################################
