USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := bbas_pro
VERSION := 1.0

SOURCES += bbas_register.cxx
SOURCES += bbas_1d_array_float.cxx
MANPAGE_SOURCES += bbas_processes.h

SOURCES += processes/brad_display_sun_index_process.cxx
SOURCES += processes/brad_save_sun_index_process.cxx
SOURCES += processes/brad_sun_dir_bin_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
