USES += contrib/rpl contrib/mul core

LIBRARY := rtvl
VERSION := 1.0

MANPAGE_SOURCES += rtvl_refine.hxx
MANPAGE_SOURCES += rtvl_votee.hxx
MANPAGE_SOURCES += rtvl_weight_smooth.txx
MANPAGE_SOURCES += rtvl_tensor_d.hxx
MANPAGE_SOURCES += rtvl_voter.txx
MANPAGE_SOURCES += rtvl_vote.hxx
MANPAGE_SOURCES += rtvl_intpow.hxx
MANPAGE_SOURCES += rtvl_weight_original.txx
MANPAGE_SOURCES += rtvl_votee.txx
MANPAGE_SOURCES += rtvl_weight.hxx
MANPAGE_SOURCES += rtvl_voter.hxx
MANPAGE_SOURCES += rtvl_tensor.txx
MANPAGE_SOURCES += rtvl_votee_d.hxx
MANPAGE_SOURCES += rtvl_terms.hxx
MANPAGE_SOURCES += rtvl_tensor_d.txx
MANPAGE_SOURCES += rtvl_refine.txx
MANPAGE_SOURCES += rtvl_weight_smooth.hxx
MANPAGE_SOURCES += rtvl_tensor.hxx
MANPAGE_SOURCES += rtvl_vote.txx
MANPAGE_SOURCES += rtvl_votee_d.txx
MANPAGE_SOURCES += rtvl_tokens.hxx
MANPAGE_SOURCES += rtvl_weight_original.hxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests examples
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
