USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk

MINI_PROG_SOURCES += boxm2_multi_render.cxx
MINI_PROG_SOURCES += boxm2_multi_update.cxx

################################
include ${VXLROOT}/config/top.mk
################################
