USES += contrib/brl contrib/brl/bbas core
include ../config.mk

MINI_PROG_SOURCES += bwm_video_corr_proc.cxx
MINI_PROG_SOURCES += bwm_video_planar_reg_proc.cxx
MINI_PROG_SOURCES += bwm_extract_snippets.cxx
MINI_PROG_SOURCES += bwm_transform_video_site_proc.cxx

################################
include ${VXLROOT}/config/top.mk
################################
