# This package contains the Manchester public not-quite VXL libraries

# Basics
SUBDIRS += mbl

# Multivariate PDF objects, builders, samplers, etc.
SUBDIRS += vpdfl pdf1d

# Manchester images 
SUBDIRS += mil mil3d

# Manchester classifier
SUBDIRS += clsfy

################################
include ${IUEROOT}/config/top.mk
################################
