# This package contains the Manchester public not-quite VXL libraries

# Binary IO support for VXL
SUBDIRS += vsl

# Binary IO functions for the level 1 libraries
SUBDIRS += vil vnl vgl vbl

# Basics
SUBDIRS += mbl

# Multivariate PDF objects, builders, samplers, etc.
SUBDIRS += vpdfl

################################
include ${IUEROOT}/config/top.mk
################################
