USES = vxl mul
include ${IUEROOT}/mul/vil3d/io/config.mk
include ${IUEROOT}/vxl/testlib/config.mk

TESTMAIN = test_driver.cxx

TESTS += test_image_view_io.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
