USES += contrib/mul core
include ../config.mk
include $(IUEROOT)/core/vpl/config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_image_view_io.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
