USES = vxl mul
include ${IUEROOT}/mul/vil3d/config.mk
include ${IUEROOT}/vxl/testlib/config.mk

TESTMAIN = test_driver.cxx

TESTS += test_gauss_reduce.cxx
TESTS += test_image_view.cxx
TESTS += test_sample_profile_trilin.cxx
TESTS += test_trilin_interp.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
