USES += contrib/mul core
include ../algo/config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN = test_driver.cxx

TESTS += test_gauss_reduce.cxx
TESTS += test_image_view.cxx
TESTS += test_sample_profile_trilin.cxx
TESTS += test_trilin_interp.cxx
TESTS += test_algo_threshold.cxx
TESTS += test_algo_binary_dilate.cxx
TESTS += test_algo_binary_erode.cxx
TESTS += test_algo_structuring_element.cxx
TESTS += test_algo_exp_filter.cxx
TESTS += test_switch_axes.cxx
TESTS += test_algo_grad_1x3.cxx
TESTS += test_math.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
