USES += contrib/mul core

LIBRARY := msm-tools
VERSION := 1.0

SOURCES += msm_apply_tps_warp.cxx
SOURCES += msm_draw_points_on_image.cxx
SOURCES += msm_draw_shape_modes.cxx
SOURCES += msm_build_shape_model.cxx
SOURCES += msm_plot_aligned_shapes.cxx
SOURCES += msm_get_shape_params.cxx

################################
include ${VXLROOT}/config/top.mk
################################
