#   DESCRIPTION:
#
#   This is the png directory of v3p.  Current version is 1.0.8.

USES := v3p/zlib
USE_STDC++ := 0

LIBRARY := png
VERSION := 1.0.8

SOURCES += png.c
SOURCES += pngset.c
SOURCES += pngget.c
SOURCES += pngrutil.c
SOURCES += pngtrans.c
SOURCES += pngwutil.c
SOURCES += pngread.c
SOURCES += pngrio.c
SOURCES += pngwio.c
SOURCES += pngwrite.c
SOURCES += pngrtran.c
SOURCES += pngwtran.c
SOURCES += pngmem.c
SOURCES += pngerror.c
SOURCES += pngpread.c

################################
include ${IUEROOT}/config/top.mk
################################
