#include <vil/vil_fwd.h>

#include <vil/vil_16bit.h>
#include <vil/vil_32bit.h>
//#include <vil/vil_block_cache_image_impl.h>
#include <vil/vil_byte.h>
#include <vil/vil_byte_swap.h>
#include <vil/vil_clamp.h>
#include <vil/vil_clamp_image.h>
//#include <vil/vil_clamp_image_impl.h>
#include <vil/vil_colour_space.h>
#include <vil/vil_convolve.h>
#include <vil/vil_convolve_simple.h>
#include <vil/vil_copy.h>
#include <vil/vil_crop.h>
//#include <vil/vil_crop_image_impl.h>
#include <vil/vil_file_format.h>
#include <vil/vil_file_image.h>
#include <vil/vil_flip_components.h>
//#include <vil/vil_flip_components_impl.h>
#include <vil/vil_flipud.h>
//#include <vil/vil_flipud_impl.h>
#include <vil/vil_image.h>
#include <vil/vil_image_as.h>
//#include <vil/vil_image_impl.h>
#include <vil/vil_image_proxy.h>
#include <vil/vil_interpolate.h>
#include <vil/vil_ip_traits.h>
#include <vil/vil_jpeglib.h>
#include <vil/vil_load.h>
#include <vil/vil_memory_image.h>
//#include <vil/vil_memory_image_impl.h>
#include <vil/vil_memory_image_of.h>
#include <vil/vil_memory_image_window.h>
#include <vil/vil_ncc.h>
#include <vil/vil_new.h>
#include <vil/vil_open.h>
#include <vil/vil_pixel.h>
#include <vil/vil_property.h>
#include <vil/vil_pyramid.h>
#include <vil/vil_resample.h>
#include <vil/vil_resample_image.h>
//#include <vil/vil_resample_image_impl.h>
#include <vil/vil_rgb.h>
#include <vil/vil_rgb_byte.h>
#include <vil/vil_rgba.h>
#include <vil/vil_save.h>
#include <vil/vil_scale_intensities.h>
#include <vil/vil_scale_intensities_image.h>
//#include <vil/vil_scale_intensities_image_impl.h>
#include <vil/vil_skip.h>
//#include <vil/vil_skip_image_impl.h>
#include <vil/vil_smooth.h>
#include <vil/vil_ssd.h>
#include <vil/vil_stream.h>
#include <vil/vil_stream_core.h>
#include <vil/vil_stream_fstream.h>
#include <vil/vil_stream_section.h>
#include <vil/vil_stream_url.h>
#include <vil/vil_warp.h>

#include <vil/vil_block_cache_image_impl.h>
#include <vil/vil_clamp_image_impl.h>
#include <vil/vil_crop_image_impl.h>
#include <vil/vil_flip_components_impl.h>
#include <vil/vil_flipud_impl.h>
#include <vil/vil_image_impl.h>
#include <vil/vil_memory_image_impl.h>
#include <vil/vil_resample_image_impl.h>
#include <vil/vil_scale_intensities_image_impl.h>
#include <vil/vil_skip_image_impl.h>

int main() { return 0; }
