USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm

TESTMAIN := test_driver.cxx
MANPAGE_SOURCES += test_utils.h
TESTS += test_binary_io.cxx
TESTS += test_block_iter.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
