USES += vxl oul
LIBRARY := ouml
IMMEDIATE_LIBS += -lvnl-algo -lvnl -lvil

SOURCES += eigenfaces.cxx
SOURCES += image_database.cxx
SOURCES += polygon_mesh.cxx
MANPAGE_SOURCES += image_ops.h
MANPAGE_SOURCES += inlines.h
MANPAGE_SOURCES += io.h

################################
include ${IUEROOT}/config/top.mk
################################
