USES += contrib/oul core

LIBRARY := ouml
IMMEDIATE_LIBS += -lvnl-algo -lvnl -lvil

SOURCES += eigenfaces.cxx
SOURCES += image_database.cxx
SOURCES += polygon_mesh.cxx
MANPAGE_SOURCES += image_ops.txx
MANPAGE_SOURCES += io.txx
MANPAGE_SOURCES += inlines.h
MANPAGE_SOURCES += image_convert.txx

################################
include ${IUEROOT}/config/top.mk
################################
