USES += vxl oul
LIBRARY := ouml
IMMEDIATE_LIBS += -lvnl-algo -lvnl -lvil

SOURCES += eigenfaces.cc
SOURCES += image_database.cc
SOURCES += polygon_mesh.cc
MANPAGE_SOURCES += image_ops.h
MANPAGE_SOURCES += inlines.h
MANPAGE_SOURCES += io.h

################################
include ${IUEROOT}/config/top.mk
################################
