USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/brl/bpro/core contrib/brl/bpro contrib/gel core

LIBRARY := bvgl_pro
VERSION := 1.0

SOURCES += bvgl_generate_mask_process.cxx

###################################
include ${VXLROOT}/config/params.mk
###################################
