USES += contrib/brl contrib/brl/bbas core v3p/netlib

LIBRARY := bnl-algo
VERSION := 1.0

SOURCES += bnl_legendre_polynomial.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
