USES += contrib/brl contrib/brl/bbas core

LIBRARY := bnl-algo
VERSION := 1.0

SOURCES += bnl_legendre_polynomial.cxx

#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

# tests
ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
