USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm-algo-sp-pro

SOURCES += boxm_algo_sp_register.cxx
MANPAGE_SOURCES += boxm_algo_sp_processes.h

SOURCES += processes/boxm_update_process.cxx
SOURCES += processes/boxm_volume_visibility_process.cxx
SOURCES += processes/boxm_render_expected_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
