USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

MINI_PROG_SOURCES += boxm2_cpp_update_main.cxx
MINI_PROG_SOURCES += boxm2_cpp_render_main.cxx
MINI_PROG_SOURCES += boxm2_cpp_change_detection_main.cxx

################################
include ${VXLROOT}/config/top.mk
################################
