USES += vxl mul
include ${IUEROOT}/mul/clsfy/config.mk
include ${IUEROOT}/mul/pdf1d/config.mk
include $(IUEROOT)/vxl/vul/config.mk
include $(IUEROOT)/vxl/testlib/config.mk

TESTS += test_binary_hyperplane.cxx
TESTS += test_binary_pdf_classifier.cxx
TESTS += test_k_nearest_neighbour.cxx
TESTS += test_smo_1.cxx
TESTS += test_rbf_svm_smo.cxx
TESTS += test_adaboost.cxx
TESTS += test_binary_threshold_1d.cxx
TESTS += test_direct_boost.cxx
TESTS += test_mean_square_1d.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
