# main package for processing operations using core classes

# vpgl process classes
SUBDIRS += vpgl_pro

# vil process classes
SUBDIRS += vil_pro

# vidl process classes
SUBDIRS += vidl_pro

# brip process classes 
SUBDIRS += brip_pro

# vgl and bvgl process classes 
SUBDIRS += bvgl_pro

################################
include ${VXLROOT}/config/top.mk
################################
