USES = vxl
IULIBS := -lvcl
IULIBS += -lvtol 
IULIBS += -lvbl
IULIBS += -lvsol
IULIBS += -lvnl
IULIBS += -lvgl
VXL := 1

MINI_PROG_SOURCES += example2d.cxx
MINI_PROG_SOURCES += example3d.cxx

################################
include ${IUEROOT}/config/top.mk
################################
