VXL := 1
USES = vxl
IULIBS += -lvtol
IULIBS += -lvsol
IULIBS += -lvgl
IULIBS += -lvbl
IULIBS += -lvnl
IULIBS += -lvcl

MINI_PROG_SOURCES += vtol_topology_example.cxx

MINI_PROG_SOURCES += example2d.cxx
MINI_PROG_SOURCES += example3d.cxx

################################
include ${IUEROOT}/config/top.mk
################################
