

USES = vxl
IULIBS := -lvcl
IULIBS += -lvtol 
IULIBS += -lvbl
IULIBS += -lvsol
IULIBS += -lvnl
IULIBS += -lvgl
VXL := 1

MINI_PROG_SOURCES += vtol_topology_example.cxx


################################
include ${IUEROOT}/config/top.mk
################################
