USES += contrib/brl contrib/brl/bseg core
include ../config.mk
include $(VXLROOT)/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS += test_batch_update.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
