#ifndef bxml_vsol_point_2d_input_converter_sptr_h
#define bxml_vsol_point_2d_input_converter_sptr_h

class bxml_vsol_point_2d_input_converter;

#include <vbl/vbl_smart_ptr.h>

typedef vbl_smart_ptr<bxml_vsol_point_2d_input_converter> bxml_vsol_point_2d_input_converter_sptr;

#endif // bxml_vsol_point_2d_input_converter_sptr_h
