USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boct_util
VERSION := 1.0

MANPAGE_SOURCES += boct_clone_tree.h
MANPAGE_SOURCES += boct_construct_tree.h

################################
include ${VXLROOT}/config/top.mk
################################
