USES += contrib/rpl core

LIBRARY := rgtl
VERSION := 1.0

MANPAGE_SOURCES += rgtl_sqt_cell_geometry.txx rgtl_sqt_cell_geometry.hxx
MANPAGE_SOURCES += rgtl_serialize_vnl_double_3.hxx
MANPAGE_SOURCES += rgtl_compact_tree.txx rgtl_compact_tree.hxx
SOURCES += rgtl_sqt_object_array_triangles_3d.cxx
MANPAGE_SOURCES += rgtl_sqt_object_array_triangles_3d.hxx
MANPAGE_SOURCES += rgtl_compact_tree_link.hxx
MANPAGE_SOURCES += rgtl_object_array_points.txx rgtl_object_array_points.hxx
SOURCES += rgtl_sqt_base.cxx
MANPAGE_SOURCES += rgtl_sqt_base.hxx
MANPAGE_SOURCES += rgtl_octree_dual_element.hxx
MANPAGE_SOURCES += rgtl_tagged_vector.hxx
SOURCES += rgtl_object_array_triangles_3d.cxx
MANPAGE_SOURCES += rgtl_object_array_triangles_3d.hxx
MANPAGE_SOURCES += rgtl_sqt_objects.txx rgtl_sqt_objects.hxx
MANPAGE_SOURCES += rgtl_serialize_base.hxx
MANPAGE_SOURCES += rgtl_serialize_direction.hxx
SOURCES += rgtl_serialize_istream.cxx
MANPAGE_SOURCES += rgtl_serialize_istream.hxx
MANPAGE_SOURCES += rgtl_octree_dual.hxx
MANPAGE_SOURCES += rgtl_compact_tree_index.hxx
MANPAGE_SOURCES += rgtl_compact_tree_data_fixed.hxx
SOURCES += rgtl_serialize_ostream.cxx
MANPAGE_SOURCES += rgtl_serialize_ostream.hxx
MANPAGE_SOURCES += rgtl_separating_axis.hxx
MANPAGE_SOURCES += rgtl_serialize_access.hxx
SOURCES += rgtl_object_once.cxx
MANPAGE_SOURCES += rgtl_object_once.hxx
MANPAGE_SOURCES += rgtl_serialize_stl_vector.hxx
MANPAGE_SOURCES += rgtl_sqt_space.txx rgtl_sqt_space.hxx
MANPAGE_SOURCES += rgtl_object_array.hxx
MANPAGE_SOURCES += rgtl_octree_dual_location.hxx
MANPAGE_SOURCES += rgtl_octree_point_location.txx rgtl_octree_point_location.hxx
MANPAGE_SOURCES += rgtl_compact_tree_policy.hxx
MANPAGE_SOURCES += rgtl_octree_data_fixed.txx rgtl_octree_data_fixed.hxx
MANPAGE_SOURCES += rgtl_sqt_object_array.hxx
MANPAGE_SOURCES += rgtl_config.hxx
MANPAGE_SOURCES += rgtl_separating_axis_projection.hxx
MANPAGE_SOURCES += rgtl_octree_cell_location.txx rgtl_octree_cell_location.hxx
MANPAGE_SOURCES += rgtl_serialize_vnl_vector_fixed.hxx
MANPAGE_SOURCES += rgtl_tagged_index.hxx
MANPAGE_SOURCES += rgtl_octree_dual_visit.hxx
MANPAGE_SOURCES += rgtl_compact_tree_node_data.hxx
MANPAGE_SOURCES += rgtl_object_closest_polygon_3d.hxx
MANPAGE_SOURCES += rgtl_sqt_cell_bounds.txx rgtl_sqt_cell_bounds.hxx
MANPAGE_SOURCES += rgtl_static_assert.hxx
MANPAGE_SOURCES += rgtl_serialize_split.hxx
MANPAGE_SOURCES += rgtl_octree_dual_index.hxx
MANPAGE_SOURCES += rgtl_octree_objects.txx rgtl_octree_objects.hxx
MANPAGE_SOURCES += rgtl_octree_cell_bounds.txx rgtl_octree_cell_bounds.hxx
MANPAGE_SOURCES += rgtl_meta.hxx
MANPAGE_SOURCES += rgtl_sqt_cell_location.txx rgtl_sqt_cell_location.hxx
MANPAGE_SOURCES += rgtl_octree_cell_geometry.txx rgtl_octree_cell_geometry.hxx

# MANPAGE_SOURCES += rgtl_serialize.txt

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
