#ifndef bvpl_kernels_processes_h_
#define bvpl_kernels_processes_h_

#include <bprb/bprb_func_process.h>
#include <bprb/bprb_macros.h>


DECLARE_FUNC_CONS(bvpl_create_edge2d_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_edge3d_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_gauss3d_x_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_gauss3d_xx_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_edge2d_kernel_vector_process);
DECLARE_FUNC_CONS(bvpl_create_edge3d_kernel_vector_process);
DECLARE_FUNC_CONS(bvpl_create_corner2d_kernel_vector_process);
DECLARE_FUNC_CONS(bvpl_create_corner2d_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_gauss3d_xx_kernel_vector_process);
DECLARE_FUNC_CONS(bvpl_load_taylor_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_gauss3d_kernel_process);
DECLARE_FUNC_CONS(bvpl_create_generic_kernel_vector_process);
DECLARE_FUNC_CONS(bvpl_write_generic_kernel_vector_process);

//util
DECLARE_FUNC_CONS(bvpl_create_wc_kernel_vector_process);

#endif
