USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_kernels_pro

SOURCES += bvpl_kernels_register.cxx
MANPAGE_SOURCES += bvpl_kernels_processes.h
SOURCES += processes/bvpl_create_gauss3d_xx_kernel_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_process.cxx
SOURCES += processes/bvpl_create_corner2d_kernel_process.cxx
SOURCES += processes/bvpl_create_gauss3d_x_kernel_process.cxx
SOURCES += processes/bvpl_create_edge2d_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_edge3d_kernel_process.cxx
SOURCES += processes/bvpl_create_gauss3d_xx_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_corner2d_kernel_vector_process.cxx
SOURCES += processes/bvpl_create_wc_kernel_vector_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
