USES += contrib/brl contrib/brl/bbas core

LIBRARY := bsta_vis

SOURCES += bsta_svg_tools.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
