USES += core
include ../config.mk

TESTS += vidl_vil1_test.cxx
MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
