USES += vxl mul

LIBRARY := mil-algo
VERSION := 1.0

SOURCES += mil_algo_exp_filter_1d.cxx
MANPAGE_SOURCES += mil_algo_exp_filter_2d.txx

################################
include ${IUEROOT}/config/top.mk
################################
