USES += contrib/mul core

LIBRARY := mil-algo
VERSION := 1.0

SOURCES += mil_algo_grad_1x3.cxx
SOURCES += mil_algo_grad_3x3.cxx
SOURCES += mil_algo_exp_filter_1d.cxx
MANPAGE_SOURCES += mil_algo_exp_filter_2d.txx
MANPAGE_SOURCES += mil_algo_line_filter.txx
MANPAGE_SOURCES += mil_algo_grad_filter_2d.txx
MANPAGE_SOURCES += mil_algo_gaussian_filter.txx
MANPAGE_SOURCES += mil_algo_brighten_image_2d.txx
MANPAGE_SOURCES += mil_algo_convolve_1d.h

################################
include ${IUEROOT}/config/top.mk
################################
