USES += contrib/mul core

LIBRARY := mipa
VERSION := 1.0

MANPAGE_SOURCES += mipa_orientation_histogram.txx
MANPAGE_SOURCES += mipa_sample_histo_boxes.txx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tools tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
