USES += core
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN = test_driver.cxx
TESTS += test_config.cxx
MINI_PROG_SOURCES += vxl_echo.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
