USES += vxl

LIBRARY := vul-io
VERSION := 1.0

SOURCES += vul_io_user_info.cxx

ifndef NOTEST
SUBDIRS += tests
endif

################################
include ${IUEROOT}/config/top.mk
################################
