USES += core

LIBRARY := vul-io
VERSION := 1.0

SOURCES += vul_io_user_info.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
