USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS := test_histogram.cxx
PARAMS_test_histogram := 18_al05_1770_0365.tif

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
