USES += contrib/brl contrib/brl/bbas core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTS := test_driver.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
