#ifndef volm_spherical_shell_container_sptr_h
#define volm_spherical_shell_container_sptr_h

class volm_spherical_shell_container;
#include <vbl/vbl_smart_ptr.h>
typedef vbl_smart_ptr<volm_spherical_shell_container> volm_spherical_shell_container_sptr;

#endif // volm_spherical_shell_container_sptr_h
