USES += vxl
USE_OPENGL := 1
USE_GTKGLAREA := 1

LIBRARY := vgui-gtk

SOURCES += vgui_gtk.cxx
SOURCES += vgui_gtk_tag.cxx
SOURCES += vgui_gtk_window.cxx
SOURCES += vgui_gtk_adaptor.cxx
SOURCES += vgui_gtk_utils.cxx
SOURCES += vgui_gtk_statusbar.cxx
SOURCES += vgui_gtk_dialog_impl.cxx

################################
include ${IUEROOT}/config/top.mk
################################
