USES += contrib/brl contrib/brl/bseg core

TESTMAIN := test_driver.cxx
TESTS += test_sigma_normalizer.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
