USES += contrib/gel contrib/gel/mrc core

LIBRARY := vpgl
VERSION := 1.0

SOURCES += vpgl_basic_camera.cxx
SOURCES += vpgl_matrix_camera.cxx
SOURCES += vpgl_perspective_camera.cxx

MANPAGE_SOURCES += vpgl_basic_camera_sptr.h
MANPAGE_SOURCES += vpgl_matrix_camera_sptr.h
MANPAGE_SOURCES += vpgl_perspective_camera_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
