USES := vxl gel gel/mrc

LIBRARY := vpgl
VERSION := 1.0

SOURCES += vpgl_basic_camera.cxx
SOURCES += vpgl_matrix_camera.cxx
SOURCES += vpgl_perspective_camera.cxx

################################
include ${IUEROOT}/config/top.mk
################################
