#ifndef VPGL_PERSPECTIVE_CAMERA_H
#define VPGL_PERSPECTIVE_CAMERA_H

class vcsl_perspective_camera;

//*****************************************************************************
// External declarations for values
//*****************************************************************************
#include <vbl/vbl_smart_ptr.h>

typedef vbl_smart_ptr<vpgl_perspective_camera> vcsl_pgl_perspective_camera_ref;

#endif 