USES = vxl
include ${IUEROOT}/vxl/vul/config.mk

TESTS += vul_test_all.cxx
TESTS += vul_test_arg.cxx
TESTS += vul_test_sprintf.cxx
TESTS += vul_test_root_dir.cxx
TESTS += vul_test_temp_filename.cxx
TESTS += vul_test_psfile.cxx
TESTS += vul_test_url.cxx
TESTS += vul_test_file_iterator.cxx

IULIBS := -lvul -lvpl

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
