USES = vxl

TESTS += vul_test_all.cxx
TESTS += vul_test_arg.cxx
TESTS += vul_test_sprintf.cxx
TESTS += vul_test_root_dir.cxx

IULIBS := -lvul

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
