USES += contrib/brl/bpro contrib/brl/bbas core
include ../config.mk

TESTMAIN := test_driver.cxx

SOURCES += bprb_test_process.cxx
TESTS += test_process.cxx
TESTS += test_process_params.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
