USES += vxl gel Carmen

ifdef HAS_CARMEN
PROGRAM := carmen_interface
SOURCES += carmen_interface.cpp
SOURCES += main.cpp
endif

IULIBS += -lvbl -lvul

################################
include ${IUEROOT}/config/top.mk
################################

