USES += vxl gel Carmen
include $(IUEROOT)/vxl/vbl/config.mk
include $(IUEROOT)/vxl/vul/config.mk

ifdef HAS_CARMEN
PROGRAM := carmen_interface
SOURCES += carmen_interface.cpp
SOURCES += main.cpp
endif

################################
include ${IUEROOT}/config/top.mk
################################

