#ifndef bstm_multi_cpp_processes_h_
#define bstm_multi_cpp_processes_h_

#include <bprb/bprb_func_process.h>
#include <bprb/bprb_macros.h>

// the init functions
DECLARE_FUNC_CONS(bstm_multi_cpp_analyze_coherency_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_change_btw_frames_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_copy_data_to_future_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_export_point_cloud_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_extract_point_cloud_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_ingest_boxm2_scene_process);
DECLARE_FUNC_CONS(bstm_multi_cpp_refine_spacetime_process);

#endif
