USES += contrib/mul core

LIBRARY := vimt-algo
VERSION := 1.0

SOURCES += vimt_dummy.cxx
MANPAGE_SOURCES += vimt_convolve_2d.h
MANPAGE_SOURCES += vimt_find_peaks.h
MANPAGE_SOURCES += vimt_find_troughs.h
MANPAGE_SOURCES += vimt_normalised_correlation_2d.h

################################
include ${IUEROOT}/config/top.mk
################################
