# makefile for rply library, for reading & writing .PLY files

USES = # nothing!
IULIBS = # no dependencies whatsoever

LIBRARY := rply
VERSION := 1.0

SOURCES += rply.c

################################
include ${VXLROOT}/config/top.mk
################################
