USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := brec_batch
VERSION := 1.0

SOURCES += reg_brec.cxx

################################
include ${VXLROOT}/config/top.mk
################################
