USES += contrib/oul core

LIBRARY := ouel
IMMEDIATE_LIBS += -lvnl-algo -lvnl

SOURCES += kalman_filter.cxx

################################
include ${IUEROOT}/config/top.mk
################################
