USES += core

IMMEDIATE_LIBS := -lvil -lvnl

LIBRARY := geml
VERSION := 1.0

SOURCES += geml_matcher.cxx
SOURCES += geml_matcher_correlation.cxx

################################
include ${IUEROOT}/config/top.mk
################################
