#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

USES := vxl

IMMEDIATE_LIBS := -lvcl

LIBRARY := geml
VERSION := 1.0

INCDIRS = ..

SOURCES += geml_matcher.cxx
SOURCES += geml_matcher_correlation.cxx


######################################
include ${IUEROOT}/config/top-rules.mk
######################################
