USES += contrib/brl contrib/brl/bbas core

LIBRARY := cfg
VERSION := 1.0

SOURCES += cvg_hemisphere_tableau.cxx
SOURCES += cvg_hemisphere_view.cxx

################################
include ${VXLROOT}/config/top.mk
################################
