USES += core contrib/brl contrib/brl/bbas
include ../config.mk

TESTMAIN := test_driver.cxx
TESTS += test_crs_index.cxx
TESTS += test_sparse_lst_sqr_function.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
