USES += core contrib/brl contrib/brl/bbas
include ../config.mk

#TESTS += test_bnl_all.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
