# DESCRIPTION:
#
#   This is the vipl_with_vbl_array_2d library, containing the (templated)
#   image processing algorithm implementations for vxl, specialised for
#   the class "vbl_array_2d" (instead of vil_image) as 2D pixel container.
#

USES += vxl tbl

LIBRARY := vipl_with_vbl_array_2d
VERSION := 1.0

MANPAGE_SOURCES += accessors/vipl_accessors_vbl_array_2d.txx

################################
include ${IUEROOT}/config/top.mk
################################

# compile with -O2 for efficiency:
debug = $(optimize)

