# This is the misc conversions directory makefile

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS := tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
