# This is the matrix/vector conversions directory makefile

USES := Numerics vxl
IMMEDIATE_LIBS := -liue-math -lvnl

SUBDIRS := tests

MANPAGE_SOURCES += vnl_matrix_to_IUE_matrix.h
MANPAGE_SOURCES += vnl_matrix_to_vbl_array.h
MANPAGE_SOURCES += vnl_matrix_to_CoolMatrix.h
MANPAGE_SOURCES += IUE_matrix_to_vnl_matrix.h
MANPAGE_SOURCES += vbl_array_to_vnl_matrix.h
MANPAGE_SOURCES += CoolMatrix_to_vnl_matrix.h
MANPAGE_SOURCES += vnl_vector_to_IUE_vector.h
MANPAGE_SOURCES += vnl_vector_to_vbl_array.h
MANPAGE_SOURCES += vnl_vector_to_CoolVector.h
MANPAGE_SOURCES += IUE_vector_to_vnl_vector.h
MANPAGE_SOURCES += vbl_array_to_vnl_vector.h
MANPAGE_SOURCES += CoolVector_to_vnl_vector.h

################################
include ${IUEROOT}/config/top.mk
################################
