USES += contrib/mul core
include ../config.mk

MINI_PROG_SOURCES += find_matches.cxx
MINI_PROG_SOURCES += mr_find_matches.cxx

################################
include ${VXLROOT}/config/top.mk
################################
