USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bvpl_octree_sample
VERSION := 1.0

SOURCES += bvpl_taylor_basis_sample.cxx
MANPAGE_SOURCES += bvpl_octree_sample.txx
MANPAGE_SOURCES += bvpl_pca_basis_sample.txx

################################
include ${VXLROOT}/config/top.mk
################################
