#
# crossge@crd.ge.com
#
#######################################
include ${IUEROOT}/config/top-params.mk
#######################################

USES := vxl

LIBRARY := gst
VERSION := 1.0

SOURCES += gst_vertex_2d.cxx
SOURCES += gst_edge_2d.cxx
SOURCES += gst_polygon_2d.cxx
SOURCES += gst_face_2d.cxx

SOURCES += gst_polygon_2d_operators.cxx

######################################
include ${IUEROOT}/config/top-rules.mk
######################################
