USES += core

LIBRARY := gst
VERSION := 1.0

SOURCES += gst_vertex_2d.cxx
SOURCES += gst_edge_2d.cxx
SOURCES += gst_polygon_2d.cxx
SOURCES += gst_face_2d.cxx

SOURCES += gst_polygon_2d_operators.cxx

MANPAGE_SOURCES += gst_edge_2d_sptr.h
MANPAGE_SOURCES += gst_polygon_2d_sptr.h
MANPAGE_SOURCES += gst_vertex_2d_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
