USES += contrib/prip core
include ../config.mk

TESTS += vdtop_kernel_test.cxx
MINI_PROG_SOURCES += vdtop_veinerization_test.cxx
TESTS += vdtop_well_composed_kernel_test.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
