USES += contrib/brl contrib/brl/bbas core
USE_EXPAT := 1

LIBRARY := bwm_io
VERSION := 1.0

SOURCES += bwm_io_config_parser.cxx
MANPAGE_SOURCES += bwm_io_structs.h

################################
include ${VXLROOT}/config/top.mk
################################
