USES += core
include ../config.mk
include ${VXLROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx

TESTS += test_ellipsoid.cxx
TESTS += test_fit_conics_2d.cxx
TESTS += test_homg.cxx
TESTS += test_compute_similarity_3d.cxx
TESTS += test_h_matrix_1d.cxx
TESTS += test_orient_box_3d.cxx
TESTS += test_fit_lines_2d.cxx
TESTS += test_h_matrix_2d.cxx
TESTS += test_rtree.cxx
TESTS += test_rotation_3d.cxx
TESTS += test_conic.cxx
TESTS += test_h_matrix_3d.cxx
TESTS += test_convex_hull_2d.cxx
TESTS += test_intersection.cxx
TESTS += test_p_matrix.cxx
TESTS += test_fit_plane_3d.cxx

MINI_PROG_SOURCES += test_include.cxx
MINI_PROG_SOURCES += test_template_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
