#include <vgl/algo/vgl_algo_fwd.h>

#include <vgl/algo/vgl_compute_similarity_3d.h>
#include <vgl/algo/vgl_conic_2d_regression.h>
#include <vgl/algo/vgl_convex_hull_2d.h>
#include <vgl/algo/vgl_fit_conics_2d.h>
#include <vgl/algo/vgl_fit_lines_2d.h>
#include <vgl/algo/vgl_fit_plane_3d.h>
#include <vgl/algo/vgl_fit_sphere_3d.h>
#include <vgl/algo/vgl_fit_quadric_3d.h>
#include <vgl/algo/vgl_h_matrix_1d.h>
#include <vgl/algo/vgl_h_matrix_1d_compute.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_3point.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_linear.h>
#include <vgl/algo/vgl_h_matrix_1d_compute_optimize.h>
#include <vgl/algo/vgl_h_matrix_2d.h>
#include <vgl/algo/vgl_h_matrix_2d_compute.h>
#include <vgl/algo/vgl_h_matrix_2d_compute_4point.h>
#include <vgl/algo/vgl_h_matrix_2d_compute_linear.h>
#include <vgl/algo/vgl_h_matrix_2d_compute_rigid_body.h>
#include <vgl/algo/vgl_h_matrix_2d_optimize.h>
#include <vgl/algo/vgl_h_matrix_2d_optimize_lmq.h>
#include <vgl/algo/vgl_h_matrix_3d.h>
#include <vgl/algo/vgl_h_matrix_3d_compute.h>
#include <vgl/algo/vgl_h_matrix_3d_compute_linear.h>
#include <vgl/algo/vgl_homg_operators_1d.h>
#include <vgl/algo/vgl_homg_operators_2d.h>
#include <vgl/algo/vgl_homg_operators_3d.h>
#include <vgl/algo/vgl_intersection.h>
#include <vgl/algo/vgl_line_2d_regression.h>
#include <vgl/algo/vgl_norm_trans_2d.h>
#include <vgl/algo/vgl_norm_trans_3d.h>
#include <vgl/algo/vgl_orient_box_3d.h>
#include <vgl/algo/vgl_orient_box_3d_operators.h>
#include <vgl/algo/vgl_p_matrix.h>
#include <vgl/algo/vgl_rotation_3d.h>
#include <vgl/algo/vgl_rtree.h>
#include <vgl/algo/vgl_rtree_c.h>

int main() { return 0; }
