USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

TESTMAIN := test_driver.cxx
TESTS += test_cell_vis_graph.cxx
TESTS += test_block_vis_graph.cxx

MINI_PROG_SOURCES += test_include.cxx
MINI_PROG_SOURCES += test_template_include.cxx

#########################################
include ${VXLROOT}/config/static-tests.mk
#########################################
