USES += contrib/brl contrib/brl/bmvl contrib/brl/bbas contrib/brl/bseg contrib/gel contrib/oxl core
include ${IUEROOT}/core/vgui/config.mk

LIBRARY := bmvv
VERSION := 1.0

#SOURCES += bmvv_multiview_manager.cxx
#SOURCES += bmvv_tomography_manager.cxx
SOURCES += bmvv_recon_manager.cxx
SOURCES += bmvv_cal_manager.cxx

#SOURCES += bmvv_menus.cxx
#SOURCES += bmvv_tomg_menus.cxx
SOURCES += bmvv_recon_menus.cxx
SOURCES += bmvv_cal_menus.cxx

SUBDIRS += mvbin

################################
include ${IUEROOT}/config/top.mk
################################
