USES += contrib/brl contrib/brl/bbas contrib/brl/bseg contrib/gel contrib/oxl core

LIBRARY := bmvv
VERSION := 1.0

SOURCES += bmvv_multiview_manager.cxx

SUBDIRS += mvbin

################################
include ${IUEROOT}/config/top.mk
################################
