USES = v3p vxl oxl

IULIBS += -lmvl -lvgl -lvil -lvnl-algo -lnetlib -lvnl -lvbl -lvpl -lvcl

MINI_PROG_SOURCES += mvl_multi_view_matches_example.cxx

include ${IUEROOT}/vxl/vil/vil_config.mk

################################
include ${IUEROOT}/config/top.mk
################################
