USES += contrib/oxl core
include ../config.mk
include ${IUEROOT}/core/vil/config.mk
include $(IUEROOT)/core/vpl/config.mk

MINI_PROG_SOURCES += mvl_multi_view_matches_example.cxx
MINI_PROG_SOURCES += compute_FMatrix_example.cxx
MINI_PROG_SOURCES += PMatrixDecompCR_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
