USES = oxl vxl

ald_libs += mvl
IULIBS += -lmvl -lvgl -lvil -lvnl-algo -lvnl -lvbl -lvcl

MINI_PROG_SOURCES += mvl_multi_view_matches_example.cxx

####################
include ../client.mk
################################
include ${IUEROOT}/config/top.mk
################################
