USES += core
include ../config.mk
include ${VXLROOT}/core/vbl/config.mk

MINI_PROG_SOURCES += vidl_vil1_mpegcodec_example.cxx
MINI_PROG_SOURCES += vidl_vil1_video2images.cxx

################################
include ${VXLROOT}/config/top.mk
################################
