# DESCRIPTION:
#
#   This is the vipl_with_vnl_matrix library, containing the (templated)
#   image processing algorithm implementations for vxl, specialised for
#   the class "vnl_matrix" (instead of vil_image) as 2D pixel container.
#

USES += vxl tbl

LIBRARY := vipl_with_vnl_matrix
VERSION := 1.0

################################
include ${IUEROOT}/config/top.mk
################################

# compile with -O2 for efficiency:
debug = $(optimize)

