

USES = vxl
IULIBS := -lvcl -lvbl
VXL := 1

MINI_PROG_SOURCES += vbl_smart_ptr_example.cxx
MINI_PROG_SOURCES += vbl_rgb_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
