USES += core
IULIBS += -lvbl-examples
include ../config.mk

LIBRARY := vbl-examples

MINI_PROG_SOURCES += vbl_smart_ptr_example.cxx

################################
include ${IUEROOT}/config/top.mk
################################
