################################
include ${IUEROOT}/config/usr_params.mk
################################

USES = vxl

LIBRARY := vbl-examples
IULIBS := -lvbl-examples -lvbl -lvcl

MINI_PROG_SOURCES += vbl_smart_ptr_example.cxx
MINI_PROG_SOURCES += vbl_sequence_filename_example.cxx
MINI_PROG_SOURCES += $(wildcard vbl_get_argc_argv_example.cxx)

################################
include ${IUEROOT}/config/usr_rules.mk
################################
