% \input awffonts % should be *before* atexinfo.tex
\input atexinfo   @c -*-texinfo-*-

@include book_header.texi

@c -----------------------------------------------------------------------------

@node Top, Introduction, (dir), (dir)

@ifinfo
This documents the image-processing module from the VXL collection of C++ libraries.

Copyright 2002-2013 VXL Contributors

Permission is granted to copy and distribute, retaining this
original copyright notice.
@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@iftex
@titlepage
@title V@emph{X}L
@subtitle A collection of C++ libraries for computer vision.
@author VXL Contributors

@c  The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2002-2013 VXL Contributors
@end titlepage
@shortcontents
@contents
@end iftex

@menu
* Introduction::
* eg::
* vipl::
* Concept Index::
@end menu

@node    Introduction, eg, Top, Top
@comment node-name, next,           previous, up
@chapter Introduction
@cindex Introduction
@cindex IUE
@cindex TargetJr

@include chapter_intro.texi

@comment ------------------------------------------------------------------
@node    eg, vipl, Introduction, Top
@comment node-name, next, previous,     up
@chapter vxl example programs

@include chapter_examples.texi

@comment ------------------------------------------------------------------
@node    vipl, eg, Top
@comment node-name, next, previous,     up
@chapter vipl: Templated Image Processing Library
@cindex vipl
@cindex Image Processing

@include chapter_vipl.texi
@include chapter_vepl.texi

@comment ------------------------------------------------------------------
@node    Concept Index,  , vcsl, Top
@c        node-name,    next, previous,        up
@unnumbered Concept Index

@printindex cp

@bye
