USES += contrib/mul core
include ../config.mk

MINI_PROG_SOURCES += mfpf_build_finder.cxx
MINI_PROG_SOURCES += mfpf_test_finder.cxx

################################
include ${VXLROOT}/config/top.mk
################################
