USES += contrib/oul core
include ../config.mk
include ${VXLROOT}/core/vul/config.mk

MINI_PROG_SOURCES += example1.cxx

################################
include ${VXLROOT}/config/top.mk
################################
