USES += contrib/oul core
include ../config.mk
include ${IUEROOT}/core/vul/config.mk

MINI_PROG_SOURCES += example1.cxx

################################
include ${IUEROOT}/config/top.mk
################################
