USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
