USES += contrib/oxl core
include $(VXLROOT)/core/vgui/config.mk
include $(VXLROOT)/contrib/oxl/oxp/config.mk

MINI_PROG_SOURCES += glmovie.cxx

SUBDIRS += awfmfc

################################
include ${VXLROOT}/config/top.mk
################################
