USES += contrib/oxl core
include $(IUEROOT)/core/vgui/config.mk
include $(IUEROOT)/contrib/oxl/oxp/config.mk

MINI_PROG_SOURCES += glmovie.cxx

SUBDIRS += awfmfc

################################
include ${IUEROOT}/config/top.mk
################################
