USES += vxl oxl

USE_OPENGL := 1
USE_GLUT   := 1
#USE_GTK   := 1

MINI_PROG_SOURCES += glmovie.cxx

SUBDIRS += awfmfc

##########################################
include $(IUELOCALROOT)/oxl/vgui/config.mk
include $(IUELOCALROOT)/oxl/oxp/config.mk
include ${IUEROOT}/config/top.mk
################################
