USES += contrib/oxl core
include $(VXLROOT)/core/vgui/config.mk
include $(VXLROOT)/contrib/oxl/osl/config.mk
include $(VXLROOT)/contrib/oxl/mvl/config.mk

PROGRAM = vgui_testbed

SOURCES += vgui_testbed.cxx
SOURCES += vgui_point_selector.cxx

MANPAGE_SOURCES += vgui_point_selector_sptr.h

################################
include ${VXLROOT}/config/top.mk
################################
