USES += contrib/oxl core
include $(IUEROOT)/core/vgui/config.mk
include $(IUEROOT)/contrib/oxl/osl/config.mk
include $(IUEROOT)/contrib/oxl/mvl/config.mk

PROGRAM = vgui_testbed

SOURCES += vgui_testbed.cxx
SOURCES += vgui_point_selector.cxx

MANPAGE_SOURCES += vgui_point_selector_sptr.h

################################
include ${IUEROOT}/config/top.mk
################################
