USES += contrib/mul core

LIBRARY := fhs
VERSION := 1.0

SOURCES += fhs_arc.cxx
SOURCES += fhs_searcher.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
 SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
