USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_util_io

SOURCES += bvpl_corner_pairs_io.cxx
SOURCES += bvpl_bundler_features_2d_io.cxx

#######################################
include ${VXLROOT}/config/top-params.mk
#######################################

ifndef NOTEST
SUBDIRS += tests
endif

######################################
include ${VXLROOT}/config/top-rules.mk
######################################
