USES += contrib/brl contrib/brl/bseg core

LIBRARY := bvpl_util_io

SOURCES += bvpl_corner_pairs_io.cxx

################################
include ${VXLROOT}/config/top.mk
################################
