USES += vxl
IULIBS := -lvgl-io -lvgl -lvsl

TESTS += test_vgl_io.cxx # includes test_homg_plane_3d_io.cxx test_point_2d_io.cxx test_point_3d_io.cxx test_homg_point_2d_io.cxx test_homg_point_3d_io.cxx test_line_segment_2d_io.cxx test_line_segment_3d_io.cxx test_line_2d_io.cxx test_homg_line_2d_io.cxx test_homg_line_3d_2_points_io.cxx test_box_2d_io.cxx test_box_3d_io.cxx test_polygon_io.cxx golden_test_vgl_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
