USES += vxl 
USES += mul
IULIBS := -lvgl-io -lvgl -lvsl

MINI_PROG_SOURCES += test_polygon_scan_iterator_io.cxx

TESTS += test_vgl_io.cxx 
TESTS += golden_test_vgl_io.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
