USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm2_ocl

SOURCES += boxm2_opencl_cache.cxx
SOURCES += boxm2_opencl_processor.cxx
SOURCES += boxm2_opencl_render_depth_process.cxx
SOURCES += boxm2_opencl_render_process.cxx
MANPAGE_SOURCES += boxm2_opencl_process_base.h
SOURCES += boxm2_opencl_update_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
