USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm-algo-pro

SOURCES += boxm_algo_register.cxx
MANPAGE_SOURCES += boxm_algo_processes.h

SOURCES += processes/boxm_split_scene_process.cxx
SOURCES += processes/boxm_save_scene_vrml.cxx
SOURCES += processes/boxm_merge_mixtures_process.cxx
SOURCES += processes/boxm_crop_scene_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
