USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := boxm-algo-pro

SOURCES += boxm_algo_register.cxx
MANPAGE_SOURCES += boxm_algo_processes.h

SOURCES += processes/boxm_save_occupancy_raw_process.cxx
SOURCES += processes/boxm_roi_init_rational_camera_process.cxx
SOURCES += processes/boxm_describe_scene_process.cxx
SOURCES += processes/boxm_line_backproject_process.cxx
SOURCES += processes/boxm_init_scene_process.cxx
SOURCES += processes/boxm_refine_scene_process.cxx
SOURCES += processes/boxm_roi_init_process.cxx
SOURCES += processes/boxm_replace_const_app_process.cxx
SOURCES += processes/boxm_render_expected_edge_vrml_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
