USES += contrib/oxl core
include ${IUEROOT}/core/vgui/config.mk
USE_MOTIFGL := 1

PROGRAM := test_motif

SOURCES += test_motif.cxx

################################
include ${IUEROOT}/config/top.mk
################################
