USES := vxl oxl
USE_MOTIFGL := 1

PROGRAM := test_motif

SOURCES += test_motif.cxx

###########################################
include ${IUELOCALROOT}/oxl/vgui/config.mk
include ${IUEROOT}/config/top.mk
################################
