USES += contrib/oxl core
include ${VXLROOT}/core/vgui/config.mk
USE_MOTIFGL := 1

PROGRAM := test_motif

SOURCES += test_motif.cxx

################################
include ${VXLROOT}/config/top.mk
################################
