USES += contrib/brl contrib/brl/bbas core

LIBRARY := bvxm_grid_io
VERSION := 1.0

SOURCES += bvxm_io_voxel_slab_base.cxx
MANPAGE_SOURCES += bvxm_io_voxel_grid.h
SOURCES += bvxm_io_voxel_grid_base.cxx
MANPAGE_SOURCES += bvxm_slab_to_image.h
MANPAGE_SOURCES += bvxm_grid_to_image_stack.h

################################
include ${VXLROOT}/config/top.mk
################################
