USES += contrib/brl contrib/brl/bbas core

LIBRARY := bvxm_grid_io
VERSION := 1.0

SOURCES += bvxm_io_voxel_slab_base.cxx
MANPAGE_SOURCES += bvxm_io_voxel_grid.h
SOURCES += bvxm_io_voxel_grid_base.cxx

################################
include ${VXLROOT}/config/top.mk
################################
