USES += contrib/brl contrib/brl/bbas contrib/brl/bseg core

LIBRARY := bvpl_octree_io

SOURCES += bvpl_io_pca_error_scenes.cxx
SOURCES += bvpl_io_discover_pca_kernels.cxx
SOURCES += bvpl_io_taylor_scenes_map.cxx

################################
include ${VXLROOT}/config/top.mk
################################
