USES += contrib/brl contrib/gel contrib/brl/bbas core
include ../config.mk
include ${IUEROOT}/contrib/gel/vdgl/config.mk
include ${IUEROOT}/contrib/gel/vtol/config.mk
include ${IUEROOT}/core/vnl/config.mk

TESTS += test_curve_algs.cxx

MINI_PROG_SOURCES += test_include.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
