USES += contrib/gel contrib/brl/bseg core

LIBRARY := vifa
VERSION := 1.0

MANPAGE_SOURCES += vifa_typedefs.h
SOURCES += vifa_coll_lines.cxx
SOURCES += vifa_coll_lines_params.cxx
SOURCES += vifa_gaussian.cxx
SOURCES += vifa_group_pgram.cxx
SOURCES += vifa_group_pgram_params.cxx
SOURCES += vifa_histogram.cxx
SOURCES += vifa_image_histogram.cxx
MANPAGE_SOURCES += vifa_imp_line.txx
SOURCES += vifa_incr_var.cxx
SOURCES += vifa_int_face_attr.cxx
SOURCES += vifa_int_face_attr_common.cxx
SOURCES += vifa_int_face_attr_common_params.cxx
MANPAGE_SOURCES += vifa_int_face_attr_factory.h
SOURCES += vifa_int_faces_adj_attr.cxx
SOURCES += vifa_int_faces_attr.cxx
SOURCES += vifa_line_cover.cxx
SOURCES += vifa_norm_params.cxx
SOURCES += vifa_parallel.cxx
SOURCES += vifa_parallel_params.cxx
MANPAGE_SOURCES += vifa_bbox.h

################################
include ${IUEROOT}/config/top.mk
################################
