USES += contrib/brl contrib/gel contrib/brl/bbas contrib/brl/bseg core
include ../config.mk
include ${IUEROOT}/core/testlib/config.mk

TESTMAIN := test_driver.cxx
TESTS += test_histogram.cxx
TESTS += test_mutual_info.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
