#include <brip/brip_blobwise_mutual_info.h>
#include <brip/brip_filter_bank.h>
#include <brip/brip_gain_offset_solver.h>
#include <brip/brip_gaussian_kernel.h>
#include <brip/brip_histogram.h>
#include <brip/brip_interp_kernel.h>
#include <brip/brip_kernel.h>
#include <brip/brip_label_equivalence.h>
#include <brip/brip_line_generator.h>
#include <brip/brip_max_scale_response.h>
#include <brip/brip_mutual_info.h>
#include <brip/brip_para_cvrg.h>
#include <brip/brip_para_cvrg_params.h>
#include <brip/brip_quadtree_node.h>
#include <brip/brip_quadtree_node_base_sptr.h>
#include <brip/brip_quadtree_utils.h>
#include <brip/brip_rect_mask.h>
#include <brip/brip_region_pixel.h>
#include <brip/brip_region_pixel_sptr.h>
#include <brip/brip_roi.h>
#include <brip/brip_roi_sptr.h>
#include <brip/brip_subpix_convolution.h>
#include <brip/brip_vil1_float_ops.h>
#include <brip/brip_vil_float_ops.h>
#include <brip/brip_vil_ops.h>
#include <brip/brip_watershed.h>
#include <brip/brip_watershed_params.h>
#include <brip/brip_vil_nitf_ops.h>

int main() { return 0; }
