USES += contrib/brl contrib/brl/bbas contrib/brl/bpro core

LIBRARY := vidl_pro
VERSION := 1.0

SOURCES += vidl_io_istream.cxx
SOURCES += vidl_io_ostream.cxx
SOURCES += vidl_pro_utils.cxx
SOURCES += vidl_register.cxx

MANPAGE_SOURCES += vidl_processes.h
SOURCES += processes/vidl_open_ostream_process.cxx
SOURCES += processes/vidl_get_frame_istream_process.cxx
SOURCES += processes/vidl_close_istream_process.cxx
SOURCES += processes/vidl_open_istream_process.cxx
SOURCES += processes/vidl_open_dshow_istream_process.cxx
SOURCES += processes/vidl_put_frame_ostream_process.cxx
SOURCES += processes/vidl_close_ostream_process.cxx

################################
include ${VXLROOT}/config/top.mk
################################
