USES += vxl
USES += mul
IULIBS := -lvpdfl -lmbl -lvnl-io -lvnl-algo -lnetlib -lvnl -lvsl

TESTS += test_vpdfl.cxx # includes test_gaussian.cxx test_axis_gaussian.cxx test_pc_gaussian.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
