USES += vxl mul
include ${IUEROOT}/mul/vpdfl/config.mk
include $(IUEROOT)/vxl/testlib/config.mk

TESTS += test_vpdfl.cxx # includes test_gaussian.cxx test_axis_gaussian.cxx test_pc_gaussian.cxx

################################
#include ${IUEROOT}/config/top.mk
include ${IUEROOT}/config/static-tests.mk
################################
