USES += contrib/mul core
include ../config.mk
include $(IUEROOT)/core/vpl/config.mk
include $(IUEROOT)/core/testlib/config.mk

TESTS += test_vpdfl.cxx # includes test_gaussian.cxx test_axis_gaussian.cxx test_pc_gaussian.cxx

#########################################
include ${IUEROOT}/config/static-tests.mk
#########################################
